// Pregnancy complications data

export interface ComplicationData {
  slug: string
  title: string
  category: 'high-risk' | 'common' | 'serious' | 'infection' | 'placental' | 'genetic'
  severity: 'mild' | 'moderate' | 'serious' | 'critical'
  howCommon: string
  shortDescription: string
  detailedDescription: string[]
  symptoms: string[]
  causes: string[]
  riskFactors: string[]
  diagnosis: string[]
  treatment: string[]
  prevention: string[]
  complications: string[]
  whenToCallDoctor: string[]
  relatedConditions: string[]
}

export const complicationsData: ComplicationData[] = [
  {
    slug: 'gestational-diabetes',
    title: 'Gestational Diabetes',
    category: 'common',
    severity: 'moderate',
    howCommon: 'Affects 2-10% of pregnancies in the US',
    shortDescription: 'High blood sugar that develops during pregnancy, usually diagnosed between 24-28 weeks.',
    detailedDescription: [
      'Gestational diabetes occurs when your body cannot produce enough insulin during pregnancy to keep blood sugar at healthy levels. Pregnancy hormones make your cells more resistant to insulin, and some women\'s bodies can\'t keep up with the increased insulin demand.',
      'Most women with gestational diabetes have healthy pregnancies and babies with proper management. The condition usually resolves after delivery, though it increases risk of developing type 2 diabetes later in life.',
      'Management involves monitoring blood sugar levels, eating a balanced diet, exercising regularly, and sometimes medication. With treatment, most women deliver healthy babies at term.',
    ],
    symptoms: [
      'Often no obvious symptoms',
      'Increased thirst',
      'Frequent urination (more than typical for pregnancy)',
      'Fatigue beyond normal pregnancy tiredness',
      'Sugar in urine (detected at prenatal visits)',
      'Diagnosed through glucose tolerance test',
    ],
    causes: [
      'Pregnancy hormones blocking insulin action (insulin resistance)',
      'Pancreas unable to produce enough extra insulin',
      'Pre-existing insulin resistance',
      'Weight gain during pregnancy',
      'Placental hormones affecting insulin',
    ],
    riskFactors: [
      'Overweight or obese before pregnancy (BMI over 30)',
      'Age over 25',
      'Family history of diabetes',
      'Previous gestational diabetes',
      'Previous baby over 9 pounds',
      'PCOS (polycystic ovary syndrome)',
      'Prediabetes',
      'African American, Hispanic, Asian, Native American ethnicity',
      'Physically inactive',
    ],
    diagnosis: [
      'Glucose challenge test at 24-28 weeks (standard screening)',
      'One-hour test with 50g glucose drink',
      'If screening positive: three-hour glucose tolerance test',
      'Fasting blood sugar, then glucose drink, blood drawn at 1, 2, 3 hours',
      'Diagnosed if 2 or more values elevated',
      'Some women tested earlier if high risk',
    ],
    treatment: [
      'Monitor blood sugar 4 times daily (fasting and after meals)',
      'Follow diabetic diet - control carbohydrates',
      'Regular exercise (walking 30 minutes daily)',
      'Count carbohydrates and spread throughout day',
      'Avoid refined sugars and simple carbs',
      'Medication if diet/exercise insufficient (metformin or insulin)',
      'More frequent prenatal visits and ultrasounds',
      'Fetal monitoring in third trimester',
      'Possible induction at 39-40 weeks',
    ],
    prevention: [
      'Maintain healthy weight before pregnancy',
      'Lose excess weight before conceiving',
      'Exercise regularly before and during pregnancy',
      'Eat balanced diet low in refined carbohydrates',
      'Gain recommended pregnancy weight (not excessive)',
      'If previous GDM, early screening and lifestyle changes',
    ],
    complications: [
      'Large baby (macrosomia) - over 9 lbs',
      'Increased C-section risk',
      'Baby\'s low blood sugar at birth (hypoglycemia)',
      'Preterm birth',
      'Preeclampsia',
      'Polyhydramnios (too much amniotic fluid)',
      'Stillbirth (rare with good control)',
      'Future type 2 diabetes risk for mother (50% develop within 10 years)',
      'Baby\'s increased obesity and diabetes risk later in life',
    ],
    whenToCallDoctor: [
      'Blood sugar readings consistently above target',
      'Blood sugar very low (under 60)',
      'Unable to keep food or fluids down',
      'Signs of infection',
      'Decreased fetal movement',
      'Unusual symptoms or concerns',
      'Difficulty following diet plan',
    ],
    relatedConditions: ['preeclampsia', 'macrosomia', 'polyhydramnios', 'type-2-diabetes'],
  },
  {
    slug: 'preeclampsia',
    title: 'Preeclampsia',
    category: 'serious',
    severity: 'serious',
    howCommon: 'Affects 5-8% of pregnancies',
    shortDescription: 'Serious pregnancy complication causing high blood pressure and organ damage, typically after 20 weeks.',
    detailedDescription: [
      'Preeclampsia is a serious condition characterized by high blood pressure and signs of damage to organs, most often the liver and kidneys. It typically develops after 20 weeks of pregnancy and can progress rapidly.',
      'The only cure for preeclampsia is delivery of the baby, though symptoms may persist postpartum. Mild preeclampsia can be managed with careful monitoring, while severe preeclampsia requires immediate treatment and often early delivery.',
      'Without treatment, preeclampsia can lead to serious complications for both mother and baby including seizures (eclampsia), stroke, organ failure, and placental abruption. Early detection through prenatal care is crucial.',
    ],
    symptoms: [
      'High blood pressure (over 140/90)',
      'Protein in urine',
      'Severe headaches that don\'t respond to medication',
      'Vision changes (blurry, seeing spots, light sensitivity)',
      'Upper abdominal pain (right side under ribs)',
      'Nausea and vomiting in second half of pregnancy',
      'Sudden weight gain (more than 2 lbs per week)',
      'Severe swelling of face and hands',
      'Decreased urination',
      'Shortness of breath',
    ],
    causes: [
      'Exact cause unknown',
      'Problems with placental blood vessels',
      'Immune system issues',
      'Insufficient blood flow to uterus',
      'Blood vessel damage',
      'Genetic factors',
    ],
    riskFactors: [
      'First pregnancy',
      'New partner (first pregnancy with current partner)',
      'Age over 35 or under 20',
      'Obesity',
      'Multiple pregnancy (twins, triplets)',
      'History of preeclampsia in previous pregnancy',
      'Family history of preeclampsia',
      'Chronic hypertension',
      'Kidney disease',
      'Diabetes',
      'Autoimmune diseases (lupus)',
      'IVF pregnancy',
      'More than 10 years since last pregnancy',
    ],
    diagnosis: [
      'Blood pressure readings over 140/90 on two occasions',
      'Protein in urine (24-hour collection or protein/creatinine ratio)',
      'Blood tests checking liver enzymes, kidney function, platelets',
      'Checking for signs of organ damage',
      'Fetal ultrasound and monitoring',
      'May be diagnosed without protein in urine if severe features present',
    ],
    treatment: [
      'Mild: Close monitoring, blood pressure checks, urine tests, fetal monitoring',
      'Moderate: Bed rest, limited activity, frequent appointments',
      'Severe: Hospitalization, IV magnesium sulfate to prevent seizures',
      'Blood pressure medication',
      'Corticosteroids for baby\'s lung development if early delivery needed',
      'Delivery is only cure - timing depends on severity and gestational age',
      'After delivery: Continue monitoring, medications may be needed',
      'Postpartum preeclampsia can occur up to 6 weeks after delivery',
    ],
    prevention: [
      'Low-dose aspirin (81mg) starting 12-16 weeks if high risk',
      'Calcium supplements (if dietary intake low)',
      'Prenatal vitamins',
      'Regular prenatal care',
      'Healthy diet',
      'Regular exercise',
      'Maintain healthy weight',
      'Monitor blood pressure at home if at risk',
    ],
    complications: [
      'Eclampsia (seizures)',
      'HELLP syndrome (liver and blood clotting disorder)',
      'Organ damage (liver, kidneys, brain)',
      'Stroke',
      'Placental abruption',
      'Preterm delivery',
      'Fetal growth restriction',
      'Stillbirth',
      'Maternal death (rare but possible)',
      'Increased cardiovascular disease risk later in life',
    ],
    whenToCallDoctor: [
      'Severe headache that won\'t go away',
      'Vision changes or seeing spots',
      'Severe pain in upper right abdomen',
      'Sudden severe swelling of face, hands, or feet',
      'Sudden weight gain (5+ pounds in a week)',
      'Difficulty breathing',
      'Nausea and vomiting in second half of pregnancy',
      'Decreased fetal movement',
      'Any concerning symptoms - call immediately, don\'t wait',
    ],
    relatedConditions: ['eclampsia', 'hellp-syndrome', 'chronic-hypertension', 'placental-abruption'],
  },
  {
    slug: 'placenta-previa',
    title: 'Placenta Previa',
    category: 'placental',
    severity: 'serious',
    howCommon: 'Affects 1 in 200 pregnancies at term',
    shortDescription: 'Placenta covers part or all of the cervix, blocking baby\'s exit and requiring C-section delivery.',
    detailedDescription: [
      'Placenta previa occurs when the placenta implants low in the uterus and covers part or all of the cervix. This blocks the baby\'s exit route and makes vaginal delivery dangerous due to bleeding risk.',
      'Many cases of low-lying placenta diagnosed early in pregnancy resolve as the uterus grows and the placenta "moves up." True placenta previa at term requires C-section delivery.',
      'The main danger is bleeding, which can occur without warning in the third trimester. Women with placenta previa need careful monitoring and may require early delivery if severe bleeding occurs.',
    ],
    symptoms: [
      'Bright red vaginal bleeding without pain (usually third trimester)',
      'Bleeding that stops and starts',
      'Bleeding may be light or heavy',
      'Some women have no symptoms (discovered on ultrasound)',
      'Cramping or contractions may accompany bleeding',
    ],
    causes: [
      'Placenta implants low in uterus',
      'Exact cause often unknown',
      'May relate to uterine scarring',
      'Abnormal uterine lining',
      'Multiple embryos attaching',
    ],
    riskFactors: [
      'Previous C-section or uterine surgery',
      'Previous placenta previa',
      'Multiple pregnancy (twins, triplets)',
      'Previous abortion or D&C',
      'Maternal age over 35',
      'Smoking',
      'Cocaine use',
      'Multiple previous pregnancies',
      'Infertility treatment/IVF',
      'Asian ethnicity',
    ],
    diagnosis: [
      'Ultrasound diagnosis (often 20-week anatomy scan)',
      'Transvaginal ultrasound for more accurate placental location',
      'Follow-up ultrasounds to see if placenta moves up',
      'Types: Complete (covers entire cervix), Partial (covers part), Marginal (edge reaches cervix)',
      'Low-lying placenta: within 2cm of cervix but not covering',
    ],
    treatment: [
      'Early pregnancy: Observation, usually resolves as uterus grows',
      'Pelvic rest: No sex, no tampons, no vaginal exams',
      'Activity restriction if bleeding occurs',
      'Hospitalization for heavy bleeding',
      'Blood transfusions if severe blood loss',
      'Corticosteroids for baby\'s lung development if early delivery likely',
      'Scheduled C-section at 36-37 weeks',
      'Emergency C-section if severe bleeding',
      'May need hysterectomy if severe bleeding can\'t be controlled',
    ],
    prevention: [
      'No proven prevention methods',
      'Avoid smoking',
      'Treat any uterine abnormalities before pregnancy',
      'Space pregnancies to allow uterine healing',
    ],
    complications: [
      'Severe bleeding requiring blood transfusion',
      'Preterm birth',
      'Placenta accreta (placenta grows into uterine wall)',
      'Emergency hysterectomy',
      'Maternal death (rare)',
      'Baby complications from preterm birth',
      'Risk of bleeding during C-section',
    ],
    whenToCallDoctor: [
      'Any vaginal bleeding in second half of pregnancy',
      'Heavy bleeding or bleeding that soaks a pad',
      'Bleeding with cramping or contractions',
      'Dizziness, lightheadedness, or fainting',
      'Fast heartbeat',
      'Severe pain',
      'Immediately call 911 if severe bleeding',
    ],
    relatedConditions: ['placental-abruption', 'placenta-accreta', 'vasa-previa'],
  },
  {
    slug: 'miscarriage',
    title: 'Miscarriage (Pregnancy Loss)',
    category: 'serious',
    severity: 'serious',
    howCommon: '10-20% of known pregnancies, often before 12 weeks',
    shortDescription: 'Loss of pregnancy before 20 weeks, most commonly in first trimester due to chromosomal abnormalities.',
    detailedDescription: [
      'Miscarriage is the loss of a pregnancy before 20 weeks. Most occur in the first trimester, often before a woman even knows she\'s pregnant. The most common cause is chromosomal abnormalities in the embryo - not something the mother did or didn\'t do.',
      'Signs include vaginal bleeding, cramping, and passing tissue. However, some miscarriages are "missed" with no symptoms, discovered during ultrasound when no heartbeat is detected.',
      'Miscarriage is emotionally devastating and requires time to grieve. Most women who miscarry go on to have successful pregnancies, though some experience recurrent miscarriage requiring investigation.',
    ],
    symptoms: [
      'Vaginal bleeding (light spotting to heavy bleeding)',
      'Cramping or abdominal pain',
      'Passing tissue or clots',
      'Disappearance of pregnancy symptoms',
      'Lower back pain',
      'Fluid or tissue passing from vagina',
      'Missed miscarriage: No symptoms, diagnosed on ultrasound',
    ],
    causes: [
      'Chromosomal abnormalities (50-70% of first trimester losses)',
      'Genetic problems in embryo',
      'Uterine abnormalities',
      'Cervical insufficiency',
      'Immune system problems',
      'Uncontrolled diabetes',
      'Severe infections',
      'Hormone problems',
      'Trauma to uterus',
      'Often no identifiable cause',
    ],
    riskFactors: [
      'Maternal age over 35 (20% risk) or over 40 (40% risk)',
      'Previous miscarriages',
      'Chronic conditions (diabetes, thyroid, autoimmune)',
      'Uterine or cervical problems',
      'Smoking, alcohol, or drug use',
      'Severe malnutrition',
      'Exposure to environmental toxins',
      'Certain medications',
      'Chromosomal abnormalities in parents',
    ],
    diagnosis: [
      'Ultrasound showing no heartbeat or empty gestational sac',
      'Declining hCG levels (pregnancy hormone)',
      'Pelvic exam showing dilated cervix',
      'Complete miscarriage: All tissue passed',
      'Incomplete: Some tissue remains',
      'Missed: Embryo died but body hasn\'t expelled it',
      'Threatened: Bleeding but pregnancy may continue',
    ],
    treatment: [
      'Expectant management: Wait for natural passage (1-2 weeks)',
      'Medical: Medication (misoprostol) to induce passage',
      'Surgical: D&C (dilation and curettage) to remove tissue',
      'Pain medication',
      'Monitoring hCG levels to ensure they return to zero',
      'RhoGAM if mother is Rh-negative',
      'Follow-up to ensure complete passage',
      'Emotional support and counseling',
      'Can try to conceive after one normal period',
    ],
    prevention: [
      'Most miscarriages cannot be prevented',
      'Take prenatal vitamins with folic acid',
      'Maintain healthy weight',
      'Avoid smoking, alcohol, drugs',
      'Limit caffeine to 200mg daily',
      'Manage chronic conditions',
      'Avoid environmental toxins',
      'Practice safe food handling',
      'After 2-3 miscarriages, testing for underlying causes',
    ],
    complications: [
      'Heavy bleeding requiring medical attention',
      'Infection if tissue remains',
      'Emotional trauma and grief',
      'Anxiety in future pregnancies',
      'Depression',
      'Rare: Asherman\'s syndrome (uterine scarring from D&C)',
      'Very rare: Septic miscarriage (infection)',
    ],
    whenToCallDoctor: [
      'Heavy bleeding (soaking more than 2 pads per hour)',
      'Severe abdominal pain',
      'Fever or chills',
      'Foul-smelling discharge',
      'Dizziness or fainting',
      'Any vaginal bleeding in pregnancy',
      'Seek support for grief and depression',
    ],
    relatedConditions: ['ectopic-pregnancy', 'molar-pregnancy', 'recurrent-miscarriage'],
  },
  {
    slug: 'ectopic-pregnancy',
    title: 'Ectopic Pregnancy',
    category: 'serious',
    severity: 'critical',
    howCommon: '1-2% of pregnancies',
    shortDescription: 'Pregnancy implants outside uterus, usually in fallopian tube - medical emergency requiring immediate treatment.',
    detailedDescription: [
      'Ectopic pregnancy occurs when a fertilized egg implants outside the uterus, most commonly in a fallopian tube. The embryo cannot survive, and if untreated, the growing pregnancy can rupture the fallopian tube, causing life-threatening internal bleeding.',
      'This is a medical emergency requiring immediate treatment. Early detection through monitoring hCG levels and ultrasound allows for medication treatment. Late detection may require emergency surgery.',
      'Ectopic pregnancy accounts for 6% of pregnancy-related deaths in the US. Quick diagnosis and treatment are critical for the mother\'s survival and preserving future fertility.',
    ],
    symptoms: [
      'Missed period with positive pregnancy test',
      'Vaginal bleeding (lighter or different than period)',
      'Sharp abdominal pain, often on one side',
      'Shoulder pain (if rupture - internal bleeding)',
      'Pelvic pain',
      'Dizziness, fainting, or weakness (if rupture)',
      'Nausea and vomiting',
      'Rectal pressure',
      'Many have no symptoms initially',
    ],
    causes: [
      'Fertilized egg can\'t travel through damaged or blocked fallopian tube',
      'Tube inflammation or scar tissue',
      'Previous pelvic or abdominal surgery',
      'Previous ectopic pregnancy',
      'Congenital fallopian tube defects',
      'Abnormal embryo development',
    ],
    riskFactors: [
      'Previous ectopic pregnancy (15% recurrence risk)',
      'Pelvic inflammatory disease (PID)',
      'Sexually transmitted infections (chlamydia, gonorrhea)',
      'Endometriosis',
      'Previous pelvic or abdominal surgery',
      'Previous tubal surgery or tubal ligation',
      'IVF or fertility treatments',
      'Smoking',
      'Maternal age over 35',
      'Use of IUD when pregnancy occurs',
    ],
    diagnosis: [
      'Blood hCG levels don\'t rise appropriately',
      'Ultrasound shows no pregnancy in uterus',
      'May see mass in fallopian tube',
      'Empty uterus with positive pregnancy test',
      'Pelvic exam showing tenderness',
      'May need serial hCG tests to track levels',
      'Laparoscopy if diagnosis uncertain',
    ],
    treatment: [
      'Medical: Methotrexate injection (stops cell growth)',
      'Requires hCG levels to be low enough and no rupture',
      'No drinking, no sex, avoid sun during treatment',
      'Serial hCG monitoring to ensure levels drop',
      'Surgical: Laparoscopy to remove ectopic pregnancy',
      'May remove part or all of fallopian tube',
      'Emergency surgery if ruptured',
      'Blood transfusion if severe bleeding',
      'Cannot save the pregnancy - not viable',
    ],
    prevention: [
      'Prevent STIs through safe sex practices',
      'Treat pelvic infections promptly',
      'Quit smoking before conceiving',
      'Early prenatal care in next pregnancy',
      'Close monitoring if high risk',
    ],
    complications: [
      'Ruptured fallopian tube - life-threatening',
      'Severe internal bleeding',
      'Shock from blood loss',
      'Loss of fallopian tube',
      'Reduced fertility',
      'Difficulty conceiving in future',
      'Maternal death if untreated',
      'Emotional trauma and grief',
    ],
    whenToCallDoctor: [
      'Sharp abdominal or pelvic pain',
      'Vaginal bleeding when pregnant',
      'Shoulder pain with positive pregnancy test',
      'Dizziness, fainting, or weakness',
      'Rectal pressure',
      'Call 911 if severe pain, heavy bleeding, or fainting',
      'Any unusual symptoms with positive pregnancy test',
    ],
    relatedConditions: ['miscarriage', 'pelvic-inflammatory-disease', 'tubal-damage'],
  },
  {
    slug: 'preterm-labor',
    title: 'Preterm Labor',
    category: 'serious',
    severity: 'serious',
    howCommon: '10% of pregnancies deliver before 37 weeks',
    shortDescription: 'Labor beginning before 37 weeks of pregnancy, risking premature birth.',
    detailedDescription: [
      'Preterm labor is labor that begins before 37 weeks of pregnancy. Babies born prematurely may face health challenges as their organs aren\'t fully developed. The earlier the birth, the higher the risks.',
      'Not all preterm labor results in preterm birth - it can sometimes be stopped with medications called tocolytics. Women at risk may receive medications to help baby\'s lungs mature in case early delivery is necessary.',
      'Early detection and treatment of preterm labor can delay delivery, giving baby more time to develop. Even a few extra days in the womb can make a significant difference in outcomes.',
    ],
    symptoms: [
      'Regular contractions (more than 4 in an hour)',
      'Menstrual-like cramping',
      'Pelvic pressure (baby pushing down)',
      'Low, dull backache',
      'Change in vaginal discharge (watery, mucus, or bloody)',
      'Abdominal cramping with or without diarrhea',
      'Water breaking (gush or trickle)',
      'Feeling that "something isn\'t right"',
    ],
    causes: [
      'Often unknown',
      'Infection (UTI, kidney infection, vaginal infection)',
      'Multiple pregnancy (twins, triplets)',
      'Uterine abnormalities',
      'Cervical insufficiency',
      'Placental problems',
      'Too much amniotic fluid',
      'Physical stress or trauma',
      'Chronic conditions',
    ],
    riskFactors: [
      'Previous preterm birth (highest risk factor)',
      'Short cervix (less than 25mm before 24 weeks)',
      'Multiple pregnancy',
      'Uterine or cervical abnormalities',
      'Certain infections',
      'Chronic conditions (diabetes, high blood pressure)',
      'Maternal age under 17 or over 35',
      'African American ethnicity',
      'Short interval between pregnancies (less than 6 months)',
      'Low or high BMI',
      'Smoking, alcohol, drugs',
      'High stress',
      'History of multiple abortions or miscarriages',
      'Bleeding in second or third trimester',
    ],
    diagnosis: [
      'Regular contractions documented',
      'Cervical exam showing dilation or effacement',
      'Cervical length ultrasound',
      'Fetal fibronectin test (if negative, very unlikely to deliver in next 2 weeks)',
      'Monitoring of contractions and baby\'s heart rate',
      'Checking for infections',
    ],
    treatment: [
      'Bed rest or reduced activity',
      'Hydration (dehydration can cause contractions)',
      'Tocolytics (medications to slow/stop contractions)',
      'Corticosteroids for baby\'s lung development',
      'Magnesium sulfate for baby\'s brain protection',
      'Progesterone supplementation if short cervix',
      'Cerclage (cervical stitch) if cervical insufficiency',
      'Antibiotics if infection present',
      'Hospitalization for monitoring',
      'May transfer to hospital with NICU',
    ],
    prevention: [
      'Weekly progesterone shots if previous preterm birth',
      'Cerclage if cervical insufficiency',
      'Treating infections promptly',
      'Prenatal care starting early',
      'Healthy diet and prenatal vitamins',
      'Avoid smoking, alcohol, drugs',
      'Manage chronic conditions',
      'Space pregnancies at least 18 months apart',
      'Manage stress',
      'Maintain healthy weight',
      'Monitor cervical length if high risk',
    ],
    complications: [
      'Premature birth before organs fully developed',
      'Respiratory distress syndrome',
      'Brain hemorrhage',
      'Temperature regulation problems',
      'Feeding difficulties',
      'Jaundice',
      'Infections',
      'Long-term developmental delays',
      'Cerebral palsy',
      'Vision and hearing problems',
      'Risk increases with earlier delivery',
    ],
    whenToCallDoctor: [
      'More than 4 contractions in an hour',
      'Regular contractions getting stronger/closer',
      'Pelvic pressure or cramping',
      'Lower back pain',
      'Change in vaginal discharge',
      'Water breaking',
      'Decreased fetal movement',
      'Any symptoms before 37 weeks',
      'Don\'t wait - call immediately',
    ],
    relatedConditions: ['cervical-insufficiency', 'pprom', 'placental-abruption', 'chorioamnionitis'],
  },
  {
    slug: 'hyperemesis-gravidarum',
    title: 'Hyperemesis Gravidarum (Severe Morning Sickness)',
    category: 'common',
    severity: 'moderate',
    howCommon: '0.5-2% of pregnancies',
    shortDescription: 'Severe, persistent nausea and vomiting causing dehydration and weight loss.',
    detailedDescription: [
      'Hyperemesis gravidarum (HG) is severe morning sickness causing persistent vomiting, dehydration, and weight loss of 5% or more of pre-pregnancy weight. It\'s much more serious than typical morning sickness.',
      'Women with HG often cannot keep down any food or fluids, leading to malnutrition and dehydration. Hospitalization for IV fluids and medications is common. The condition typically begins early in pregnancy and may last throughout.',
      'HG is physically and emotionally exhausting. While it doesn\'t usually harm the baby directly, maternal dehydration and malnutrition can cause complications. Treatment focuses on preventing dehydration and providing adequate nutrition.',
    ],
    symptoms: [
      'Severe, persistent nausea',
      'Vomiting more than 3-4 times per day',
      'Unable to keep food or fluids down',
      'Weight loss of 5% or more',
      'Dehydration (dark urine, dizziness, rapid heart rate)',
      'Feeling faint or weak',
      'Headaches',
      'Inability to perform daily activities',
      'Excessive salivation',
      'Low blood pressure',
    ],
    causes: [
      'Exact cause unknown',
      'Very high hCG hormone levels',
      'Multiple pregnancy (twins)',
      'Molar pregnancy',
      'Genetic predisposition',
      'First pregnancy or new partner',
      'History of motion sickness',
      'Migraine history',
    ],
    riskFactors: [
      'HG in previous pregnancy (up to 80% recurrence)',
      'Multiple pregnancy (twins, triplets)',
      'Molar pregnancy',
      'Female fetus',
      'Family history of HG',
      'History of eating disorders',
      'Thyroid problems',
      'First pregnancy',
      'Young maternal age',
    ],
    diagnosis: [
      'Persistent vomiting with weight loss',
      'Signs of dehydration',
      'Electrolyte imbalances on blood tests',
      'Ketones in urine',
      'Ruling out other causes (gallbladder, appendicitis, etc.)',
      'Ultrasound to rule out molar pregnancy or multiples',
      'Thyroid tests',
    ],
    treatment: [
      'IV fluids for hydration',
      'Anti-nausea medications (ondansetron, promethazine, metoclopramide)',
      'Vitamin B6 and doxylamine combination',
      'Thiamine supplementation to prevent deficiency',
      'Small, frequent meals when able to eat',
      'BRAT diet (bananas, rice, applesauce, toast)',
      'Ginger or peppermint',
      'Hospitalization if severe',
      'Feeding tube or TPN if unable to eat for extended period',
      'Home IV therapy',
      'Emotional support and counseling',
    ],
    prevention: [
      'Cannot be prevented',
      'Early treatment of nausea may prevent progression',
      'Stay hydrated',
      'Eat small, frequent meals',
      'Avoid triggers',
      'If previous HG, early intervention and medications',
    ],
    complications: [
      'Severe dehydration',
      'Electrolyte imbalances',
      'Malnutrition',
      'Weight loss',
      'Wernicke encephalopathy (thiamine deficiency)',
      'Muscle wasting',
      'Depression and anxiety',
      'PTSD',
      'Preterm birth if severe',
      'Low birth weight',
      'Esophageal tears from vomiting',
      'Tooth enamel erosion',
    ],
    whenToCallDoctor: [
      'Unable to keep fluids down for 24 hours',
      'Vomiting more than 3-4 times daily',
      'Losing weight',
      'Dark urine or no urination for 8+ hours',
      'Dizziness or fainting',
      'Rapid heartbeat',
      'Severe weakness',
      'Vomiting blood',
      'Thoughts of harming self or baby',
    ],
    relatedConditions: ['morning-sickness', 'dehydration', 'molar-pregnancy'],
  },
  {
    slug: 'placental-abruption',
    title: 'Placental Abruption',
    category: 'serious',
    severity: 'critical',
    howCommon: '1% of pregnancies',
    shortDescription: 'Placenta separates from uterine wall before delivery - emergency requiring immediate delivery.',
    detailedDescription: [
      'Placental abruption occurs when the placenta partially or completely separates from the uterine wall before delivery. This is a medical emergency because the baby depends on the placenta for oxygen and nutrients.',
      'Symptoms include vaginal bleeding, abdominal pain, and uterine contractions. However, bleeding may be hidden behind the placenta. The condition can progress rapidly and requires emergency delivery.',
      'Severe abruption can cause massive bleeding, shock, and fetal death. Even mild abruption requires close monitoring as it can worsen suddenly. Emergency C-section is often necessary.',
    ],
    symptoms: [
      'Vaginal bleeding (may be heavy or light)',
      'Abdominal pain',
      'Back pain',
      'Uterine tenderness',
      'Rapid uterine contractions',
      'Uterus that stays hard between contractions',
      'Decreased fetal movement',
      'Fetal distress on monitoring',
      'Hidden bleeding (no visible bleeding)',
    ],
    causes: [
      'Exact cause often unknown',
      'Trauma to abdomen (car accident, fall, abuse)',
      'Sudden decrease in uterus size (after water breaks)',
      'Blood vessel problems',
      'Hypertension',
      'Cocaine use',
    ],
    riskFactors: [
      'High blood pressure or preeclampsia',
      'Previous placental abruption (10% recurrence)',
      'Abdominal trauma',
      'Smoking',
      'Cocaine or methamphetamine use',
      'Heavy alcohol use',
      'Multiple pregnancy',
      'Age over 35',
      'Premature rupture of membranes',
      'Polyhydramnios (excess amniotic fluid)',
      'Short umbilical cord',
      'Uterine infection',
      'Previous C-section',
    ],
    diagnosis: [
      'Physical exam showing tender, hard uterus',
      'Vaginal bleeding',
      'Fetal heart rate abnormalities',
      'Ultrasound (may not show abruption)',
      'Blood tests checking for anemia and clotting',
      'Diagnosis often based on symptoms',
    ],
    treatment: [
      'Mild (small separation, stable): Close monitoring, possible bed rest',
      'Moderate to Severe: Immediate delivery',
      'Emergency C-section if baby or mother in distress',
      'Blood transfusions if severe bleeding',
      'IV fluids',
      'Oxygen',
      'Continuous fetal monitoring',
      'Corticosteroids if preterm and stable enough to wait',
      'Cannot reattach placenta - delivery only treatment',
    ],
    prevention: [
      'Cannot always be prevented',
      'Control blood pressure',
      'Avoid smoking, alcohol, drugs',
      'Wear seatbelt properly',
      'Avoid abdominal trauma',
      'If previous abruption, extra monitoring',
    ],
    complications: [
      'Fetal death',
      'Severe maternal bleeding',
      'Shock',
      'DIC (disseminated intravascular coagulation)',
      'Kidney failure',
      'Hysterectomy',
      'Maternal death',
      'Brain damage if baby deprived of oxygen',
      'Preterm delivery complications',
    ],
    whenToCallDoctor: [
      'Any vaginal bleeding in second or third trimester',
      'Abdominal pain',
      'Back pain',
      'Uterine tenderness or contractions',
      'Decreased fetal movement',
      'After any trauma to abdomen',
      'Call 911 if heavy bleeding or severe pain',
      'This is an emergency - go to hospital immediately',
    ],
    relatedConditions: ['placenta-previa', 'preeclampsia', 'pprom'],
  },
  {
    slug: 'intrauterine-growth-restriction',
    title: 'IUGR - Intrauterine Growth Restriction',
    category: 'serious',
    severity: 'serious',
    howCommon: '3-7% of pregnancies',
    shortDescription: 'Baby not growing at expected rate in utero, measuring smaller than gestational age.',
    detailedDescription: [
      'Intrauterine growth restriction (IUGR), also called fetal growth restriction (FGR), occurs when a baby doesn\'t grow at the expected rate inside the uterus. The baby measures below the 10th percentile for gestational age.',
      'IUGR can be symmetric (entire baby small) or asymmetric (head normal but body small). Causes include placental problems, maternal conditions, infections, and sometimes chromosomal abnormalities.',
      'Treatment depends on the cause and severity. Close monitoring with frequent ultrasounds tracks growth. Early delivery may be necessary if baby isn\'t thriving in utero, balancing prematurity risks against continued growth restriction.',
    ],
    symptoms: [
      'Mother: Measuring small for gestational age (fundal height)',
      'Mother: May feel less fetal movement',
      'Ultrasound: Baby measuring below 10th percentile',
      'Ultrasound: Low amniotic fluid',
      'Ultrasound: Abnormal Doppler blood flow',
      'Often no obvious symptoms to mother',
    ],
    causes: [
      'Placental insufficiency (placenta not working well)',
      'Maternal high blood pressure or preeclampsia',
      'Maternal chronic conditions (diabetes, kidney disease, heart disease)',
      'Smoking, alcohol, or drug use',
      'Malnutrition or eating disorders',
      'Multiple pregnancy',
      'Infections (CMV, toxoplasmosis, rubella)',
      'Chromosomal abnormalities',
      'Structural birth defects',
      'Problems with umbilical cord',
    ],
    riskFactors: [
      'Maternal high blood pressure',
      'Preeclampsia',
      'Diabetes',
      'Kidney disease',
      'Heart or lung disease',
      'Anemia',
      'Smoking',
      'Alcohol or drug use',
      'Poor nutrition',
      'Maternal age over 35 or under 17',
      'Previous baby with IUGR',
      'Multiple pregnancy',
      'Living at high altitude',
    ],
    diagnosis: [
      'Fundal height measuring small',
      'Ultrasound showing small baby (below 10th percentile)',
      'Estimated fetal weight calculation',
      'Amniotic fluid levels',
      'Doppler ultrasound of blood flow',
      'Serial ultrasounds to track growth over time',
      'Non-stress tests',
      'Biophysical profile',
    ],
    treatment: [
      'Identify and treat underlying cause if possible',
      'Frequent monitoring with ultrasounds',
      'Non-stress tests and biophysical profiles',
      'Bed rest or reduced activity',
      'Nutritional counseling',
      'Stop smoking, alcohol, drugs',
      'Low-dose aspirin if related to placental insufficiency',
      'Early delivery if baby not thriving (balancing prematurity vs. growth restriction)',
      'Delivery timing individualized based on severity',
      'Usually by 37-38 weeks, earlier if concerning',
    ],
    prevention: [
      'Maintain healthy lifestyle',
      'Prenatal care starting early',
      'Control chronic conditions',
      'Avoid smoking, alcohol, drugs',
      'Adequate nutrition',
      'Gain appropriate weight',
      'Low-dose aspirin if high risk',
      'Treat infections',
    ],
    complications: [
      'Low birth weight',
      'Difficulty maintaining body temperature',
      'Low blood sugar',
      'Low resistance to infection',
      'Breathing problems',
      'Low oxygen levels at birth',
      'Stillbirth',
      'Preterm birth',
      'Cesarean delivery',
      'Long-term developmental issues',
      'Increased risk of diabetes and heart disease in adulthood',
    ],
    whenToCallDoctor: [
      'Decreased fetal movement',
      'Measuring small at appointments',
      'Any concerning symptoms',
      'New or worsening symptoms of underlying condition',
    ],
    relatedConditions: ['preeclampsia', 'placental-insufficiency', 'oligohydramnios'],
  },
  {
    slug: 'cholestasis-of-pregnancy',
    title: 'Intrahepatic Cholestasis of Pregnancy (ICP)',
    category: 'serious',
    severity: 'moderate',
    howCommon: '1-2% of pregnancies in US, higher in certain populations',
    shortDescription: 'Liver condition causing severe itching, usually in third trimester, increasing stillbirth risk.',
    detailedDescription: [
      'Intrahepatic cholestasis of pregnancy (ICP) is a liver condition where bile acids build up in the bloodstream instead of flowing from the liver to the gut. This causes intense itching, especially on hands and feet, typically in the third trimester.',
      'The main concern with ICP is increased risk of stillbirth and preterm birth. The exact mechanism isn\'t fully understood, but elevated bile acids can affect the baby. Treatment includes medication to lower bile acids and close monitoring.',
      'Most cases resolve shortly after delivery. Women with ICP typically deliver between 36-38 weeks to reduce stillbirth risk while avoiding unnecessary prematurity.',
    ],
    symptoms: [
      'Intense itching, especially on palms and soles',
      'Itching worse at night',
      'No rash (unless from scratching)',
      'Dark urine',
      'Light-colored stools',
      'Jaundice (rare)',
      'Fatigue beyond normal pregnancy',
      'Loss of appetite',
      'Nausea',
    ],
    causes: [
      'Exact cause unknown',
      'Pregnancy hormones affecting liver function',
      'Genetic factors (runs in families)',
      'Bile acid buildup in blood',
      'Liver not processing bile acids properly',
    ],
    riskFactors: [
      'Personal or family history of ICP',
      'Previous liver damage',
      'Multiple pregnancy',
      'Hispanic, Scandinavian, or Chilean descent',
      'IVF pregnancy',
      'Hepatitis C infection',
    ],
    diagnosis: [
      'Blood test for bile acids (elevated)',
      'Liver function tests (may be elevated)',
      'Clinical symptoms (severe itching)',
      'Ruling out other causes of itching',
      'Bile acids usually over 10 micromol/L',
      'Severity based on bile acid levels',
    ],
    treatment: [
      'Ursodeoxycholic acid (UDCA) - reduces bile acids and improves outcomes',
      'Anti-itch medications (limited effectiveness)',
      'Vitamin K supplementation',
      'Frequent monitoring of bile acids and liver function',
      'Fetal monitoring (non-stress tests, biophysical profiles)',
      'Early delivery at 36-37 weeks',
      'May induce labor to prevent stillbirth',
      'Symptoms resolve shortly after delivery',
    ],
    prevention: [
      'Cannot be prevented',
      'Early recognition and treatment important',
      'If previous ICP, monitoring in subsequent pregnancies',
      'May recur in 60-90% of future pregnancies',
    ],
    complications: [
      'Stillbirth (main concern)',
      'Preterm birth',
      'Meconium in amniotic fluid',
      'Fetal distress during labor',
      'Maternal vitamin K deficiency',
      'Postpartum hemorrhage',
      'Gallstones later in life',
      'Increased liver disease risk',
      'Recurrence in future pregnancies',
    ],
    whenToCallDoctor: [
      'Severe itching, especially hands and feet',
      'Itching that worsens or doesn\'t improve',
      'Dark urine or light stools',
      'Yellowing of skin or eyes',
      'Decreased fetal movement',
      'Any new symptoms',
      'Don\'t dismiss itching as "just pregnancy" - get tested',
    ],
    relatedConditions: ['liver-disease', 'gallstones', 'preterm-labor'],
  },
  {
    slug: 'hellp-syndrome',
    title: 'HELLP Syndrome',
    category: 'serious',
    severity: 'critical',
    howCommon: '0.5-0.9% of pregnancies, 10-20% of severe preeclampsia cases',
    shortDescription: 'Life-threatening complication of preeclampsia affecting liver, blood, and clotting.',
    detailedDescription: [
      'HELLP syndrome is a severe, life-threatening pregnancy complication. The acronym stands for Hemolysis (breaking down of red blood cells), Elevated Liver enzymes, and Low Platelet count. It\'s considered a variant of preeclampsia.',
      'HELLP can develop rapidly and is often mistaken for flu or gallbladder problems initially. It\'s a medical emergency requiring immediate delivery, as it can cause organ failure, stroke, and maternal death.',
      'About 70% of cases occur before delivery, while 30% develop postpartum (within 48 hours). Early recognition and treatment are critical for maternal and fetal survival.',
    ],
    symptoms: [
      'Pain in upper right abdomen (under ribs)',
      'Severe headache',
      'Nausea and vomiting',
      'Malaise (feeling generally unwell)',
      'Vision changes',
      'High blood pressure',
      'Swelling',
      'Bleeding or bruising easily',
      'Flu-like symptoms',
      'May progress rapidly',
    ],
    causes: [
      'Related to preeclampsia',
      'Exact cause unknown',
      'Genetic factors',
      'Immune system problems',
      'Blood vessel damage',
      'Liver damage from preeclampsia',
    ],
    riskFactors: [
      'Preeclampsia or history of preeclampsia',
      'Previous HELLP syndrome',
      'Age over 25',
      'White race',
      'Multiple pregnancy',
      'History of pregnancy complications',
    ],
    diagnosis: [
      'Blood tests showing hemolysis',
      'Elevated liver enzymes (AST, ALT)',
      'Low platelet count (under 100,000)',
      'Blood pressure reading',
      'Protein in urine',
      'Blood smear showing damaged red blood cells',
      'Classified as mild, moderate, or severe based on platelet count',
    ],
    treatment: [
      'Immediate delivery is only cure',
      'Stabilize mother before delivery',
      'Blood pressure medications',
      'Magnesium sulfate to prevent seizures',
      'Corticosteroids to help liver function and baby\'s lungs',
      'Blood transfusions if needed',
      'Platelet transfusions if very low',
      'Close monitoring in ICU',
      'May need delivery by emergency C-section',
      'Continue monitoring 48-72 hours postpartum',
    ],
    prevention: [
      'Cannot be prevented',
      'Early and regular prenatal care',
      'Managing preeclampsia risk factors',
      'Low-dose aspirin if high risk for preeclampsia',
      'Recognizing symptoms early',
    ],
    complications: [
      'Maternal: Liver rupture or failure',
      'Kidney failure',
      'Placental abruption',
      'Pulmonary edema',
      'Stroke',
      'DIC (blood clotting disorder)',
      'Maternal death',
      'Fetal: Growth restriction',
      'Preterm birth',
      'Stillbirth',
      'Respiratory distress',
    ],
    whenToCallDoctor: [
      'Severe pain upper right abdomen',
      'Severe headache',
      'Vision changes',
      'Nausea and vomiting in late pregnancy',
      'Flu-like symptoms',
      'Severe swelling',
      'Decreased fetal movement',
      'Call immediately - this is an emergency',
      'Go to ER or call 911 if severe symptoms',
    ],
    relatedConditions: ['preeclampsia', 'eclampsia', 'liver-rupture', 'dic'],
  },
  {
    slug: 'gestational-hypertension',
    title: 'Gestational Hypertension (Pregnancy-Induced Hypertension)',
    category: 'common',
    severity: 'moderate',
    howCommon: '6-8% of pregnancies',
    shortDescription: 'High blood pressure developing after 20 weeks without protein in urine or organ damage.',
    detailedDescription: [
      'Gestational hypertension is high blood pressure that develops after 20 weeks of pregnancy without the protein in urine or organ damage seen in preeclampsia. Blood pressure is 140/90 or higher.',
      'Unlike chronic hypertension (high blood pressure before pregnancy), gestational hypertension starts during pregnancy and typically resolves after delivery. However, it can progress to preeclampsia.',
      'Management involves monitoring blood pressure, checking for progression to preeclampsia, and determining optimal delivery timing. Most women with gestational hypertension deliver at or near term.',
    ],
    symptoms: [
      'High blood pressure (140/90 or higher)',
      'Often no symptoms',
      'Headaches',
      'May progress to preeclampsia symptoms',
      'Usually detected at prenatal visit',
    ],
    causes: [
      'Exact cause unknown',
      'Problems with blood vessels',
      'Placental factors',
      'Genetic predisposition',
      'Similar factors to preeclampsia',
    ],
    riskFactors: [
      'First pregnancy',
      'Age under 20 or over 40',
      'Obesity',
      'Multiple pregnancy',
      'Family history of hypertension',
      'Diabetes',
      'Kidney disease',
      'African American ethnicity',
      'IVF pregnancy',
    ],
    diagnosis: [
      'Blood pressure 140/90 or higher on two occasions',
      'Develops after 20 weeks',
      'No protein in urine (differentiates from preeclampsia)',
      'No signs of organ damage',
      'Regular monitoring to check for progression',
    ],
    treatment: [
      'Mild: Monitoring blood pressure, weekly appointments',
      'Home blood pressure monitoring',
      'Checking for protein in urine at each visit',
      'Fetal monitoring (NSTs, ultrasounds)',
      'Medication if blood pressure very high',
      'Delivery at 37-39 weeks',
      'Close monitoring during labor',
      'Blood pressure may remain high after delivery for weeks',
    ],
    prevention: [
      'Low-dose aspirin if high risk',
      'Maintaining healthy weight',
      'Regular exercise',
      'Healthy diet',
      'Managing stress',
      'Early and regular prenatal care',
    ],
    complications: [
      'Progression to preeclampsia (25-50% of cases)',
      'Preterm birth if early delivery needed',
      'Placental abruption',
      'Intrauterine growth restriction',
      'Need for induction',
      'Increased C-section risk',
      'Chronic hypertension later in life',
    ],
    whenToCallDoctor: [
      'Severe headache',
      'Vision changes',
      'Upper abdominal pain',
      'Sudden severe swelling',
      'Decreased fetal movement',
      'Blood pressure readings consistently above 140/90 at home',
    ],
    relatedConditions: ['preeclampsia', 'chronic-hypertension', 'eclampsia'],
  },
  {
    slug: 'oligohydramnios',
    title: 'Oligohydramnios (Low Amniotic Fluid)',
    category: 'serious',
    severity: 'moderate',
    howCommon: '4% of pregnancies, 12% of post-term pregnancies',
    shortDescription: 'Too little amniotic fluid surrounding baby, which can affect development and delivery.',
    detailedDescription: [
      'Oligohydramnios is a condition where there\'s too little amniotic fluid surrounding the baby. Amniotic fluid cushions the baby, allows movement for development, regulates temperature, and protects the umbilical cord.',
      'Causes include placental problems, ruptured membranes, post-term pregnancy, maternal dehydration, and fetal urinary tract abnormalities. Severity and timing affect outcomes and treatment.',
      'Management depends on gestational age and severity. In the third trimester, if baby is doing well, increased hydration may help. If baby is near term or showing distress, delivery may be recommended.',
    ],
    symptoms: [
      'Mother: Measuring small for gestational age',
      'Mother: Leaking fluid (if membranes ruptured)',
      'Mother: Feeling every fetal movement intensely',
      'Usually discovered on ultrasound',
      'Decreased fetal movement sometimes',
    ],
    causes: [
      'Placental insufficiency (placenta not working well)',
      'Ruptured membranes (water breaking)',
      'Post-term pregnancy (over 42 weeks)',
      'Fetal urinary tract problems',
      'Intrauterine growth restriction',
      'Multiple pregnancy with twin-to-twin transfusion',
      'Maternal dehydration',
      'Certain medications (NSAIDs, ACE inhibitors)',
      'Birth defects',
      'Chromosomal abnormalities',
    ],
    riskFactors: [
      'Post-term pregnancy',
      'Preeclampsia',
      'Diabetes',
      'Lupus',
      'Chronic high blood pressure',
      'Multiple pregnancy',
      'Birth defects',
      'Previous pregnancy with oligohydramnios',
    ],
    diagnosis: [
      'Ultrasound measuring amniotic fluid index (AFI)',
      'AFI less than 5cm indicates oligohydramnios',
      'Or single deepest pocket less than 2cm',
      'Checking for rupture of membranes',
      'Fetal anatomy scan to rule out abnormalities',
      'Doppler ultrasound to check blood flow',
    ],
    treatment: [
      'Depends on gestational age and severity',
      'Maternal hydration (drinking more water)',
      'IV fluids if severe',
      'Bed rest',
      'Amnioinfusion (adding fluid during labor)',
      'Close fetal monitoring',
      'Delivery if near term or baby in distress',
      'Treat underlying cause if identified',
      'Serial ultrasounds to monitor fluid levels',
    ],
    prevention: [
      'Stay well hydrated',
      'Regular prenatal care',
      'Managing chronic conditions',
      'Avoid certain medications',
      'Report any fluid leaking',
    ],
    complications: [
      'Early pregnancy: Birth defects, miscarriage',
      'Second trimester: Preterm birth, growth restriction',
      'Third trimester: Difficult labor, cord compression',
      'Musculoskeletal abnormalities',
      'Lung underdevelopment',
      'Stillbirth',
      'Increased C-section risk',
      'Fetal distress during labor',
    ],
    whenToCallDoctor: [
      'Leaking fluid',
      'Decreased fetal movement',
      'Severe abdominal pain',
      'Contractions',
      'Any concerns about baby',
    ],
    relatedConditions: ['iugr', 'pprom', 'placental-insufficiency', 'post-term-pregnancy'],
  },
  {
    slug: 'polyhydramnios',
    title: 'Polyhydramnios (Excess Amniotic Fluid)',
    category: 'serious',
    severity: 'moderate',
    howCommon: '1-2% of pregnancies',
    shortDescription: 'Too much amniotic fluid, which can cause preterm labor and other complications.',
    detailedDescription: [
      'Polyhydramnios is excess amniotic fluid surrounding the baby. While fluid is essential for development, too much can cause complications like preterm labor, placental abruption, and cord prolapse.',
      'Mild polyhydramnios often has no cause and resolves on its own. Moderate to severe cases warrant investigation for fetal abnormalities, maternal diabetes, or twin-to-twin transfusion syndrome.',
      'Treatment depends on severity and cause. Mild cases are monitored. Severe cases may require amnioreduction (removing fluid) or early delivery.',
    ],
    symptoms: [
      'Rapidly growing belly',
      'Difficulty breathing',
      'Swelling in legs and feet',
      'Decreased urination',
      'Constipation',
      'Feeling of abdominal tightness',
      'Difficulty feeling fetal movements',
      'Uterus measures large for gestational age',
    ],
    causes: [
      'Often no identified cause (idiopathic)',
      'Maternal diabetes or gestational diabetes',
      'Multiple pregnancy, especially with twin-to-twin transfusion',
      'Fetal abnormalities (GI, neurological, chromosomal)',
      'Fetal anemia',
      'Infections (parvovirus, CMV, toxoplasmosis)',
      'Swallowing problems in fetus',
      'Fetal heart problems',
    ],
    riskFactors: [
      'Diabetes or gestational diabetes',
      'Multiple pregnancy',
      'Birth defects',
      'Rh incompatibility',
      'Previous pregnancy with polyhydramnios',
    ],
    diagnosis: [
      'Ultrasound measuring amniotic fluid index (AFI)',
      'AFI over 24-25cm indicates polyhydramnios',
      'Or single deepest pocket over 8cm',
      'Glucose tolerance test to check for diabetes',
      'Detailed anatomy scan looking for abnormalities',
      'Mild, moderate, or severe based on AFI level',
    ],
    treatment: [
      'Mild: Monitoring with serial ultrasounds',
      'Moderate to Severe: More frequent monitoring',
      'Treat underlying cause (control diabetes)',
      'Medications to decrease amniotic fluid production (indomethacin)',
      'Amnioreduction (removing excess fluid with needle)',
      'Early delivery if severe',
      'Careful monitoring during labor',
    ],
    prevention: [
      'Control diabetes before and during pregnancy',
      'Regular prenatal care',
      'Early detection and management',
    ],
    complications: [
      'Preterm labor and birth',
      'Premature rupture of membranes',
      'Placental abruption',
      'Umbilical cord prolapse',
      'Postpartum hemorrhage',
      'Malpresentation (breech, transverse)',
      'Fetal abnormalities (if present)',
      'Maternal breathing difficulties',
      'Need for C-section',
    ],
    whenToCallDoctor: [
      'Rapidly growing belly',
      'Difficulty breathing',
      'Severe swelling',
      'Decreased fetal movement',
      'Leaking fluid',
      'Contractions',
      'Severe abdominal discomfort',
    ],
    relatedConditions: ['gestational-diabetes', 'twin-twin-transfusion', 'fetal-abnormalities'],
  },
  {
    slug: 'rh-incompatibility',
    title: 'Rh Incompatibility & Sensitization',
    category: 'serious',
    severity: 'serious',
    howCommon: '15% of population is Rh negative; incompatibility much rarer with RhoGAM',
    shortDescription: 'When Rh-negative mother develops antibodies against Rh-positive baby\'s blood cells.',
    detailedDescription: [
      'Rh incompatibility occurs when an Rh-negative mother is pregnant with an Rh-positive baby. If the baby\'s blood crosses into the mother\'s bloodstream, her immune system may produce antibodies against the Rh factor.',
      'The first pregnancy is usually unaffected, but antibodies can attack Rh-positive babies in future pregnancies, causing anemia and other serious problems. This is called hemolytic disease of the newborn.',
      'RhoGAM (Rh immune globulin) injections prevent sensitization by destroying fetal blood cells before the mother\'s immune system responds. This has made Rh disease largely preventable.',
    ],
    symptoms: [
      'Mother: Usually no symptoms',
      'Baby: Anemia',
      'Baby: Jaundice',
      'Baby: Enlarged liver and spleen',
      'Baby: Heart failure (severe cases)',
      'Baby: Hydrops fetalis (most severe)',
      'Detected through blood tests',
    ],
    causes: [
      'Rh-negative mother pregnant with Rh-positive baby',
      'Baby\'s blood enters mother\'s circulation',
      'Mother\'s immune system creates antibodies',
      'Antibodies cross placenta in subsequent pregnancies',
      'Attack baby\'s red blood cells',
    ],
    riskFactors: [
      'Being Rh-negative',
      'Father is Rh-positive',
      'Events that mix maternal and fetal blood:',
      '- Miscarriage, abortion, ectopic pregnancy',
      '- Amniocentesis or CVS',
      '- Placental abruption',
      '- Trauma to abdomen',
      '- External cephalic version',
      '- Delivery',
      'Previous pregnancy without RhoGAM',
    ],
    diagnosis: [
      'Blood type and Rh testing at first prenatal visit',
      'Antibody screening',
      'Father\'s blood type testing',
      'If sensitized: Regular antibody titer levels',
      'Fetal monitoring with ultrasounds',
      'Middle cerebral artery Doppler for anemia',
      'Amniocentesis to check bilirubin levels',
    ],
    treatment: [
      'Prevention: RhoGAM at 28 weeks',
      'RhoGAM after delivery if baby is Rh-positive',
      'RhoGAM after miscarriage, amniocentesis, trauma, etc.',
      'If sensitized: Close monitoring of antibody levels',
      'Fetal ultrasounds to check for anemia',
      'Intrauterine blood transfusion if severe',
      'Early delivery if needed',
      'Newborn treatment: Phototherapy, exchange transfusion',
    ],
    prevention: [
      'RhoGAM injection at 28 weeks for Rh-negative mothers',
      'RhoGAM within 72 hours after delivery of Rh-positive baby',
      'RhoGAM after any event that may mix blood',
      'Prevents over 99% of sensitization',
      'Cannot reverse sensitization once it occurs',
    ],
    complications: [
      'Mild to severe anemia in baby',
      'Kernicterus (brain damage from severe jaundice)',
      'Heart failure',
      'Hydrops fetalis (severe fluid buildup)',
      'Stillbirth',
      'Need for blood transfusions',
      'Developmental problems',
      'Death (if untreated)',
    ],
    whenToCallDoctor: [
      'Decreased fetal movement',
      'Any trauma to abdomen',
      'Vaginal bleeding',
      'After any procedure',
      'If you\'re Rh-negative and haven\'t received RhoGAM',
      'Concerns about previous sensitization',
    ],
    relatedConditions: ['hemolytic-disease-newborn', 'fetal-anemia', 'jaundice'],
  },
  {
    slug: 'group-b-strep-infection',
    title: 'Group B Strep Infection',
    category: 'infection',
    severity: 'moderate',
    howCommon: '25% of pregnant women carry GBS bacteria',
    shortDescription: 'Common bacteria that can pass to baby during delivery, prevented with antibiotics in labor.',
    detailedDescription: [
      'Group B streptococcus (GBS) is a common bacteria that about 25% of healthy women carry in their vagina or rectum. While harmless to adults, GBS can cause serious infections in newborns if passed during delivery.',
      'All pregnant women are tested for GBS at 35-37 weeks. If positive, antibiotics are given during labor to prevent transmission. This reduces the baby\'s risk of infection by 80-90%.',
      'Without treatment, babies can develop pneumonia, sepsis, or meningitis in the first week of life. With antibiotics during labor, GBS infections in newborns are rare.',
    ],
    symptoms: [
      'Mother: Usually no symptoms (colonization, not infection)',
      'Mother: May have UTI symptoms if GBS causes infection',
      'Newborn (if infected): Difficulty breathing',
      'Newborn: Fever or low temperature',
      'Newborn: Difficulty feeding',
      'Newborn: Lethargy',
      'Newborn: Irritability',
      'Newborn: Seizures (severe)',
    ],
    causes: [
      'Common bacteria in vagina and rectum',
      'Can come and go naturally',
      'Not a sexually transmitted infection',
      'Baby exposed during vaginal delivery',
      'Bacteria can enter baby\'s lungs, blood, or spinal fluid',
    ],
    riskFactors: [
      'Mother positive for GBS',
      'No antibiotics during labor when GBS positive',
      'Preterm labor (before 37 weeks)',
      'Water broken for more than 18 hours',
      'Fever during labor',
      'Previous baby with GBS infection',
      'GBS in urine during pregnancy',
    ],
    diagnosis: [
      'GBS screening test at 35-37 weeks (swab)',
      'Culture takes 2-3 days',
      'If GBS found in urine anytime, treated as positive',
      'Previous baby with GBS infection - treated as positive',
      'If unknown and risk factors present - antibiotics given',
    ],
    treatment: [
      'Antibiotics during labor (IV penicillin or ampicillin)',
      'Given every 4 hours during labor',
      'Need at least 4 hours of antibiotics before delivery for effectiveness',
      'Alternative antibiotics if penicillin allergy',
      'Newborn monitored closely for signs of infection',
      'Baby may need antibiotics if high risk',
    ],
    prevention: [
      'Routine screening at 35-37 weeks',
      'Antibiotics during labor if positive',
      'Good hygiene',
      'Cannot be prevented with diet or lifestyle',
      'Not treated during pregnancy, only during labor',
    ],
    complications: [
      'Newborn: Pneumonia',
      'Sepsis (blood infection)',
      'Meningitis (brain infection)',
      'Death (rare with treatment)',
      'Long-term neurological problems',
      'Hearing or vision loss',
      'Developmental delays',
      'Mother: UTI, uterine infection, sepsis (rare)',
    ],
    whenToCallDoctor: [
      'If baby shows signs of infection after birth',
      'Fever during labor',
      'Water broken for many hours without labor',
      'Symptoms of UTI during pregnancy',
      'Preterm labor before screening done',
    ],
    relatedConditions: ['neonatal-sepsis', 'meningitis', 'uti-in-pregnancy'],
  },
  {
    slug: 'anemia-in-pregnancy',
    title: 'Anemia in Pregnancy',
    category: 'common',
    severity: 'mild',
    howCommon: '15-25% of pregnancies',
    shortDescription: 'Low red blood cell count or hemoglobin, causing fatigue and other symptoms.',
    detailedDescription: [
      'Anemia during pregnancy means you have fewer red blood cells than normal to carry oxygen to your tissues and baby. Iron deficiency is the most common cause, as your body needs extra iron during pregnancy.',
      'Your blood volume increases by 50% during pregnancy, but red blood cell production doesn\'t always keep up. Mild anemia is common and easily treated with iron supplements.',
      'Untreated severe anemia can lead to preterm birth, low birth weight, and maternal complications. Routine screening at first visit and again at 24-28 weeks catches most cases.',
    ],
    symptoms: [
      'Fatigue beyond normal pregnancy tiredness',
      'Weakness',
      'Pale skin, lips, nails',
      'Dizziness or lightheadedness',
      'Shortness of breath',
      'Rapid or irregular heartbeat',
      'Cold hands and feet',
      'Headaches',
      'Difficulty concentrating',
      'May have no obvious symptoms',
    ],
    causes: [
      'Iron deficiency (most common)',
      'Inadequate dietary iron',
      'Blood loss',
      'Increased iron needs in pregnancy',
      'Folate deficiency',
      'Vitamin B12 deficiency',
      'Multiple pregnancy',
      'Pregnancies close together',
      'Heavy periods before pregnancy',
    ],
    riskFactors: [
      'Two pregnancies close together',
      'Multiple pregnancy (twins, triplets)',
      'Severe morning sickness',
      'Heavy periods before pregnancy',
      'Not taking prenatal vitamins',
      'Vegetarian or vegan diet',
      'History of anemia',
      'Teens (still growing)',
      'Chronic diseases',
    ],
    diagnosis: [
      'Blood test measuring hemoglobin and hematocrit',
      'Complete blood count (CBC)',
      'First trimester: Hemoglobin under 11 g/dL',
      'Second/Third trimester: Under 10.5 g/dL',
      'Tests to determine type (iron, folate, B12)',
      'Ferritin level to check iron stores',
    ],
    treatment: [
      'Iron supplements (ferrous sulfate 325mg daily)',
      'Take with vitamin C to increase absorption',
      'Avoid taking with calcium or antacids',
      'Increase dietary iron (red meat, spinach, beans)',
      'Folate supplements',
      'Vitamin B12 if deficient',
      'IV iron if severe or can\'t tolerate oral',
      'Recheck levels in 4-6 weeks',
    ],
    prevention: [
      'Take prenatal vitamins daily (contain iron)',
      'Eat iron-rich foods',
      'Pair iron with vitamin C',
      'Cook in cast iron pans',
      'Avoid tea and coffee with meals (reduces absorption)',
      'Space pregnancies adequately',
    ],
    complications: [
      'Preterm birth',
      'Low birth weight baby',
      'Need for blood transfusion at delivery',
      'Postpartum depression',
      'Baby born with anemia',
      'Fatigue making labor difficult',
      'Increased infection risk',
      'Delayed postpartum recovery',
    ],
    whenToCallDoctor: [
      'Severe fatigue',
      'Dizziness or fainting',
      'Chest pain',
      'Rapid heartbeat',
      'Shortness of breath',
      'Side effects from iron supplements',
      'No improvement after taking supplements',
    ],
    relatedConditions: ['iron-deficiency', 'fatigue', 'preterm-birth'],
  },
  {
    slug: 'molar-pregnancy',
    title: 'Molar Pregnancy (Gestational Trophoblastic Disease)',
    category: 'serious',
    severity: 'serious',
    howCommon: '1 in 1000 pregnancies in US',
    shortDescription: 'Abnormal placental tissue growth instead of normal pregnancy - requires treatment.',
    detailedDescription: [
      'Molar pregnancy is a rare condition where abnormal tissue grows in the uterus instead of a normal embryo and placenta. It\'s caused by genetic errors during fertilization resulting in abnormal cell growth.',
      'There are two types: complete molar (no embryo forms) and partial molar (some embryonic tissue but not viable). The abnormal tissue produces very high levels of pregnancy hormone (hCG).',
      'Treatment involves removing the tissue by D&C. Close follow-up is essential because molar tissue can become cancerous. With proper treatment and monitoring, outcomes are excellent.',
    ],
    symptoms: [
      'Vaginal bleeding (dark brown to bright red)',
      'Severe nausea and vomiting',
      'Rapidly growing uterus (larger than expected)',
      'Pelvic pressure or pain',
      'Passage of grape-like tissue',
      'High blood pressure early in pregnancy',
      'Preeclampsia before 20 weeks',
      'Hyperthyroidism symptoms',
      'Ovarian cysts',
    ],
    causes: [
      'Genetic error during fertilization',
      'Complete molar: Egg with no genetic material fertilized',
      'Partial molar: Egg fertilized by two sperm',
      'Results in abnormal chromosome numbers',
      'Causes abnormal cell growth',
    ],
    riskFactors: [
      'Maternal age under 20 or over 35 (especially over 40)',
      'Previous molar pregnancy (1-2% recurrence)',
      'Previous miscarriage',
      'Diet low in protein, folate, and carotene',
      'Asian ethnicity',
      'Blood type A',
    ],
    diagnosis: [
      'Ultrasound showing "snowstorm" pattern',
      'No embryo or fetal heartbeat visible',
      'Extremely high hCG levels',
      'Uterus larger than expected for dates',
      'Tissue examination after D&C confirms',
    ],
    treatment: [
      'D&C (dilation and curettage) to remove tissue',
      'May need repeat D&C if tissue remains',
      'RhoGAM if mother Rh-negative',
      'hCG monitoring weekly until undetectable',
      'Then monthly monitoring for 6-12 months',
      'Chest X-ray to check for spread',
      'Chemotherapy if tissue becomes cancerous (rare)',
      'Avoid pregnancy during monitoring period',
      'Use reliable contraception',
    ],
    prevention: [
      'Cannot be prevented',
      'Adequate nutrition before pregnancy',
      'Folate supplementation',
      'After molar pregnancy, wait to conceive until cleared',
    ],
    complications: [
      'Heavy bleeding',
      'Infection',
      'Persistent gestational trophoblastic disease (15-20%)',
      'Choriocarcinoma (cancerous, rare)',
      'Need for chemotherapy',
      'Emotional trauma from loss',
      'Anxiety about future pregnancies',
      'With proper treatment, cure rate over 90%',
    ],
    whenToCallDoctor: [
      'Vaginal bleeding in early pregnancy',
      'Severe nausea and vomiting',
      'Passage of tissue or clots',
      'Pelvic pain',
      'Signs of hyperthyroidism (rapid heartbeat, tremors)',
      'During follow-up: Rising or plateauing hCG levels',
    ],
    relatedConditions: ['miscarriage', 'gestational-trophoblastic-neoplasia', 'hyperemesis'],
  },
  {
    slug: 'cervical-insufficiency',
    title: 'Cervical Insufficiency (Incompetent Cervix)',
    category: 'serious',
    severity: 'serious',
    howCommon: '1-2% of pregnancies',
    shortDescription: 'Cervix opens too early in pregnancy without contractions, risking preterm birth.',
    detailedDescription: [
      'Cervical insufficiency means the cervix begins to open (dilate) and thin (efface) too early in pregnancy, usually in the second trimester, without contractions or labor signs. This can lead to preterm birth or loss.',
      'The condition is often diagnosed after a pregnancy loss or discovered during routine ultrasound. Risk factors include previous cervical surgery, damage during previous birth, or congenital weakness.',
      'Treatment includes cervical cerclage (stitching the cervix closed), progesterone supplementation, and close monitoring. With treatment, many women carry to term.',
    ],
    symptoms: [
      'Often no symptoms until cervix opens significantly',
      'Mild discomfort or cramping in second trimester',
      'Backache',
      'Pelvic pressure',
      'Change in vaginal discharge',
      'Light vaginal bleeding',
      'May feel like period starting',
      'Usually discovered on ultrasound',
    ],
    causes: [
      'Exact cause often unknown',
      'Congenitally short or weak cervix',
      'Previous cervical trauma',
      'Damage from previous delivery',
      'Multiple D&C procedures',
      'Cervical surgery (LEEP, cone biopsy)',
      'DES exposure in utero',
      'Uterine abnormalities',
    ],
    riskFactors: [
      'Previous second trimester loss',
      'Previous preterm birth',
      'Cervical surgery (LEEP, cone biopsy, cryotherapy)',
      'Multiple pregnancy',
      'DES exposure',
      'Uterine abnormalities',
      'Cervical trauma',
    ],
    diagnosis: [
      'History of second trimester loss',
      'Transvaginal ultrasound measuring cervical length',
      'Cervix shortening (less than 25mm before 24 weeks)',
      'Cervix opening without contractions',
      'Physical exam showing dilated cervix',
      'Serial ultrasounds to monitor',
    ],
    treatment: [
      'Cervical cerclage (stitch placed 12-14 weeks)',
      'Removed at 36-37 weeks or if labor begins',
      'Progesterone suppositories or injections',
      'Activity restriction or bed rest',
      'Pelvic rest (no sex)',
      'Regular cervical length monitoring',
      'May need hospitalization if severe',
      'Cerclage not appropriate for all cases',
    ],
    prevention: [
      'Cannot always be prevented',
      'Avoid unnecessary cervical procedures',
      'If known risk, early cerclage placement',
      'Close monitoring in subsequent pregnancies',
      'Progesterone supplementation',
    ],
    complications: [
      'Preterm birth',
      'Pregnancy loss in second trimester',
      'Water breaking early (PPROM)',
      'Infection',
      'Cervical tears during delivery',
      'Cerclage complications (infection, rupture of membranes)',
      'Emotional trauma from losses',
    ],
    whenToCallDoctor: [
      'Pelvic pressure in second trimester',
      'Backache',
      'Change in discharge',
      'Mild cramping',
      'Anything that feels "off"',
      'After cerclage: Contractions, bleeding, fever, leaking fluid',
    ],
    relatedConditions: ['preterm-labor', 'pprom', 'pregnancy-loss'],
  },
  {
    slug: 'postpartum-preeclampsia',
    title: 'Postpartum Preeclampsia',
    category: 'serious',
    severity: 'serious',
    howCommon: '1 in 200 postpartum women, 30% of preeclampsia cases develop postpartum',
    shortDescription: 'Preeclampsia developing after delivery, usually within first 48 hours but up to 6 weeks postpartum.',
    detailedDescription: [
      'Postpartum preeclampsia is high blood pressure and organ damage that develops after delivery. It can occur in women who had preeclampsia during pregnancy or develop in women who had normal blood pressure throughout pregnancy.',
      'Most cases develop within 48 hours of delivery, but it can occur up to 6 weeks postpartum. Women are often home when symptoms begin, making awareness crucial.',
      'Treatment is similar to pregnancy preeclampsia - blood pressure medication and sometimes magnesium sulfate. Most cases resolve within days to weeks, but it\'s a serious condition requiring immediate treatment.',
    ],
    symptoms: [
      'High blood pressure (over 140/90)',
      'Severe headache',
      'Vision changes (blurry, seeing spots)',
      'Upper abdominal pain (right side under ribs)',
      'Nausea and vomiting',
      'Decreased urination',
      'Swelling of face and hands',
      'Shortness of breath',
      'Confusion',
    ],
    causes: [
      'Similar to pregnancy preeclampsia',
      'Blood vessel problems',
      'Immune system factors',
      'May be triggered by delivery',
      'Exact cause unclear',
    ],
    riskFactors: [
      'Preeclampsia during pregnancy',
      'Obesity',
      'Age over 40',
      'High blood pressure during pregnancy',
      'Multiple pregnancy',
      'First pregnancy',
      'African American ethnicity',
      'Previous postpartum preeclampsia',
    ],
    diagnosis: [
      'Blood pressure reading over 140/90',
      'Protein in urine',
      'Blood tests checking organ function',
      'Low platelet count',
      'Elevated liver enzymes',
      'May develop suddenly',
    ],
    treatment: [
      'Blood pressure medication',
      'Magnesium sulfate to prevent seizures',
      'Hospitalization if severe',
      'Close monitoring',
      'Treating symptoms',
      'Usually resolves within days to weeks',
      'Can continue breastfeeding with most medications',
    ],
    prevention: [
      'Know warning signs before leaving hospital',
      'Blood pressure monitoring at postpartum visits',
      'Home blood pressure monitoring if high risk',
      'Follow up within 3-7 days after discharge',
      'Low-dose aspirin during pregnancy if high risk',
    ],
    complications: [
      'Eclampsia (seizures)',
      'Stroke',
      'HELLP syndrome',
      'Pulmonary edema',
      'Organ damage',
      'Death (rare but possible)',
      'Need for ICU care',
    ],
    whenToCallDoctor: [
      'Severe headache',
      'Vision changes',
      'Severe pain under ribs',
      'Nausea and vomiting',
      'Severe swelling',
      'Shortness of breath',
      'Confusion',
      'Call immediately or go to ER - this is an emergency',
      'Don\'t dismiss symptoms as "just postpartum"',
    ],
    relatedConditions: ['preeclampsia', 'eclampsia', 'hellp-syndrome'],
  },
  {
    slug: 'umbilical-cord-prolapse',
    title: 'Umbilical Cord Prolapse',
    category: 'serious',
    severity: 'critical',
    howCommon: '0.1-0.6% of births',
    shortDescription: 'Umbilical cord drops through cervix before baby - emergency requiring immediate C-section.',
    detailedDescription: [
      'Umbilical cord prolapse is an obstetric emergency where the umbilical cord drops through the open cervix ahead of the baby, usually after water breaks. The cord can become compressed, cutting off oxygen to the baby.',
      'This requires immediate emergency cesarean delivery. Every minute counts, as cord compression reduces oxygen flow to the baby. Healthcare providers keep pressure off the cord until delivery.',
      'Risk is higher with breech presentation, multiple pregnancy, polyhydramnios, and preterm birth. Most cases occur in hospital during labor where emergency delivery is available.',
    ],
    symptoms: [
      'Visible or palpable cord in vagina',
      'Cord protruding from vagina',
      'Sudden changes in fetal heart rate after water breaks',
      'Feeling something unusual in vagina',
      'Usually occurs during labor in hospital',
    ],
    causes: [
      'Water breaking with cord in lower position',
      'Cord slips through cervix before baby',
      'More common when baby not engaged in pelvis',
      'Can occur with artificial rupture of membranes',
    ],
    riskFactors: [
      'Breech presentation',
      'Transverse lie (baby sideways)',
      'Multiple pregnancy',
      'Polyhydramnios (excess fluid)',
      'Preterm labor',
      'Long umbilical cord',
      'Low birth weight baby',
      'Multiple previous pregnancies',
      'Artificial rupture of membranes',
    ],
    diagnosis: [
      'Visual inspection - cord visible',
      'Pelvic exam - cord felt',
      'Sudden fetal heart rate decelerations',
      'Usually diagnosed during labor',
    ],
    treatment: [
      'Emergency cesarean delivery',
      'Provider keeps pressure off cord until delivery',
      'Mother positioned to relieve pressure (knee-chest)',
      'Filling bladder with saline to lift baby off cord',
      'Oxygen for mother',
      'IV fluids',
      'Immediate transfer to operating room',
      'Minutes count - must deliver quickly',
    ],
    prevention: [
      'Cannot always be prevented',
      'Controlled rupture of membranes',
      'Avoiding artificial rupture if baby not engaged',
      'C-section for high-risk positions (breech, transverse)',
      'Careful monitoring during labor',
    ],
    complications: [
      'Fetal oxygen deprivation',
      'Brain damage',
      'Stillbirth',
      'Emergency C-section complications',
      'Most babies do well if delivered quickly',
    ],
    whenToCallDoctor: [
      'Feeling cord in vagina',
      'Something protruding from vagina',
      'After water breaks - call immediately',
      'If occurs at home: Call 911, get on hands and knees, keep pressure off cord',
      'This is life-threatening emergency',
    ],
    relatedConditions: ['breech-presentation', 'polyhydramnios', 'preterm-labor'],
  },
  {
    slug: 'breech-position',
    title: 'Breech Position (Breech Presentation)',
    category: 'common',
    severity: 'moderate',
    howCommon: '3-4% of full-term pregnancies',
    shortDescription: 'Baby positioned feet or bottom first instead of head-down, often requiring C-section delivery.',
    detailedDescription: [
      'Breech position means the baby is positioned with their bottom, feet, or both toward the birth canal instead of head-down. There are three types: frank breech (bottom first, legs up), complete breech (bottom first, legs crossed), and footling breech (one or both feet first).',
      'Most babies turn head-down by 36 weeks. If a baby remains breech after 36 weeks, options include external cephalic version (manually turning baby), planned C-section, or in rare cases, vaginal breech delivery with an experienced provider.',
      'Breech position is more common before 36 weeks and usually corrects on its own. Contributing factors include multiple pregnancy, polyhydramnios, placenta previa, uterine abnormalities, or previous pregnancies.',
    ],
    symptoms: [
      'Baby\'s head felt high under ribs',
      'Hard round mass (head) in upper abdomen',
      'Kicks felt low in pelvis',
      'Hiccups felt in lower abdomen',
      'Usually discovered during prenatal exam or ultrasound',
      'Mother may notice baby\'s position feels different',
    ],
    causes: [
      'Often no specific cause',
      'Multiple pregnancy (twins, triplets)',
      'Too much or too little amniotic fluid',
      'Uterine abnormalities (fibroids, bicornuate uterus)',
      'Placenta previa or low-lying placenta',
      'Premature birth',
      'Multiple previous pregnancies (loose abdominal muscles)',
      'Short umbilical cord',
      'Fetal abnormalities (rare)',
    ],
    riskFactors: [
      'Preterm labor or delivery before 37 weeks',
      'Multiple pregnancy',
      'History of premature delivery',
      'Too much amniotic fluid (polyhydramnios)',
      'Too little amniotic fluid (oligohydramnios)',
      'Abnormally shaped uterus',
      'Fibroids or other uterine abnormalities',
      'Placenta previa or placenta covering cervix',
      'Multiple previous pregnancies',
    ],
    diagnosis: [
      'Physical exam - provider feels baby\'s position (Leopold maneuvers)',
      'Ultrasound confirms baby\'s position',
      'Type of breech identified (frank, complete, footling)',
      'Ultrasound checks for reasons (placenta position, cord, fluid levels)',
      'Usually diagnosed at 36-week appointment',
      'Checked again closer to delivery if trying version',
    ],
    treatment: [
      'Before 36 weeks: Watchful waiting (baby may turn on own)',
      'Certain positions and exercises (though limited evidence)',
      'External cephalic version (ECV) at 36-37 weeks',
      'ECV: Doctor manually turns baby from outside',
      'ECV success rate: 50-60% for first pregnancy, higher for subsequent',
      'If version unsuccessful or declined: Scheduled C-section at 39 weeks',
      'C-section is safest delivery method for most breech babies',
      'Vaginal breech delivery very rare, only with experienced provider',
    ],
    prevention: [
      'Cannot be prevented in most cases',
      'Some positions may encourage turning (limited evidence):',
      'Breech tilt exercise',
      'Pelvic tilts',
      'Swimming',
      'Chiropractic Webster technique (unproven)',
      'Moxibustion (traditional Chinese medicine, mixed evidence)',
      'Most important: Regular prenatal care to identify position',
    ],
    complications: [
      'Need for C-section delivery',
      'Risks associated with cesarean birth',
      'If vaginal delivery attempted: Cord prolapse risk',
      'Head entrapment during vaginal delivery',
      'Birth injuries',
      'External version risks: Placental abruption, preterm labor, cord compression',
      'Most babies delivered by planned C-section do very well',
    ],
    whenToCallDoctor: [
      'After external version attempt: Contractions, bleeding, decreased movement',
      'Leaking fluid or water breaking (higher prolapse risk)',
      'Decreased fetal movement',
      'Vaginal bleeding',
      'Severe abdominal pain',
      'If unsure about baby\'s position, ask at appointments',
    ],
    relatedConditions: ['umbilical-cord-prolapse', 'polyhydramnios', 'oligohydramnios', 'placenta-previa'],
  },
]

export function getComplicationData(slug: string): ComplicationData | undefined {
  return complicationsData.find((comp) => comp.slug === slug)
}

export function getComplicationsByCategory(category: string): ComplicationData[] {
  return complicationsData.filter((comp) => comp.category === category)
}

export function getComplicationsBySeverity(severity: string): ComplicationData[] {
  return complicationsData.filter((comp) => comp.severity === severity)
}
