// Pregnancy exercises and fitness data

export interface ExerciseData {
  slug: string
  title: string
  category: 'cardio' | 'strength' | 'flexibility' | 'pelvic-floor' | 'relaxation'
  trimesterSafety: { first: boolean; second: boolean; third: boolean }
  shortDescription: string
  detailedDescription: string[]
  benefits: string[]
  howToPerform: string[]
  safetyTips: string[]
  modifications: string[]
  whenToAvoid: string[]
  frequency: string
  relatedExercises: string[]
}

export const exercisesData: ExerciseData[] = [
  {
    slug: 'prenatal-yoga',
    title: 'Prenatal Yoga',
    category: 'flexibility',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Gentle yoga poses designed specifically for pregnancy to improve flexibility, reduce stress, and prepare your body for labor.',
    detailedDescription: [
      'Prenatal yoga is one of the best exercises during pregnancy, combining gentle stretching, mental centering, and focused breathing. It\'s specifically modified to be safe for pregnant women and addresses common pregnancy discomforts.',
      'Regular prenatal yoga practice helps maintain flexibility, strengthens muscles needed for labor, improves circulation, and reduces pregnancy-related aches and pains. Many women find it also helps with anxiety and prepares them mentally for childbirth.',
      'Studies show that prenatal yoga can reduce low back pain, improve sleep quality, decrease stress and anxiety, and even improve outcomes during labor and delivery.',
    ],
    benefits: [
      'Reduces stress, anxiety, and symptoms of depression',
      'Improves sleep quality and reduces insomnia',
      'Increases strength, flexibility, and endurance for labor',
      'Decreases lower back pain, nausea, and headaches',
      'Improves circulation and reduces swelling',
      'Helps with proper breathing techniques for labor',
      'Builds a supportive community with other expectant mothers',
      'Strengthens hip and pelvic muscles for childbirth',
    ],
    howToPerform: [
      'Find a certified prenatal yoga instructor or class in your area',
      'Inform instructor of your trimester and any pregnancy complications',
      'Use props like blocks, bolsters, and blankets for support',
      'Focus on deep, slow breathing throughout practice',
      'Hold poses for shorter durations, focusing on alignment over depth',
      'Practice 2-3 times per week for 30-60 minutes',
      'Include warm-up and cool-down periods',
      'Listen to your body and never push into pain',
    ],
    safetyTips: [
      'Always attend prenatal-specific yoga classes, not regular yoga',
      'Avoid hot yoga or Bikram yoga - overheating is dangerous',
      'Don\'t lie flat on your back after 20 weeks (reduces blood flow)',
      'Avoid deep twists, backbends, and inversions',
      'Skip poses that put pressure on your abdomen',
      'Stay hydrated and take breaks whenever needed',
      'Use a chair or wall for balance as your center of gravity shifts',
      'Get clearance from your healthcare provider before starting',
    ],
    modifications: [
      'Use blocks under hands in forward folds to avoid compressing belly',
      'Widen stance in standing poses to accommodate growing belly',
      'Practice side-lying or propped poses instead of lying flat',
      'Use wall support for balance poses',
      'Replace deep twists with gentle open twists from shoulders',
      'Elevate upper body with pillows in resting poses',
    ],
    whenToAvoid: [
      'Pregnancy complications like placenta previa or preeclampsia',
      'Risk of preterm labor or history of miscarriage',
      'Severe anemia or heart/lung disease',
      'Incompetent cervix or cerclage',
      'Multiple pregnancy (twins, triplets) in third trimester without approval',
      'Vaginal bleeding or ruptured membranes',
      'Any pain, dizziness, or unusual symptoms during practice',
    ],
    frequency: '2-3 times per week, 30-60 minutes per session',
    relatedExercises: ['pelvic-floor-exercises', 'prenatal-stretching', 'breathing-exercises'],
  },
  {
    slug: 'walking',
    title: 'Walking During Pregnancy',
    category: 'cardio',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Low-impact cardiovascular exercise that\'s safe throughout all trimesters and helps maintain fitness without stressing joints.',
    detailedDescription: [
      'Walking is often called the perfect pregnancy exercise because it\'s safe, free, requires no equipment, and can be done anywhere. It provides cardiovascular benefits without the jarring impact of running or high-intensity workouts.',
      'Whether you were active before pregnancy or are just starting to exercise, walking is an excellent choice. You can easily adjust the intensity by changing your pace or route, making it suitable for all fitness levels throughout your entire pregnancy.',
      'Regular walking during pregnancy helps control weight gain, reduces pregnancy discomforts, improves mood, lowers risk of gestational diabetes and preeclampsia, and helps prepare your body for labor.',
    ],
    benefits: [
      'Maintains cardiovascular fitness without joint stress',
      'Helps control pregnancy weight gain',
      'Reduces risk of gestational diabetes by 27%',
      'Improves mood and reduces pregnancy depression',
      'Decreases swelling in legs and feet',
      'Promotes better sleep and energy levels',
      'Strengthens muscles used during labor',
      'Can be done anywhere, anytime, for free',
    ],
    howToPerform: [
      'Start with 10-15 minutes if new to exercise, gradually increase to 30 minutes',
      'Walk at a moderate pace where you can still hold a conversation',
      'Maintain good posture - shoulders back, head up, core engaged',
      'Take shorter, more frequent walks if 30 minutes feels too long',
      'Walk on flat, even surfaces to reduce fall risk',
      'Wear supportive athletic shoes with good arch support',
      'Swing arms naturally for balance and increased calorie burn',
      'Aim for 150 minutes of moderate walking per week (5 days x 30 minutes)',
    ],
    safetyTips: [
      'Stay hydrated - bring water bottle on walks over 20 minutes',
      'Avoid walking in extreme heat or humidity',
      'Walk during cooler parts of day (morning or evening) in summer',
      'Use sunscreen and wear a hat for sun protection',
      'Listen to your body - slow down if you feel fatigued',
      'Stop if you experience dizziness, chest pain, or contractions',
      'Walk in well-lit, safe areas or with a partner',
      'As belly grows, slow your pace and take more frequent breaks',
    ],
    modifications: [
      'First trimester: Can maintain pre-pregnancy pace and distance',
      'Second trimester: May need to slow pace as belly grows',
      'Third trimester: Shorter, more frequent walks; focus on consistency over intensity',
      'If experiencing pelvic pain, reduce distance and consider supportive belly band',
      'Walk on treadmill with handrails if balance becomes an issue',
      'Break 30-minute walks into three 10-minute sessions if needed',
    ],
    whenToAvoid: [
      'Cervical insufficiency or cerclage',
      'Risk of preterm labor or history of preterm birth',
      'Placenta previa after 26 weeks',
      'Severe anemia',
      'Preeclampsia or pregnancy-induced hypertension',
      'Ruptured membranes or vaginal bleeding',
      'Multiple pregnancy with risk factors',
    ],
    frequency: '30 minutes daily, 5-7 days per week',
    relatedExercises: ['swimming', 'stationary-cycling', 'prenatal-aerobics'],
  },
  {
    slug: 'pelvic-floor-exercises',
    title: 'Kegel & Pelvic Floor Exercises',
    category: 'pelvic-floor',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Essential exercises to strengthen pelvic floor muscles, prevent incontinence, and support easier labor and recovery.',
    detailedDescription: [
      'Pelvic floor exercises, also known as Kegels, strengthen the hammock of muscles that support your bladder, uterus, and bowels. During pregnancy, these muscles are under increased stress from your growing baby and hormonal changes.',
      'Strong pelvic floor muscles help prevent urinary incontinence during and after pregnancy, support your growing uterus, may reduce the risk of tearing during delivery, and promote faster postpartum recovery. These exercises are invisible and can be done anywhere.',
      'The pelvic floor muscles also play a crucial role during labor. Learning to relax these muscles is just as important as strengthening them, as it helps during the pushing stage of delivery.',
    ],
    benefits: [
      'Prevents and reduces urinary incontinence during pregnancy',
      'Supports bladder, uterus, and bowel function',
      'May reduce risk of perineal tearing during delivery',
      'Improves postpartum recovery and healing',
      'Enhances sexual function during and after pregnancy',
      'Prevents pelvic organ prolapse',
      'Strengthens core stability',
      'Can be performed anywhere without anyone knowing',
    ],
    howToPerform: [
      'Find the right muscles: Stop urination midstream (but don\'t do Kegels while peeing regularly)',
      'Empty your bladder before starting exercises',
      'Tighten pelvic floor muscles and hold for 5 seconds',
      'Relax completely for 5 seconds',
      'Work up to holding for 10 seconds, relaxing for 10 seconds',
      'Perform 10 repetitions, 3 times daily',
      'Breathe normally - don\'t hold your breath',
      'Focus on isolating pelvic floor - don\'t squeeze abs, thighs, or buttocks',
    ],
    safetyTips: [
      'Don\'t perform Kegels while urinating (except to find the muscles)',
      'If you\'re unsure you\'re doing them correctly, ask your provider',
      'Consider seeing a pelvic floor physical therapist for personalized guidance',
      'Don\'t overdo it - more isn\'t always better',
      'Practice both strengthening (squeezing) and relaxation',
      'Some women have overly tight pelvic floors and need relaxation, not strengthening',
      'Stop if you experience pain',
      'Remember to practice relaxing these muscles for pushing during labor',
    ],
    modifications: [
      'First trimester: Build foundational strength with basic holds',
      'Second trimester: Increase hold duration and add quick pulses',
      'Third trimester: Focus equally on relaxation to prepare for delivery',
      'Try different positions: lying down, sitting, standing',
      'Use biofeedback apps or devices for guidance',
      'Combine with other exercises like squats or walking',
    ],
    whenToAvoid: [
      'During urination (except for identifying muscles initially)',
      'If you have pain or unusual symptoms',
      'Pelvic floor physical therapists should evaluate women with pelvic pain',
      'Some conditions require pelvic floor relaxation, not strengthening',
    ],
    frequency: '3 sets of 10 repetitions daily',
    relatedExercises: ['squats', 'prenatal-yoga', 'core-strengthening'],
  },
  {
    slug: 'swimming',
    title: 'Swimming & Water Aerobics',
    category: 'cardio',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Excellent low-impact full-body workout that takes pressure off joints and helps with swelling while keeping you cool.',
    detailedDescription: [
      'Swimming and water aerobics are among the best exercises during pregnancy. The buoyancy of water supports your weight, taking pressure off your joints and spine while allowing a full range of motion without the risk of falling or overheating.',
      'Many pregnant women report feeling lighter and more mobile in the water, making it especially appealing in the third trimester when movement becomes more challenging. The water provides natural resistance, giving you a strengthening workout without weights.',
      'Swimming is particularly beneficial for women experiencing significant swelling, back pain, or sciatic nerve pain. The water pressure helps reduce swelling in the legs and feet, while the horizontal position improves circulation.',
    ],
    benefits: [
      'Zero impact on joints while providing cardiovascular workout',
      'Buoyancy relieves pressure on back and pelvis',
      'Reduces swelling in legs, feet, and hands',
      'Full-body workout engaging all major muscle groups',
      'Keeps you cool and prevents overheating',
      'Improves circulation and reduces varicose veins',
      'Strengthens core without crunches',
      'Relieves sciatic nerve pain and back discomfort',
    ],
    howToPerform: [
      'Aim for 30 minutes, 3-4 times per week',
      'Use different strokes: freestyle, backstroke, breaststroke (modify as needed)',
      'Consider prenatal water aerobics classes for variety and community',
      'Start with 10-15 minutes if new to swimming, gradually increase',
      'Maintain a pace where you can comfortably talk',
      'Use kickboards or pool noodles for variety and support',
      'Include warm-up and cool-down laps',
      'Focus on smooth, controlled movements',
    ],
    safetyTips: [
      'Avoid diving or jumping into the pool',
      'Use pool ladders or steps carefully - surfaces can be slippery',
      'Don\'t swim in overly hot pools or hot tubs (keep under 85-87°F)',
      'Stay hydrated even though you\'re in water',
      'Avoid chlorine-heavy pools if it irritates skin or breathing',
      'Use handrails and take your time entering/exiting pool',
      'Don\'t swim in open water alone',
      'Stop if you experience dizziness, contractions, or pain',
    ],
    modifications: [
      'First trimester: Can continue pre-pregnancy swimming routine',
      'Second trimester: Modify strokes as belly grows (avoid tight rotation)',
      'Third trimester: Focus on gentle movements, backstroke, or water aerobics',
      'If breast stroke feels uncomfortable, switch to freestyle or backstroke',
      'Use a snorkel if turning head to breathe becomes difficult',
      'Walk in water instead of swimming if preferred',
    ],
    whenToAvoid: [
      'Ruptured membranes or leaking amniotic fluid',
      'Vaginal bleeding',
      'Preterm labor risk',
      'Cervical insufficiency',
      'Skin infections or open wounds',
      'Some pregnancy complications - check with provider',
    ],
    frequency: '30 minutes, 3-4 times per week',
    relatedExercises: ['walking', 'prenatal-aerobics', 'water-walking'],
  },
  {
    slug: 'squats',
    title: 'Pregnancy Squats',
    category: 'strength',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Strengthen legs, glutes, and pelvic floor while opening the pelvis to prepare for labor and delivery.',
    detailedDescription: [
      'Squats are one of the most beneficial exercises during pregnancy, strengthening the exact muscles you\'ll use during labor and delivery. They build strength in your legs, glutes, and core while opening the pelvis and encouraging baby into optimal position.',
      'As a functional movement, squats prepare your body for daily activities during pregnancy and postpartum - like lifting, sitting, and carrying your baby. The squatting position is also a natural birthing position used in many cultures.',
      'Regular squatting throughout pregnancy can shorten labor, reduce pain, and make pushing more effective. The position naturally opens the pelvis by up to 30%, giving baby more room to descend.',
    ],
    benefits: [
      'Strengthens legs, glutes, hamstrings, and core muscles',
      'Opens pelvis and encourages baby into optimal birth position',
      'May shorten labor and make pushing more effective',
      'Improves balance and stability as your center of gravity shifts',
      'Builds strength for carrying baby and daily activities postpartum',
      'Reduces back pain by strengthening supporting muscles',
      'Improves circulation in lower body',
      'Functional exercise that mimics daily movements',
    ],
    howToPerform: [
      'Stand with feet slightly wider than hip-width apart',
      'Turn toes slightly outward (about 15-30 degrees)',
      'Keep chest lifted and engage core muscles',
      'Lower down as if sitting back into a chair',
      'Keep knees tracking over toes (don\'t let them cave inward)',
      'Lower as far as comfortable - depth will vary by trimester',
      'Press through heels to return to standing',
      'Start with 10-15 repetitions, 2-3 sets',
    ],
    safetyTips: [
      'Don\'t let knees extend past toes or cave inward',
      'Keep weight in your heels, not on toes',
      'Maintain neutral spine - don\'t round or overarch back',
      'Use a chair or wall for support if needed for balance',
      'Breathe throughout movement - don\'t hold breath',
      'Stop if you feel pelvic pain or pressure',
      'Reduce depth if you feel unstable',
      'Get clearance from provider if you have pubic symphysis dysfunction',
    ],
    modifications: [
      'First trimester: Can do full-depth squats with normal stance',
      'Second trimester: May need wider stance as belly grows',
      'Third trimester: Reduce depth, use chair support, focus on pelvic opening',
      'Hold onto doorframe, countertop, or have partner hold your hands',
      'Try supported squats with exercise ball against wall behind back',
      'Practice sumo squats with very wide stance for third trimester',
      'Use a yoga block or cushion under heels if ankles are tight',
    ],
    whenToAvoid: [
      'Severe pubic symphysis dysfunction (SPD) or pelvic girdle pain',
      'Risk of preterm labor',
      'Incompetent cervix or cerclage',
      'Placenta previa',
      'High blood pressure or preeclampsia',
      'Doctor has recommended pelvic rest',
      'Sharp pain in pelvis, back, or abdomen during movement',
    ],
    frequency: '10-15 reps, 2-3 sets, 3-4 times per week',
    relatedExercises: ['pelvic-floor-exercises', 'lunges', 'wall-sits'],
  },
  {
    slug: 'prenatal-pilates',
    title: 'Prenatal Pilates',
    category: 'strength',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Low-impact core strengthening exercises adapted for pregnancy to improve posture, stability, and body awareness.',
    detailedDescription: [
      'Prenatal Pilates focuses on strengthening the deep core muscles, improving posture, and enhancing body awareness - all crucial during pregnancy when your body undergoes significant changes. Modified for pregnancy, it avoids exercises that put pressure on the abdomen or require lying flat on your back.',
      'The practice emphasizes controlled movements, proper breathing, and mind-body connection. These skills are valuable during pregnancy for managing discomfort and are especially helpful during labor when you need to stay focused and controlled.',
      'Prenatal Pilates is particularly effective for preventing and reducing back pain, one of the most common pregnancy complaints. By strengthening core and back muscles, you support your changing spine and pelvis.',
    ],
    benefits: [
      'Strengthens deep core and pelvic floor muscles safely',
      'Improves posture and reduces back pain',
      'Enhances balance and body awareness',
      'Builds endurance for labor and pushing',
      'Reduces pregnancy-related aches and pains',
      'Improves breathing technique for labor',
      'Promotes faster postpartum core recovery',
      'Low-impact with controlled, safe movements',
    ],
    howToPerform: [
      'Find a certified prenatal Pilates instructor or class',
      'Start with basics if new to Pilates',
      'Focus on deep, controlled breathing throughout exercises',
      'Engage transverse abdominals (deep core) not surface abs',
      'Move slowly and with control - quality over quantity',
      'Use props like resistance bands, small balls, and pillows',
      'Practice 2-3 times per week for 30-45 minutes',
      'Combine mat work with reformer if available',
    ],
    safetyTips: [
      'Only attend prenatal-specific classes, not regular Pilates',
      'Avoid exercises lying flat on back after 20 weeks',
      'Skip movements that require strong abdominal crunching',
      'Don\'t do exercises that create doming or coning of belly',
      'Modify as belly grows to avoid compression',
      'Use elevation (pillows/wedge) for any reclined positions',
      'Stop if you experience dizziness, pain, or discomfort',
      'Avoid overstretching due to relaxin hormone',
    ],
    modifications: [
      'Prop upper body at 45-degree angle instead of lying flat',
      'Practice side-lying exercises instead of prone (belly down)',
      'Use lighter resistance bands and reduce range of motion',
      'Widen stance in standing exercises for stability',
      'Focus on maintaining neutral spine, not deepening curves',
      'Replace planks with modified versions on knees or incline',
    ],
    whenToAvoid: [
      'High-risk pregnancy or complications',
      'Diastasis recti (abdominal separation) - needs special modifications',
      'Risk of preterm labor',
      'Placenta previa',
      'Severe pelvic or back pain without diagnosis',
      'Any pregnancy restrictions from your healthcare provider',
    ],
    frequency: '2-3 times per week, 30-45 minutes per session',
    relatedExercises: ['prenatal-yoga', 'core-strengthening', 'pelvic-floor-exercises'],
  },
  {
    slug: 'stationary-cycling',
    title: 'Stationary Bike Cycling',
    category: 'cardio',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Safe cardiovascular workout that supports your weight, eliminates fall risk, and allows easy intensity adjustment.',
    detailedDescription: [
      'Stationary cycling provides excellent cardiovascular exercise during pregnancy without the risks associated with outdoor biking. The bike supports your weight, there\'s no risk of falling, and you can easily control the intensity and duration.',
      'Unlike outdoor cycling, you don\'t have to worry about balance issues as your belly grows, uneven terrain, or traffic hazards. You can stop immediately if needed and the resistance is easily adjustable to match your energy levels on any given day.',
      'Stationary cycling is particularly good for women who were active cyclists before pregnancy, as it allows you to maintain cardiovascular fitness throughout pregnancy with minimal modifications.',
    ],
    benefits: [
      'Cardiovascular workout without joint impact',
      'Zero fall risk unlike outdoor cycling',
      'Strengthens legs and glutes',
      'Easily adjustable intensity and resistance',
      'Can be done while watching TV or reading',
      'Climate-controlled environment',
      'Reduces swelling in lower legs',
      'Maintains pre-pregnancy cycling fitness safely',
    ],
    howToPerform: [
      'Adjust seat height so knee has slight bend at bottom of pedal stroke',
      'Position handlebars higher as belly grows to stay more upright',
      'Start with 20-30 minutes at moderate intensity',
      'Maintain a pace where you can hold a conversation',
      'Keep resistance at comfortable level - you should be able to pedal smoothly',
      'Aim for 3-5 sessions per week',
      'Include 5-minute warm-up and cool-down at lower intensity',
      'Stay hydrated with water bottle nearby',
    ],
    safetyTips: [
      'Avoid recumbent bikes that lean you too far back after 20 weeks',
      'Don\'t overexert - keep intensity moderate',
      'Stop if you feel dizzy, short of breath, or have contractions',
      'Ensure bike is stable and properly maintained',
      'Position fan nearby to prevent overheating',
      'Don\'t grip handlebars too tightly - keep shoulders relaxed',
      'Get off bike slowly to avoid dizziness',
      'Listen to your body - some days you may need lower intensity',
    ],
    modifications: [
      'First trimester: Can maintain pre-pregnancy intensity',
      'Second trimester: Raise handlebars for more upright position',
      'Third trimester: Reduce intensity and duration as needed, stay very upright',
      'Widen seat or add cushion if seat becomes uncomfortable',
      'Reduce resistance rather than pushing through fatigue',
      'Break longer sessions into two shorter ones if needed',
      'Switch to recumbent bike with slight incline if upright becomes uncomfortable',
    ],
    whenToAvoid: [
      'Balance issues or dizziness even on stationary bike',
      'Severe shortness of breath or heart palpitations',
      'Risk of preterm labor',
      'Severe swelling in legs',
      'Preeclampsia or high blood pressure',
      'Cervical insufficiency',
      'Any pain during or after cycling',
    ],
    frequency: '20-30 minutes, 3-5 times per week',
    relatedExercises: ['walking', 'swimming', 'elliptical-trainer'],
  },
  {
    slug: 'prenatal-stretching',
    title: 'Prenatal Stretching Routine',
    category: 'flexibility',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Gentle stretches to relieve muscle tension, improve flexibility, and reduce common pregnancy aches and pains.',
    detailedDescription: [
      'Stretching during pregnancy is essential for relieving the muscle tension and tightness that comes from carrying extra weight and changes in your posture. As your belly grows, your center of gravity shifts forward, often causing tight hips, back, shoulders, and neck.',
      'The hormone relaxin, which loosens ligaments in preparation for childbirth, can make you more flexible but also more prone to overstretching and injury. Gentle, controlled stretching helps maintain healthy range of motion without overextending joints.',
      'A daily stretching routine can significantly reduce pregnancy discomforts like lower back pain, sciatic nerve pain, leg cramps, and tension headaches. It also promotes better sleep and relaxation.',
    ],
    benefits: [
      'Reduces lower back pain and sciatica',
      'Relieves tight hips and pelvic tension',
      'Decreases leg cramps and muscle soreness',
      'Improves circulation and reduces swelling',
      'Promotes better sleep and relaxation',
      'Maintains healthy range of motion',
      'Reduces stress and tension headaches',
      'Prepares body for labor positions',
    ],
    howToPerform: [
      'Warm up muscles with 5-10 minutes of walking before stretching',
      'Move slowly into each stretch without bouncing',
      'Hold each stretch for 20-30 seconds, breathing deeply',
      'Stretch to point of mild tension, never pain',
      'Focus on major areas: hips, back, legs, shoulders, neck',
      'Practice daily for 10-15 minutes',
      'Stretch both sides equally',
      'Use props like yoga straps, blocks, and pillows for support',
    ],
    safetyTips: [
      'Never stretch cold muscles - warm up first',
      'Don\'t bounce or force stretches due to relaxin',
      'Be extra cautious not to overstretch - joints are looser',
      'Avoid deep twisting stretches',
      'Don\'t stretch lying flat on back after 20 weeks',
      'Stop if you feel pain, not just mild tension',
      'Breathe deeply throughout - never hold breath',
      'Use walls, chairs, or partner for balance',
    ],
    modifications: [
      'First trimester: Can do most standard stretches',
      'Second trimester: Modify positions as belly grows, use props',
      'Third trimester: Use plenty of support, stay upright or side-lying',
      'Replace seated forward folds with wide-leg versions',
      'Do hamstring stretches lying on back with leg elevated (first/second trimester only)',
      'Use yoga strap to reach feet if you can\'t bend forward',
      'Practice hip stretches on hands and knees or standing',
    ],
    whenToAvoid: [
      'After bed rest or period of inactivity without warming up',
      'Pelvic girdle pain or pubic symphysis dysfunction without guidance',
      'Risk of preterm labor',
      'Vaginal bleeding',
      'Round ligament pain during stretch (adjust position)',
      'Any sharp pain during stretching',
    ],
    frequency: '10-15 minutes daily',
    relatedExercises: ['prenatal-yoga', 'prenatal-pilates', 'foam-rolling'],
  },
  {
    slug: 'side-lying-leg-lifts',
    title: 'Side-Lying Leg Lifts',
    category: 'strength',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Safe strengthening exercise for hips, glutes, and outer thighs that can be done throughout pregnancy.',
    detailedDescription: [
      'Side-lying leg lifts are a pregnancy-safe way to strengthen your hips, glutes, and outer thigh muscles without putting pressure on your belly. These muscles are important for supporting your changing posture and maintaining pelvic stability.',
      'As your pregnancy progresses and your belly grows, many traditional leg exercises become uncomfortable or unsafe. Side-lying exercises allow you to work lower body muscles while keeping your belly supported and comfortable.',
      'Strong hip abductors (outer hip muscles) help prevent and reduce pelvic girdle pain, support your changing gait, and maintain balance as your center of gravity shifts.',
    ],
    benefits: [
      'Strengthens hips, glutes, and outer thighs',
      'Supports pelvic stability and reduces pain',
      'Safe position throughout all trimesters',
      'Helps prevent waddling gait common in late pregnancy',
      'No pressure on belly or back',
      'Improves balance and stability',
      'Can be done in bed or on floor',
      'Reduces hip pain and tightness',
    ],
    howToPerform: [
      'Lie on your left side with head supported on pillow or arm',
      'Bend bottom leg slightly for stability',
      'Keep top leg straight with foot flexed',
      'Lift top leg up toward ceiling, keeping hips stacked',
      'Raise leg only to hip height or slightly above',
      'Lower with control back to starting position',
      'Complete 10-15 repetitions on each side',
      'Perform 2-3 sets',
    ],
    safetyTips: [
      'Keep movements slow and controlled',
      'Don\'t swing leg or use momentum',
      'Keep hips stacked - don\'t roll backward or forward',
      'Engage core to stabilize pelvis',
      'Stop if you feel pelvic or hip pain',
      'Use pregnancy pillow or regular pillows for support',
      'Don\'t lift leg too high - quality over range of motion',
      'Place pillow between knees if more comfortable',
    ],
    modifications: [
      'First trimester: Can add ankle weights for extra resistance',
      'Second trimester: Focus on maintaining good form as belly grows',
      'Third trimester: Use pillows under belly for support',
      'Add resistance band around thighs for extra challenge',
      'Try different angles: lift leg forward, straight up, or slightly back',
      'Do smaller movements with more repetitions if large lifts feel hard',
      'Flex and point foot to vary muscle engagement',
    ],
    whenToAvoid: [
      'Severe pelvic girdle pain or pubic symphysis dysfunction',
      'Hip bursitis or hip pain aggravated by exercise',
      'Risk of preterm labor with activity restriction',
      'Any pain during the movement',
    ],
    frequency: '10-15 reps per side, 2-3 sets, 3-4 times per week',
    relatedExercises: ['squats', 'prenatal-pilates', 'hip-circles'],
  },
  {
    slug: 'cat-cow-stretch',
    title: 'Cat-Cow Stretch',
    category: 'flexibility',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Gentle spinal movement that relieves back pain, improves posture, and helps position baby optimally.',
    detailedDescription: [
      'Cat-Cow is one of the most recommended stretches during pregnancy because it gently mobilizes the spine, relieves back pain, and can help position baby in an optimal position for birth. It\'s safe throughout all trimesters and can be done daily.',
      'This yoga-inspired movement alternates between arching and rounding your back, creating space in the spine and pelvis. The gentle rocking motion is soothing and helps relieve pressure on the lower back, especially beneficial in the third trimester.',
      'Many midwives and birthing instructors recommend Cat-Cow during pregnancy and even during early labor to help baby move into the best position and to relieve back labor pain.',
    ],
    benefits: [
      'Relieves lower back pain and tension',
      'Improves spinal flexibility and mobility',
      'Creates space for baby and improves positioning',
      'Strengthens core and back muscles',
      'Reduces pressure on sciatic nerve',
      'Calming and meditative movement',
      'Helps baby engage in pelvis for birth',
      'Safe and comfortable throughout pregnancy',
    ],
    howToPerform: [
      'Start on hands and knees (all fours position)',
      'Place hands shoulder-width apart, knees hip-width apart',
      'Start in neutral spine with flat back',
      'COW: Inhale, drop belly, lift chest and tailbone toward ceiling, gaze forward',
      'CAT: Exhale, round spine, tuck tailbone, drop head, draw belly toward spine',
      'Move slowly between positions, synchronized with breath',
      'Repeat 10-15 times',
      'Practice 2-3 times daily, especially when back is tight',
    ],
    safetyTips: [
      'Move gently - don\'t force the arch or round',
      'Keep neck neutral, don\'t drop head too far in cat pose',
      'Distribute weight evenly on hands and knees',
      'Use yoga mat or soft surface for knee comfort',
      'Place folded towel under knees if needed',
      'Keep elbows slightly bent, not locked',
      'Stop if you feel wrist pain (modify to forearms)',
      'Breathe deeply throughout movement',
    ],
    modifications: [
      'First trimester: Can do full range of motion',
      'Second trimester: May feel bigger stretch as belly grows',
      'Third trimester: Widen knees to accommodate belly',
      'Do on forearms instead of hands if wrists are uncomfortable',
      'Place pillows under knees for extra cushioning',
      'Practice while leaning on exercise ball or couch for support',
      'Take breaks as needed if wrists or knees get tired',
    ],
    whenToAvoid: [
      'Severe carpal tunnel syndrome or wrist pain',
      'Knee pain or injury',
      'Severe back pain that worsens with movement',
      'Balance issues on hands and knees',
      'Dizziness when lowering head below heart',
    ],
    frequency: '10-15 repetitions, 2-3 times daily',
    relatedExercises: ['prenatal-yoga', 'prenatal-stretching', 'child-pose'],
  },
  {
    slug: 'prenatal-strength-training',
    title: 'Prenatal Strength Training',
    category: 'strength',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Modified resistance training to maintain muscle strength, support posture, and prepare body for the physical demands of labor.',
    detailedDescription: [
      'Strength training during pregnancy helps you maintain muscle mass, support your changing posture, and build the endurance needed for labor and caring for a newborn. Modified properly, it\'s safe and highly beneficial throughout pregnancy.',
      'As your body produces relaxin and your joints become looser, maintaining muscle strength becomes even more important for joint stability and injury prevention. Strong muscles also help support the extra weight you\'re carrying and reduce common pregnancy discomforts.',
      'Prenatal strength training should focus on functional movements that prepare you for daily activities and motherhood - lifting, carrying, squatting, and maintaining posture. The goal is maintenance and functional strength, not muscle building or increasing weight.',
    ],
    benefits: [
      'Maintains muscle strength and tone',
      'Reduces pregnancy-related back and joint pain',
      'Prepares body for labor and pushing',
      'Builds endurance for carrying and lifting baby',
      'Improves posture and core stability',
      'Helps control pregnancy weight gain',
      'Reduces gestational diabetes risk',
      'Promotes faster postpartum recovery',
    ],
    howToPerform: [
      'Work with certified prenatal fitness trainer if possible',
      'Focus on moderate weight, higher repetitions (12-15 reps)',
      'Include exercises for all major muscle groups',
      'Prioritize lower body, back, and postural muscles',
      'Use dumbbells, resistance bands, or body weight',
      'Train 2-3 times per week with rest days between',
      'Keep workouts to 30-45 minutes',
      'Always include warm-up and cool-down',
    ],
    safetyTips: [
      'Get clearance from healthcare provider first',
      'Reduce weight from pre-pregnancy levels (use 60-70%)',
      'Avoid exercises lying flat on back after 20 weeks',
      'Never hold breath while lifting - exhale on exertion',
      'Avoid heavy overhead lifting in third trimester',
      'Don\'t exercise to fatigue - maintain conversation',
      'Skip exercises that cause abdominal doming or coning',
      'Avoid movements that strain pelvic floor (heavy deadlifts, etc.)',
    ],
    modifications: [
      'First trimester: Maintain pre-pregnancy routine with reduced weight',
      'Second trimester: Modify bench exercises to incline, adjust for belly',
      'Third trimester: Focus on lighter weights, seated/standing exercises',
      'Replace barbell exercises with dumbbells for better control',
      'Modify push-ups to incline or wall version',
      'Skip exercises on stomach (planks, etc.) or modify significantly',
      'Reduce range of motion as needed for comfort',
    ],
    whenToAvoid: [
      'High-risk pregnancy or complications',
      'Pregnancy-induced hypertension or preeclampsia',
      'Risk of preterm labor',
      'Cervical insufficiency',
      'Multiple pregnancy without clearance',
      'Severe anemia',
      'Certain heart or lung conditions',
    ],
    frequency: '30-45 minutes, 2-3 times per week',
    relatedExercises: ['squats', 'prenatal-pilates', 'resistance-band-exercises'],
  },
  {
    slug: 'prenatal-aerobics',
    title: 'Prenatal Aerobics Classes',
    category: 'cardio',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Structured group fitness classes designed for pregnancy with cardiovascular exercise, strengthening, and social support.',
    detailedDescription: [
      'Prenatal aerobics classes offer structured, pregnancy-safe cardiovascular workouts led by certified instructors who understand pregnancy modifications. These classes combine cardio, strength, and flexibility in a supportive group environment.',
      'Group fitness classes provide motivation, accountability, and social connection with other expectant mothers. The instructor ensures exercises are safe and appropriate for each trimester, taking the guesswork out of pregnancy fitness.',
      'Prenatal aerobics typically includes low-impact movements, modified dance moves, light weights, and stretching. The intensity is kept moderate and instructors provide multiple modification options for different fitness levels and stages of pregnancy.',
    ],
    benefits: [
      'Cardiovascular fitness in safe, structured environment',
      'Professional instruction ensures proper form and safety',
      'Social support and community with other pregnant women',
      'Combines cardio, strength, and flexibility',
      'Motivation and accountability from scheduled classes',
      'Learn pregnancy-safe exercises to do at home',
      'Reduces isolation and pregnancy anxiety',
      'Fun and energizing break from daily routine',
    ],
    howToPerform: [
      'Find certified prenatal aerobics classes in your area or online',
      'Attend 2-3 classes per week',
      'Arrive early to inform instructor of any pregnancy concerns',
      'Bring water bottle and towel',
      'Wear supportive athletic shoes and comfortable clothing',
      'Work at your own pace within the class structure',
      'Take breaks whenever needed',
      'Join at any point in pregnancy - instructors modify for all trimesters',
    ],
    safetyTips: [
      'Only attend prenatal-specific classes, not regular aerobics',
      'Ensure instructor is certified in prenatal fitness',
      'Inform instructor immediately if you feel unwell',
      'Don\'t compare yourself to others - work at your own level',
      'Stay hydrated throughout class',
      'Stop if you experience dizziness, contractions, or pain',
      'Avoid jumping or high-impact movements',
      'Listen to your body over the instructor if something feels wrong',
    ],
    modifications: [
      'First trimester: Can usually participate fully with standard modifications',
      'Second trimester: Reduce impact and adjust for growing belly',
      'Third trimester: Focus on low-impact, take frequent breaks',
      'Step side-to-side instead of jumping',
      'March in place instead of running',
      'Reduce arm movements overhead if uncomfortable',
      'Use lighter weights than others if needed',
    ],
    whenToAvoid: [
      'High-risk pregnancy without medical clearance',
      'Severe morning sickness or dizziness',
      'Preterm labor risk',
      'Placenta previa',
      'Severe shortness of breath',
      'Pregnancy-induced hypertension',
      'Multiple pregnancy in third trimester without approval',
    ],
    frequency: '45-60 minutes, 2-3 times per week',
    relatedExercises: ['walking', 'prenatal-yoga', 'swimming'],
  },
  {
    slug: 'wall-sits',
    title: 'Wall Sits',
    category: 'strength',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Isometric leg strengthening exercise that builds endurance for labor and delivery with wall support for safety.',
    detailedDescription: [
      'Wall sits are an excellent isometric exercise during pregnancy that strengthens your legs and glutes while the wall provides stability and support. This exercise is particularly beneficial for building the leg endurance needed during labor, especially if you plan to use squatting positions.',
      'Unlike dynamic squats, wall sits involve holding a static position, which builds muscular endurance without requiring balance or coordination. This makes them ideal for later pregnancy when balance becomes more challenging.',
      'Many women find that strong legs from exercises like wall sits make it easier to move through different labor positions and to maintain squatting or standing positions during contractions.',
    ],
    benefits: [
      'Builds leg and glute strength and endurance',
      'Prepares muscles for labor positions',
      'Wall provides stability and support',
      'No balance required',
      'Strengthens quadriceps, hamstrings, and glutes',
      'Can be done anywhere with a wall',
      'Improves stamina for long labor',
      'Reduces pressure on joints compared to squats',
    ],
    howToPerform: [
      'Stand with back against wall, feet about 2 feet from wall',
      'Slide down wall until thighs are parallel to ground (or comfortable angle)',
      'Keep knees aligned over ankles, not extending past toes',
      'Feet should be hip-width apart or slightly wider',
      'Hold position for 20-30 seconds to start',
      'Work up to 45-60 second holds',
      'Rest 30-60 seconds between holds',
      'Repeat 3-5 times',
    ],
    safetyTips: [
      'Don\'t hold breath - breathe normally throughout hold',
      'Keep back flat against wall',
      'Ensure knees stay aligned over ankles',
      'Slide up wall immediately if you feel dizzy or unwell',
      'Start with higher position (less bend) and progress as strength builds',
      'Stop if you feel pelvic pressure or pain',
      'Don\'t push to exhaustion - leave some in the tank',
      'Use this time to practice breathing techniques for labor',
    ],
    modifications: [
      'First trimester: Can hold lower position for longer',
      'Second trimester: May need to adjust position as belly grows',
      'Third trimester: Stay at higher angle, focus on endurance over depth',
      'Widen stance if more comfortable',
      'Hold for shorter periods (15-20 seconds) if needed',
      'Place exercise ball between back and wall for extra support',
      'Reduce angle of squat to 30-45 degrees instead of 90 degrees',
    ],
    whenToAvoid: [
      'Severe pubic symphysis dysfunction',
      'Pelvic girdle pain aggravated by exercise',
      'High blood pressure or dizziness',
      'Risk of preterm labor',
      'Placenta previa',
      'Doctor-recommended activity restriction',
      'Severe shortness of breath',
    ],
    frequency: '3-5 holds of 30-60 seconds, 3-4 times per week',
    relatedExercises: ['squats', 'lunges', 'prenatal-strength-training'],
  },
  {
    slug: 'breathing-exercises',
    title: 'Prenatal Breathing Exercises',
    category: 'relaxation',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Focused breathing techniques to reduce stress, improve oxygen flow, and prepare for labor breathing patterns.',
    detailedDescription: [
      'Breathing exercises are one of the most important yet often overlooked pregnancy practices. Focused breathing helps manage stress and anxiety, improves oxygen delivery to your baby, and prepares you for breathing techniques used during labor.',
      'As your pregnancy progresses and your growing uterus pushes against your diaphragm, you may feel short of breath. Practicing breathing exercises helps you learn to take fuller, more efficient breaths despite limited lung capacity.',
      'The breathing patterns you practice during pregnancy become automatic tools during labor. Many women find that the breathing techniques they practiced help them stay calm and manage contractions during childbirth.',
    ],
    benefits: [
      'Reduces stress, anxiety, and tension',
      'Improves oxygen flow to baby',
      'Lowers blood pressure and heart rate',
      'Prepares for labor breathing techniques',
      'Helps manage shortness of breath',
      'Promotes relaxation and better sleep',
      'Increases mind-body connection',
      'Useful tool for pain management during labor',
    ],
    howToPerform: [
      'Find quiet, comfortable place to sit or lie down (propped if after 20 weeks)',
      'Place one hand on chest, one on belly',
      'Breathe in slowly through nose for 4 counts',
      'Feel belly rise while chest stays relatively still',
      'Exhale slowly through mouth for 4-6 counts',
      'Focus attention on the breath',
      'Practice for 5-10 minutes daily',
      'Try different techniques: diaphragmatic, counted breathing, visualization',
    ],
    safetyTips: [
      'Don\'t hyperventilate or breathe too rapidly',
      'If you feel dizzy, return to normal breathing',
      'Practice when calm so it\'s available when stressed',
      'Don\'t practice immediately after eating',
      'Keep breathing natural, not forced',
      'Stop if you experience any discomfort',
      'Use in combination with comfortable positioning',
      'Remember to breathe normally between focused practice',
    ],
    modifications: [
      'First trimester: Can practice in any comfortable position',
      'Second trimester: Begin incorporating labor breathing patterns',
      'Third trimester: Practice in positions you might use during labor',
      'Seated breathing: Sit cross-legged or in chair with back support',
      'Side-lying breathing: Lie on left side with pillow support',
      'Standing/swaying breathing: Practice breathing while gently swaying hips',
      'Try 4-7-8 technique: Breathe in 4, hold 7, exhale 8',
    ],
    whenToAvoid: [
      'Severe shortness of breath or respiratory issues',
      'If breathing exercises trigger anxiety (some people find focus on breath stressful)',
      'During asthma attack or breathing difficulty',
      'If you become dizzy or lightheaded',
    ],
    frequency: '5-10 minutes daily, plus as needed for stress',
    relatedExercises: ['prenatal-yoga', 'meditation', 'progressive-muscle-relaxation'],
  },
  {
    slug: 'modified-planks',
    title: 'Modified Planks',
    category: 'strength',
    trimesterSafety: { first: true, second: true, third: false },
    shortDescription: 'Safe core strengthening on hands and knees or incline to maintain abdominal strength without stress on belly.',
    detailedDescription: [
      'Modified planks allow you to safely strengthen your core muscles during pregnancy without the risks associated with traditional planks. As your belly grows, standard planks can put excessive pressure on the abdominal wall and pelvic floor.',
      'Core strength is crucial during pregnancy for supporting your back, maintaining posture, and preparing for the physical demands of labor and recovery. Modified planks provide these benefits without putting your pregnancy at risk.',
      'It\'s important to stop planks if you notice any doming or coning of your belly (the abdomen bulging outward), as this indicates too much stress on the linea alba (the connective tissue between abdominal muscles) and increases risk of diastasis recti.',
    ],
    benefits: [
      'Strengthens deep core muscles safely',
      'Supports lower back and improves posture',
      'Builds shoulder and arm strength',
      'Prepares body for postpartum recovery',
      'Can be modified extensively for comfort',
      'Functional strength for daily activities',
      'Prevents excessive back arching',
      'Builds endurance without high impact',
    ],
    howToPerform: [
      'Start on hands and knees (all fours position)',
      'Place hands slightly wider than shoulders',
      'Engage core by gently drawing belly button toward spine',
      'Hold neutral spine position for 10-15 seconds',
      'Focus on breathing normally while engaging core',
      'Release and rest',
      'Repeat 5-8 times',
      'Progress to hands and toes (modified) only if no belly doming',
    ],
    safetyTips: [
      'STOP immediately if you see belly doming or coning',
      'Never hold breath - breathe normally throughout',
      'Keep neck neutral, not dropped or craned up',
      'Don\'t let belly sag or back arch excessively',
      'Start with very short holds (10 seconds) and progress slowly',
      'Discontinue if you experience any pelvic pressure or pain',
      'Many women should stop planks by end of second trimester',
      'When in doubt, skip planks and do other core exercises',
    ],
    modifications: [
      'First trimester: Can do on hands and toes with shorter holds',
      'Second trimester: Switch to hands and knees, or incline plank',
      'Third trimester: Generally not recommended - use other core exercises',
      'Incline plank: Hands on couch or wall, body at angle',
      'Keep knees down on mat for support',
      'Side plank against wall for oblique work',
      'Replace with standing core exercises like marching',
    ],
    whenToAvoid: [
      'Any visible doming or coning of belly',
      'Diastasis recti (abdominal separation)',
      'Pelvic floor dysfunction or weakness',
      'Carpal tunnel syndrome or wrist pain',
      'Third trimester for most women',
      'Any pelvic pressure or bearing down sensation',
      'Lower back pain aggravated by planks',
    ],
    frequency: '5-8 holds of 10-15 seconds, 3 times per week',
    relatedExercises: ['cat-cow-stretch', 'prenatal-pilates', 'side-lying-leg-lifts'],
  },
  {
    slug: 'butterfly-stretch',
    title: 'Butterfly Stretch (Baddha Konasana)',
    category: 'flexibility',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Hip opening stretch that increases flexibility in the pelvic area and inner thighs, beneficial for labor preparation.',
    detailedDescription: [
      'The butterfly stretch, also known as Bound Angle Pose in yoga, is excellent for opening the hips and stretching the inner thighs during pregnancy. This gentle seated stretch helps prepare the pelvis for childbirth and relieves tightness from the relaxin hormone.',
      'As one of the safest and most beneficial pregnancy stretches, butterfly pose can be practiced throughout all trimesters. It increases blood flow to the pelvis, stretches the muscles that will open during delivery, and provides a comfortable position for meditation and breathing practice.',
      'Many childbirth educators recommend practicing butterfly stretch daily in the third trimester to increase pelvic flexibility and encourage optimal baby positioning.',
    ],
    benefits: [
      'Opens hips and increases pelvic flexibility',
      'Stretches inner thighs and groin muscles',
      'Increases blood flow to pelvis',
      'Prepares pelvic area for childbirth',
      'Relieves tension in lower back and hips',
      'Reduces sciatica pain',
      'Comfortable position for breathing practice',
      'Safe throughout entire pregnancy',
    ],
    howToPerform: [
      'Sit on floor with back against wall for support',
      'Bring soles of feet together, letting knees fall open',
      'Hold feet or ankles with hands',
      'Sit up tall with straight spine',
      'Gently press knees toward floor (don\'t force)',
      'Hold for 30-60 seconds, breathing deeply',
      'Can gently flutter knees like butterfly wings',
      'Practice daily, especially in third trimester',
    ],
    safetyTips: [
      'Sit against wall or use pillows behind back for support',
      'Don\'t force knees toward ground - let gravity do the work',
      'Keep back straight, don\'t round forward',
      'Use blocks or pillows under knees for support if needed',
      'Stop if you feel sharp pain in hips or groin',
      'Be gentle due to increased flexibility from relaxin',
      'Don\'t bounce or pulse knees forcefully',
      'Keep breathing relaxed and deep',
    ],
    modifications: [
      'First trimester: Can practice traditional pose',
      'Second trimester: May need to move feet farther from body',
      'Third trimester: Place pillows under knees, sit on folded blanket',
      'Sit on yoga block or folded blanket to elevate hips',
      'Place blocks or pillows under each knee for support',
      'Practice with back against wall for stability',
      'If uncomfortable on floor, sit on edge of chair and practice with feet on ground',
    ],
    whenToAvoid: [
      'Severe pubic symphysis dysfunction (SPD)',
      'Hip or groin injury',
      'Pelvic girdle pain aggravated by the stretch',
      'After hip or pelvic surgery',
      'Knee problems affected by position',
    ],
    frequency: 'Hold for 30-60 seconds, 2-3 times daily',
    relatedExercises: ['prenatal-yoga', 'squats', 'prenatal-stretching'],
  },
  {
    slug: 'arm-circles',
    title: 'Arm Circles & Shoulder Exercises',
    category: 'strength',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Upper body exercises to strengthen shoulders and improve posture, counteracting forward pull from growing belly.',
    detailedDescription: [
      'Arm circles and shoulder exercises are important during pregnancy to counteract the forward pull of your growing breasts and belly. These simple exercises strengthen your upper back, shoulders, and arms while improving posture.',
      'As pregnancy progresses, many women develop rounded shoulders and upper back pain from carrying extra weight in front. Regular shoulder exercises help maintain proper alignment and reduce neck and shoulder tension.',
      'Strong shoulders and arms are also practical for pregnancy and postpartum - you\'ll be carrying a baby, car seat, diaper bags, and more. Building upper body strength now pays off in daily activities later.',
    ],
    benefits: [
      'Strengthens shoulders, upper back, and arms',
      'Improves posture and reduces slouching',
      'Relieves upper back and neck tension',
      'Prepares arms for carrying baby and baby gear',
      'Increases circulation in shoulders and arms',
      'Reduces numbness and tingling in arms',
      'Counteracts forward pull from pregnancy weight',
      'Can be done anywhere without equipment',
    ],
    howToPerform: [
      'Stand with feet hip-width apart, knees slightly bent',
      'Extend arms out to sides at shoulder height',
      'Make small circles forward for 30 seconds',
      'Reverse direction, make circles backward for 30 seconds',
      'Lower arms and rest',
      'Repeat 3-4 times',
      'Add shoulder rolls: roll shoulders back 10 times, forward 10 times',
      'Practice daily or whenever shoulders feel tight',
    ],
    safetyTips: [
      'Start with small circles and gradually increase size',
      'Keep movements controlled and smooth',
      'Don\'t shrug shoulders up toward ears',
      'Keep core gently engaged',
      'Stop if you feel dizzy with arms raised',
      'Lower arms and rest if they become tired',
      'Breathe normally throughout exercise',
      'Can be done seated if standing is uncomfortable',
    ],
    modifications: [
      'First trimester: Can hold light weights (2-3 lbs) for added resistance',
      'Second trimester: Focus on posture as belly grows',
      'Third trimester: May prefer seated version, no weights',
      'Do circles with one arm at a time if both is too tiring',
      'Practice while seated in chair for stability',
      'Reduce circle size if feeling tired',
      'Add resistance band for extra strengthening',
    ],
    whenToAvoid: [
      'Severe carpal tunnel syndrome',
      'Shoulder injury or pain',
      'Dizziness when raising arms',
      'High blood pressure (check with provider)',
      'Severe swelling in hands or arms',
    ],
    frequency: '3-4 sets of 30 seconds each direction, daily',
    relatedExercises: ['prenatal-strength-training', 'prenatal-yoga', 'posture-exercises'],
  },
  {
    slug: 'tailor-sitting',
    title: 'Tailor Sitting (Cross-Legged)',
    category: 'flexibility',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Simple seated position that opens hips, improves posture, and can be practiced throughout the day.',
    detailedDescription: [
      'Tailor sitting, or simply sitting cross-legged, is one of the easiest ways to improve hip flexibility and pelvic opening during pregnancy. This traditional position has been used by pregnant women across cultures for centuries as preparation for childbirth.',
      'While Western culture typically sits in chairs, sitting cross-legged on the floor naturally opens the hips and strengthens the back. Spending time in this position throughout the day can significantly increase hip flexibility without dedicated exercise time.',
      'This position is also practical - you can sit this way while watching TV, reading, working on a laptop (with a desk or table), or playing with older children. Many women find it more comfortable than sitting in a chair as pregnancy progresses.',
    ],
    benefits: [
      'Opens hips and increases pelvic flexibility',
      'Stretches inner thighs and groin',
      'Improves posture and spinal alignment',
      'Strengthens back muscles',
      'Prepares pelvis for childbirth',
      'Can be practiced anytime, anywhere',
      'Reduces swelling in legs and feet',
      'Promotes better circulation',
    ],
    howToPerform: [
      'Sit on floor with legs crossed in front of you',
      'Sit on folded blanket or cushion to elevate hips above knees',
      'Keep back straight and shoulders relaxed',
      'Rest hands on knees or in lap',
      'Switch which leg is in front every few minutes',
      'Sit against wall if needed for back support',
      'Practice throughout day during relaxing activities',
      'Work up to 20-30 minutes total per day',
    ],
    safetyTips: [
      'Elevate hips on cushion or folded blanket',
      'Don\'t force flexibility - let it develop gradually',
      'Switch leg positions regularly to stretch both sides evenly',
      'Use wall support if your back gets tired',
      'Place pillows under knees if they\'re elevated and uncomfortable',
      'Stop if you feel pain in knees, hips, or pelvic area',
      'Get up slowly using hands for support',
      'May need hand support to transition from this position',
    ],
    modifications: [
      'First trimester: Can sit in low cross-legged position',
      'Second trimester: May need higher cushion as belly grows',
      'Third trimester: Sit on higher cushion, against wall for support',
      'Use yoga blocks or pillows under knees for support',
      'Sit in chair with feet on floor if floor is too difficult',
      'Practice wide-leg seated position instead if more comfortable',
      'Lean back on hands or against furniture for support',
    ],
    whenToAvoid: [
      'Severe pelvic girdle pain or pubic symphysis dysfunction',
      'Knee injuries or arthritis',
      'Difficulty getting up from floor safely',
      'Balance issues',
      'Severe swelling requiring legs to be elevated',
    ],
    frequency: 'Throughout the day, accumulating 20-30 minutes total',
    relatedExercises: ['butterfly-stretch', 'prenatal-yoga', 'squats'],
  },
  {
    slug: 'pelvic-tilts',
    title: 'Pelvic Tilts',
    category: 'flexibility',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Gentle pelvic movement that relieves back pain, strengthens core, and improves pelvic mobility for labor.',
    detailedDescription: [
      'Pelvic tilts are one of the most recommended exercises during pregnancy for relieving and preventing lower back pain. This simple movement strengthens abdominal and back muscles while increasing pelvic mobility - both crucial for pregnancy comfort and labor.',
      'As your belly grows and your center of gravity shifts forward, your lower back often arches more (anterior pelvic tilt), leading to pain. Pelvic tilts help counteract this by strengthening the muscles that support proper pelvic alignment.',
      'The rocking motion of pelvic tilts is also soothing and can help position baby optimally in the pelvis. Many women find this movement helpful during labor for managing contractions.',
    ],
    benefits: [
      'Relieves and prevents lower back pain',
      'Strengthens abdominal and back muscles',
      'Increases pelvic flexibility and mobility',
      'Improves posture and spinal alignment',
      'Reduces sciatic nerve pain',
      'Helps position baby optimally',
      'Useful during labor for pain management',
      'Safe and comfortable throughout pregnancy',
    ],
    howToPerform: [
      'Lie on back (first/early second trimester) or stand against wall',
      'If lying down: Bend knees with feet flat, arms at sides',
      'Tilt pelvis backward, pressing lower back into floor/wall',
      'Feel your tailbone tuck under and lower abs engage',
      'Hold for 3-5 seconds',
      'Release to neutral',
      'Repeat 10-15 times',
      'Can also perform on hands and knees (similar to cat-cow)',
    ],
    safetyTips: [
      'Don\'t lie flat on back after 20 weeks (use standing or hands/knees version)',
      'Move slowly and with control',
      'Don\'t push into pain - gentle movement only',
      'Breathe normally throughout',
      'Keep shoulders relaxed',
      'Focus on using core and pelvic muscles, not pushing with legs',
      'Stop if you feel dizzy or uncomfortable',
      'This should feel relieving, not straining',
    ],
    modifications: [
      'First trimester: Can do lying on back',
      'Second trimester: Switch to standing against wall or hands and knees',
      'Third trimester: Standing or hands/knees versions only',
      'Standing version: Stand with back against wall, tilt pelvis to flatten back against wall',
      'Hands and knees: Similar movement to cat pose',
      'Can do while sitting on exercise ball',
      'Practice anywhere - standing in line, against counter, etc.',
    ],
    whenToAvoid: [
      'Lying on back after 20 weeks (use modified positions)',
      'Severe back pain that worsens with movement',
      'Dizziness in any position',
      'Pelvic girdle pain aggravated by movement',
    ],
    frequency: '10-15 repetitions, 2-3 times daily',
    relatedExercises: ['cat-cow-stretch', 'prenatal-yoga', 'core-strengthening'],
  },
  {
    slug: 'seated-marching',
    title: 'Seated Marching',
    category: 'cardio',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Gentle seated cardio exercise that improves circulation and maintains fitness when standing exercise is difficult.',
    detailedDescription: [
      'Seated marching is a gentle cardiovascular exercise perfect for days when you need to keep moving but don\'t have energy for standing exercise, or when you need to reduce impact further. It improves circulation, maintains fitness, and can be done anywhere with a chair.',
      'This exercise is particularly useful in the third trimester when standing for extended periods becomes uncomfortable, or on days when you\'re experiencing pelvic pain, swelling, or fatigue but still want to stay active.',
      'Seated marching can be done while watching TV, working at a desk, or during breaks. It\'s an excellent alternative exercise that keeps blood flowing and prevents the risks of prolonged sitting.',
    ],
    benefits: [
      'Improves circulation without standing',
      'Reduces swelling in legs and feet',
      'Gentle cardiovascular activity',
      'Strengthens hip flexors and core',
      'Can be done anywhere with a chair',
      'Reduces risk of blood clots from prolonged sitting',
      'Good alternative when standing is uncomfortable',
      'Maintains activity on lower-energy days',
    ],
    howToPerform: [
      'Sit toward front of sturdy chair with feet flat on floor',
      'Sit up straight with shoulders back',
      'Lift right knee up toward chest',
      'Lower right foot back to floor',
      'Lift left knee up toward chest',
      'Alternate legs in marching motion',
      'Continue for 5-10 minutes',
      'Swing arms naturally as if walking',
    ],
    safetyTips: [
      'Use sturdy chair that won\'t slide or tip',
      'Maintain good posture throughout',
      'Don\'t hold breath - breathe naturally',
      'Start slowly and increase pace gradually',
      'Lift knees only as high as comfortable',
      'Stop if you feel pelvic pressure or pain',
      'Stay hydrated',
      'Can take breaks as needed',
    ],
    modifications: [
      'First trimester: Can lift knees higher for more intensity',
      'Second trimester: Adjust knee height as comfortable',
      'Third trimester: Smaller movements, focus on consistency',
      'Add arm movements overhead for upper body work',
      'Hold light weights for added resistance',
      'Increase or decrease pace based on energy level',
      'Do intervals: 1 minute fast, 1 minute slow',
      'Just lift heels off ground if full knee lift is too much',
    ],
    whenToAvoid: [
      'Severe pelvic pressure or pain with movement',
      'Risk of preterm labor with activity restriction',
      'Dizziness or lightheadedness while sitting',
      'Severe swelling requiring legs to be elevated',
    ],
    frequency: '5-10 minutes, 2-3 times per day',
    relatedExercises: ['walking', 'stationary-cycling', 'prenatal-aerobics'],
  },
  {
    slug: 'child-pose',
    title: 'Child\'s Pose (Balasana)',
    category: 'relaxation',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Relaxing yoga pose that gently stretches the back, hips, and thighs while promoting rest and stress relief.',
    detailedDescription: [
      'Child\'s Pose is a restful yoga position that provides gentle stretching and promotes relaxation during pregnancy. It\'s one of the safest and most comfortable poses for pregnant women, offering a moment of calm while gently stretching the entire back body.',
      'This pose is particularly soothing for the lower back and hips, making it ideal for pregnancy when these areas carry extra tension. Many prenatal yoga classes use Child\'s Pose as a resting position between more active poses.',
      'The forward folding and grounding nature of this pose has a naturally calming effect on the nervous system, making it excellent for stress relief, anxiety management, and preparing for sleep.',
    ],
    benefits: [
      'Gently stretches lower back, hips, and thighs',
      'Relieves back and neck tension',
      'Calms nervous system and reduces stress',
      'Promotes deep breathing',
      'Helps with digestion and reduces bloating',
      'Comfortable resting position',
      'Reduces anxiety and promotes relaxation',
      'Safe throughout pregnancy with modifications',
    ],
    howToPerform: [
      'Start on hands and knees',
      'Separate knees wide (wider than hips)',
      'Bring big toes together behind you',
      'Sit hips back toward heels',
      'Extend arms forward on floor or alongside body',
      'Rest forehead on floor or on stacked hands/pillow',
      'Breathe deeply, letting belly relax between thighs',
      'Hold for 30 seconds to several minutes',
    ],
    safetyTips: [
      'Widen knees enough to accommodate growing belly',
      'Use pillows under forehead if you can\'t reach floor comfortably',
      'Place pillow or folded blanket under hips if heels don\'t reach',
      'Don\'t force the stretch - should feel gentle and relaxing',
      'Keep breathing deeply and naturally',
      'Exit slowly by walking hands back and sitting up gradually',
      'Stop if you feel dizzy or uncomfortable',
      'Avoid if you have knee problems',
    ],
    modifications: [
      'First trimester: Can practice traditional version',
      'Second trimester: Widen knees to make room for belly',
      'Third trimester: Very wide knees, pillows under chest for support',
      'Stack pillows or bolster under chest for elevation',
      'Turn head to side instead of facing down',
      'Place folded blanket between hips and heels for support',
      'Practice with upper body resting on exercise ball',
      'Use couch or bed edge for upper body support',
    ],
    whenToAvoid: [
      'Knee pain or injury',
      'Dizziness when head is lower than heart',
      'Severe acid reflux (elevate upper body more)',
      'Difficulty getting up from floor',
      'Very high or very low blood pressure (check with provider)',
    ],
    frequency: 'Hold 30 seconds to 3 minutes, 2-3 times daily or as needed',
    relatedExercises: ['cat-cow-stretch', 'prenatal-yoga', 'prenatal-stretching'],
  },
  {
    slug: 'side-leg-lifts-standing',
    title: 'Standing Side Leg Lifts',
    category: 'strength',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Standing hip strengthening exercise using a chair for support that improves balance and strengthens glutes.',
    detailedDescription: [
      'Standing side leg lifts strengthen your hip abductors (outer hip and glute muscles) while improving balance and stability. Using a chair for support makes this a safe, practical exercise throughout pregnancy.',
      'Strong hip muscles are essential during pregnancy for supporting your changing posture, preventing waddling gait, and reducing hip and pelvic pain. The standing version also challenges your balance in a controlled way.',
      'This functional exercise mimics movements you do every day - stepping sideways, maintaining balance, and using hip strength for stability. It prepares your body for the physical demands of carrying a growing belly and eventually a baby.',
    ],
    benefits: [
      'Strengthens hip abductors and glutes',
      'Improves balance and stability',
      'Reduces hip and pelvic pain',
      'Prevents waddling gait',
      'Functional exercise for daily activities',
      'Can be done anywhere with a chair',
      'Maintains proper hip alignment',
      'Strengthens supporting muscles for pregnancy posture',
    ],
    howToPerform: [
      'Stand next to sturdy chair, holding back or seat for support',
      'Stand on left leg, right hand on chair',
      'Keep standing leg slightly bent',
      'Lift right leg out to side, keeping toes pointing forward',
      'Lift only to hip height or just below',
      'Lower leg with control',
      'Complete 12-15 repetitions',
      'Switch sides and repeat',
    ],
    safetyTips: [
      'Use very sturdy chair that won\'t slide or tip',
      'Keep both hips level - don\'t lean away',
      'Don\'t swing leg or use momentum',
      'Keep toes pointing forward, not turning out',
      'Engage core to stabilize pelvis',
      'Standing leg should be slightly bent, not locked',
      'Stop if you feel pelvic or hip pain',
      'Move slowly and with control',
    ],
    modifications: [
      'First trimester: Can add ankle weights',
      'Second trimester: Focus on balance as center of gravity shifts',
      'Third trimester: Hold chair with both hands if needed for balance',
      'Reduce height of leg lift',
      'Do more repetitions with smaller movements',
      'Stand with back against wall for extra stability',
      'Add resistance band around thighs for extra challenge (first/second trimester)',
    ],
    whenToAvoid: [
      'Severe pelvic girdle pain',
      'Hip bursitis or pain',
      'Balance issues that make standing on one leg unsafe',
      'Dizziness',
      'Risk of falling',
    ],
    frequency: '12-15 reps per side, 2-3 sets, 3-4 times per week',
    relatedExercises: ['side-lying-leg-lifts', 'squats', 'prenatal-strength-training'],
  },
  {
    slug: 'hip-circles',
    title: 'Hip Circles & Pelvic Mobility',
    category: 'flexibility',
    trimesterSafety: { first: true, second: true, third: true },
    shortDescription: 'Gentle hip and pelvic mobility exercises that reduce pain, improve flexibility, and help position baby for birth.',
    detailedDescription: [
      'Hip circles are a simple yet effective way to maintain pelvic mobility and reduce hip discomfort during pregnancy. The gentle circular motion lubricates the hip joints, stretches surrounding muscles, and can help baby find optimal positioning in the pelvis.',
      'This exercise is particularly popular during late pregnancy and even during early labor, as the rocking motion can be soothing and may help baby descend into the birth canal. Many birthing classes teach hip circles as a labor comfort measure.',
      'The movement also feels good - many pregnant women naturally begin swaying or circling their hips when standing as a way to relieve discomfort. Practicing hip circles consciously increases pelvic awareness and flexibility.',
    ],
    benefits: [
      'Increases pelvic mobility and flexibility',
      'Reduces hip and lower back tension',
      'Helps baby find optimal position for birth',
      'Lubricates hip joints',
      'Soothing and relaxing movement',
      'Can be used during labor for comfort',
      'Improves body awareness and pelvic control',
      'Feels naturally good and intuitive',
    ],
    howToPerform: [
      'Stand with feet hip-width apart, knees slightly bent',
      'Place hands on hips or hold onto chair/counter for support',
      'Make slow, smooth circles with your hips',
      'Circle clockwise for 10 rotations',
      'Circle counter-clockwise for 10 rotations',
      'Start with small circles, gradually make larger',
      'Keep upper body relatively still',
      'Practice for 2-3 minutes',
    ],
    safetyTips: [
      'Use chair or counter for balance if needed',
      'Move slowly and smoothly - no jerking',
      'Keep knees slightly bent throughout',
      'Don\'t force range of motion',
      'Stop if you feel pain or dizziness',
      'Breathe naturally throughout',
      'Stay within comfortable range - circles don\'t need to be large',
      'Can also be done while sitting on exercise ball',
    ],
    modifications: [
      'First trimester: Can do standing with no support',
      'Second trimester: May want to hold support for balance',
      'Third trimester: Use chair/counter support, make smaller circles',
      'Sit on exercise ball and circle hips',
      'Try figure-8 patterns instead of circles',
      'Do while leaning hands on wall',
      'Practice during commercials or while waiting for something',
      'Add to daily routine - can be done anywhere',
    ],
    whenToAvoid: [
      'Severe pelvic girdle pain aggravated by movement',
      'Dizziness or balance issues',
      'Placenta previa (check with provider)',
      'Pain during the movement',
      'Risk of preterm labor with activity restrictions',
    ],
    frequency: '10 circles each direction, 2-3 times daily',
    relatedExercises: ['pelvic-tilts', 'squats', 'prenatal-yoga'],
  },
]

export function getExerciseData(slug: string): ExerciseData | undefined {
  return exercisesData.find((ex) => ex.slug === slug)
}

export function getExercisesByCategory(category: string): ExerciseData[] {
  return exercisesData.filter((ex) => ex.category === category)
}

export function getExercisesByTrimester(trimester: 'first' | 'second' | 'third'): ExerciseData[] {
  return exercisesData.filter((ex) => ex.trimesterSafety[trimester])
}
