// Labor and delivery preparation data

export interface LaborPrepData {
  slug: string
  title: string
  category: 'labor-basics' | 'pain-management' | 'delivery-methods' | 'preparation' | 'interventions'
  shortDescription: string
  detailedDescription: string[]
  keyPoints: string[]
  whatToKnow: string[]
  howToPrepare: string[]
  prosAndCons?: { pros: string[]; cons: string[] }
  whenToConsider?: string[]
  relatedTopics: string[]
}

export const laborPrepData: LaborPrepData[] = [
  {
    slug: 'stages-of-labor',
    title: 'Stages of Labor - What to Expect',
    category: 'labor-basics',
    shortDescription: 'Understanding the three stages of labor from early contractions through delivery and placenta birth.',
    detailedDescription: [
      'Labor progresses through three distinct stages, each with unique characteristics and duration. Understanding these stages helps you know what to expect and when to go to the hospital.',
      'The first stage (labor and dilation) is the longest, divided into early labor, active labor, and transition. The second stage is pushing and delivery. The third stage is delivery of the placenta.',
      'Every labor is different - some progress quickly while others take time. Your healthcare team monitors your progress to ensure both you and baby are doing well throughout.',
    ],
    keyPoints: [
      'Stage 1: Cervical dilation from 0-10cm, divided into three phases',
      'Early labor: 0-6cm dilation, contractions 5-30 minutes apart',
      'Active labor: 6-8cm dilation, contractions 3-5 minutes apart',
      'Transition: 8-10cm dilation, most intense contractions 1-2 minutes apart',
      'Stage 2: Pushing and baby delivery, can last minutes to 3+ hours',
      'Stage 3: Placenta delivery, usually 5-30 minutes after baby',
    ],
    whatToKnow: [
      'First stage averages 12-19 hours for first babies, 8-12 for subsequent births',
      'Active labor is when most people go to hospital (4-6cm dilated)',
      'Transition is shortest but most intense phase',
      'Pushing stage averages 1-2 hours for first babies, less for subsequent',
      'You may not feel urge to push immediately at 10cm',
      'Placenta delivery involves mild contractions',
      'Healthcare team monitors both you and baby throughout',
    ],
    howToPrepare: [
      'Take childbirth education class to learn about each stage',
      'Practice breathing and relaxation techniques',
      'Discuss pain management preferences with provider',
      'Understand when to go to hospital (active labor)',
      'Prepare for long process - stay nourished and hydrated early',
      'Know that every labor is different',
      'Have support person familiar with stages to help advocate',
    ],
    relatedTopics: ['labor-signs', 'contractions-guide', 'when-to-go-hospital', 'pushing-techniques'],
  },
  {
    slug: 'labor-signs',
    title: 'Signs of Labor - When It\'s Starting',
    category: 'labor-basics',
    shortDescription: 'Recognizing true labor signs including contractions, water breaking, and bloody show.',
    detailedDescription: [
      'Knowing the signs of labor helps you identify when it\'s time to head to the hospital. True labor signs include regular contractions that get stronger and closer together, your water breaking, and bloody show.',
      'Many women experience false labor (Braxton Hicks) in late pregnancy, which can be confusing. True labor contractions have a regular pattern, increase in intensity, don\'t stop with rest, and cause cervical change.',
      'Labor can start gradually or suddenly. Some women have clear signs like water breaking, while others have a slow build-up over hours or days.',
    ],
    keyPoints: [
      'Regular contractions that get progressively stronger and closer',
      'Contractions that don\'t stop when you rest or change position',
      'Water breaking (gush or trickle of amniotic fluid)',
      'Bloody show (thick mucus plug with blood)',
      'Back pain that radiates to abdomen',
      'Cervical dilation confirmed by healthcare provider',
    ],
    whatToKnow: [
      'Only 15% of women have water break before contractions start',
      'Braxton Hicks vs. true labor: true labor has regular pattern',
      'Losing mucus plug can happen weeks before labor',
      'Early labor can last hours or days',
      'Use 5-1-1 rule: contractions 5 min apart, lasting 1 min, for 1 hour',
      'Call provider if water breaks regardless of contractions',
      'Trust your instincts - call if something feels wrong',
    ],
    howToPrepare: [
      'Learn difference between true and false labor',
      'Know when to call doctor vs. go to hospital',
      'Time contractions with app or stopwatch',
      'Have hospital bag packed by 36 weeks',
      'Discuss signs with provider at appointments',
      'Don\'t rush to hospital too early unless water breaks',
      'Stay calm and hydrated during early labor at home',
    ],
    relatedTopics: ['stages-of-labor', 'when-to-go-hospital', 'water-breaking', 'braxton-hicks'],
  },
  {
    slug: 'epidural',
    title: 'Epidural Anesthesia for Labor',
    category: 'pain-management',
    shortDescription: 'Regional anesthesia that numbs lower body for pain relief during labor and delivery.',
    detailedDescription: [
      'An epidural provides effective pain relief by numbing the lower half of your body while allowing you to stay awake and alert. It\'s the most common form of pain relief during labor, used by about 70% of women in the US.',
      'The procedure involves inserting a thin catheter into your lower back through which pain medication is continuously delivered. It typically takes 10-20 minutes to place and another 10-15 minutes to take full effect.',
      'Epidurals allow you to rest during long labors, reduce stress hormones, and provide complete pain relief for most women. However, they do come with considerations like limited mobility and potential side effects.',
    ],
    keyPoints: [
      'Numbs lower body from waist down',
      'Allows you to stay awake and alert',
      'Provides near-complete pain relief for most women',
      'Can be adjusted for strength throughout labor',
      'Does not slow labor in active phase',
      'Can be topped up for C-section if needed',
    ],
    whatToKnow: [
      'Must stay in bed once epidural is placed',
      'Catheter inserted in bladder (you won\'t feel need to pee)',
      'Continuous fetal monitoring required',
      'May make pushing stage longer',
      'Can cause drop in blood pressure (monitored closely)',
      'May not work perfectly for everyone (5-10% have inadequate relief)',
      'Takes 10-20 minutes to place, 10-15 to work fully',
    ],
    howToPrepare: [
      'Discuss pros and cons with provider prenatally',
      'Ask anesthesiologist questions when they visit',
      'Understand it\'s not "all or nothing" - can try other methods first',
      'Know you can request it anytime during labor',
      'Don\'t let others pressure your decision either way',
      'Have IV started (required before epidural)',
      'Empty bladder before placement if possible',
    ],
    prosAndCons: {
      pros: [
        'Excellent pain relief for most women',
        'Allows rest during long labors',
        'Can reduce stress and exhaustion',
        'Lowers stress hormones',
        'Awake and alert for delivery',
        'Can be adjusted for comfort',
        'Already in place if C-section needed',
      ],
      cons: [
        'Must stay in bed (can\'t walk)',
        'May prolong pushing stage',
        'Increases likelihood of instrument delivery',
        'Can cause itching, shaking',
        'May drop blood pressure',
        'Rare risks: headache, nerve damage',
        'Requires continuous monitoring',
      ],
    },
    relatedTopics: ['pain-management-options', 'natural-birth', 'spinal-block', 'labor-positions'],
  },
  {
    slug: 'natural-birth',
    title: 'Unmedicated Birth (Natural Birth)',
    category: 'pain-management',
    shortDescription: 'Giving birth without pain medication using natural pain management techniques.',
    detailedDescription: [
      'Natural birth refers to vaginal delivery without epidural or other pain medications. Women choose unmedicated birth for various reasons including desire to experience labor fully, avoiding medication side effects, or faster recovery.',
      'Managing labor pain naturally involves techniques like breathing exercises, movement, water therapy, massage, hypnobirthing, and mental focus. Support from doula or partner is crucial.',
      'Natural birth is challenging but achievable with preparation and support. Many women find it empowering, though there\'s no shame in changing your mind and requesting pain medication.',
    ],
    keyPoints: [
      'Vaginal delivery without epidural or narcotics',
      'Uses natural pain management techniques',
      'Maintains mobility and freedom of movement',
      'Shorter recovery time',
      'Requires strong support system',
      'Can change mind and request medication anytime',
    ],
    whatToKnow: [
      'Labor is intense - requires mental and physical preparation',
      'Support person/doula role is crucial',
      'Freedom to move, walk, shower during labor',
      'May labor at home longer',
      'Can eat and drink during labor',
      'Alert and able to move immediately after delivery',
      'Shorter hospital stay possible',
      'It\'s okay to change your plan',
    ],
    howToPrepare: [
      'Take natural childbirth classes (Bradley, Lamaze, Hypnobirthing)',
      'Practice breathing and relaxation techniques daily',
      'Consider hiring a doula for support',
      'Discuss with provider - ensure they\'re supportive',
      'Create birth plan with natural preferences',
      'Tour birth center or hospital labor rooms',
      'Build trust with support team',
      'Understand it\'s not "failure" if you need medication',
    ],
    prosAndCons: {
      pros: [
        'Freedom of movement during labor',
        'Can eat and drink',
        'No medication side effects',
        'Alert immediately after birth',
        'Shorter recovery time',
        'Lower risk of interventions',
        'Empowering experience for many',
        'Baby alert at birth',
      ],
      cons: [
        'Labor pain is intense',
        'Requires significant mental/physical preparation',
        'Exhaustion can be extreme',
        'May need to change plan if complications arise',
        'Some hospital staff may not be experienced with natural birth',
        'Not all hospitals support natural birth preferences',
      ],
    },
    relatedTopics: ['epidural', 'pain-management-options', 'doula-support', 'birth-center'],
  },
  {
    slug: 'c-section-delivery',
    title: 'Cesarean Section (C-Section)',
    category: 'delivery-methods',
    shortDescription: 'Surgical delivery of baby through incision in abdomen and uterus, either planned or emergency.',
    detailedDescription: [
      'A cesarean section is surgical delivery of your baby through incisions in your abdomen and uterus. About 32% of US births are by C-section. Some are planned in advance (scheduled), while others occur during labor (emergency or unplanned).',
      'Planned C-sections may be recommended for breech baby, placenta previa, certain medical conditions, previous C-sections (though VBAC is often possible), or maternal choice. Unplanned C-sections occur when labor isn\'t progressing or baby is in distress.',
      'C-section is major abdominal surgery requiring longer recovery than vaginal birth. However, it\'s very safe with modern techniques and allows for delivery when vaginal birth isn\'t advisable.',
    ],
    keyPoints: [
      'Surgical delivery through abdominal incision',
      'Can be scheduled or unplanned during labor',
      'Takes 45-60 minutes total, baby out in 5-10 minutes',
      'Requires spinal or epidural anesthesia (rarely general)',
      'Recovery is 6-8 weeks vs. 1-2 weeks for vaginal',
      'Hospital stay 2-4 days vs. 1-2 for vaginal birth',
    ],
    whatToKnow: [
      'Two incisions made: skin/fat and uterus',
      'Usually horizontal ("bikini cut") incision',
      'Partner can be present for scheduled C-section',
      'Spinal block allows you to be awake',
      'May feel pulling/pressure but not pain',
      'See and hold baby immediately after birth',
      'Breastfeeding possible with support',
      'Scar fades significantly over time',
    ],
    howToPrepare: [
      'Discuss reasons and alternatives with provider',
      'Understand it may be necessary for safety',
      'Ask about skin-to-skin in OR if possible',
      'Arrange help at home for recovery',
      'Prepare for limited lifting and movement',
      'Get support pillow for incision',
      'Discuss future pregnancy plans (VBAC possibility)',
      'Know recovery takes longer - be patient with yourself',
    ],
    prosAndCons: {
      pros: [
        'Scheduled timing (for planned C-section)',
        'Shorter time in labor',
        'Lower risk of pelvic floor issues',
        'Less trauma to perineum',
        'May be necessary for safety',
        'Clear view of surgery (if desired)',
      ],
      cons: [
        'Major abdominal surgery',
        'Longer recovery time',
        'More pain after delivery',
        'Risk of infection, bleeding',
        'Harder to pick up baby initially',
        'May affect future pregnancies',
        'Potential for adhesions/scar tissue',
        'Higher cost',
      ],
    },
    relatedTopics: ['vbac', 'epidural', 'c-section-recovery', 'breech-baby'],
  },
  {
    slug: 'vbac',
    title: 'VBAC - Vaginal Birth After Cesarean',
    category: 'delivery-methods',
    shortDescription: 'Attempting vaginal delivery after previous C-section - success rates, risks, and considerations.',
    detailedDescription: [
      'VBAC (Vaginal Birth After Cesarean) means attempting vaginal delivery after having had one or more previous C-sections. Success rates are 60-80% depending on various factors.',
      'Many women are candidates for VBAC, though it requires careful monitoring during labor. The main concern is uterine rupture (rare but serious), which occurs in about 0.5-1% of VBAC attempts.',
      'VBAC offers the benefits of vaginal delivery including faster recovery, while avoiding another surgery. However, not all women or hospitals support VBAC, so planning is essential.',
    ],
    keyPoints: [
      'Success rate 60-80% for VBAC after one C-section',
      'Requires continuous monitoring during labor',
      'Uterine rupture risk about 0.5-1%',
      'Not all hospitals offer VBAC',
      'Benefits include faster recovery, lower infection risk',
      'May need to attempt labor at hospital with OR available',
    ],
    whatToKnow: [
      'Best candidates: One previous C-section with low transverse incision',
      'Labor spontaneously starting improves success',
      'Induction lowers success rate',
      'Must have emergency C-section available',
      'Continuous fetal monitoring required',
      'May not be option with certain uterine incision types',
      'Provider and hospital must support VBAC',
    ],
    howToPrepare: [
      'Get medical records from previous C-section',
      'Find VBAC-supportive provider and hospital',
      'Understand what increases success: spontaneous labor, previous vaginal birth',
      'Discuss risks and benefits thoroughly',
      'Prepare mentally for possibility of repeat C-section',
      'Consider doula with VBAC experience',
      'Join VBAC support group',
      'Stay healthy and at optimal weight for pregnancy',
    ],
    prosAndCons: {
      pros: [
        'Faster recovery than repeat C-section',
        'Experience of vaginal birth',
        'Lower infection risk',
        'Shorter hospital stay',
        'Less risk for future pregnancies',
        'Avoid risks of multiple C-sections',
        'Lower cost',
      ],
      cons: [
        'Small risk of uterine rupture',
        'May end in emergency C-section anyway',
        'Requires hospital with surgical backup',
        'Not all providers support VBAC',
        'Continuous monitoring limits movement',
        'Stress of unknown outcome',
        'Lower success if induction needed',
      ],
    },
    relatedTopics: ['c-section-delivery', 'labor-induction', 'uterine-rupture-risk'],
  },
  {
    slug: 'pain-management-options',
    title: 'Pain Management Options During Labor',
    category: 'pain-management',
    shortDescription: 'Overview of all pain relief options from natural techniques to medical interventions.',
    detailedDescription: [
      'Labor pain management ranges from natural techniques like breathing and positioning to medical options like epidurals and narcotics. There\'s no single right choice - what matters is what works for you.',
      'Natural methods include breathing techniques, water therapy, movement, massage, hypnobirthing, and TENS units. Medical options include nitrous oxide (laughing gas), IV narcotics, and regional anesthesia (epidural/spinal).',
      'Many women use a combination approach, starting with natural methods and adding medication as needed. You can change your mind at any point - pain relief preferences aren\'t a test of strength.',
    ],
    keyPoints: [
      'Natural options: breathing, movement, water, massage, TENS, hypnobirthing',
      'Medical options: nitrous oxide, IV narcotics, epidural, spinal block',
      'Combination approach is common',
      'Can change mind at any point',
      'No option is "better" - depends on personal preference and situation',
      'Provider and hospital availability varies',
    ],
    whatToKnow: [
      'Natural methods work best with preparation and practice',
      'Narcotics provide partial relief, may make you drowsy',
      'Nitrous oxide (if available) offers mild relief, you control',
      'Epidural provides most complete relief',
      'All options have pros and cons',
      'Labor intensity varies - keep open mind',
      'Support person role crucial for natural methods',
    ],
    howToPrepare: [
      'Research all options before labor',
      'Discuss availability with provider and hospital',
      'Take childbirth class covering pain management',
      'Practice natural techniques during pregnancy',
      'Make preferences known but stay flexible',
      'Discuss with partner how they can support',
      'Consider doula for natural pain management support',
      'Remember: using pain relief isn\'t failure',
    ],
    relatedTopics: ['epidural', 'natural-birth', 'nitrous-oxide', 'labor-positions'],
  },
  {
    slug: 'hospital-bag',
    title: 'Hospital Bag Packing List',
    category: 'preparation',
    shortDescription: 'Complete checklist of what to pack for labor, delivery, and postpartum hospital stay.',
    detailedDescription: [
      'Packing your hospital bag by 36 weeks ensures you\'re ready when labor starts. You\'ll need items for labor, delivery, postpartum recovery, baby\'s first days, and going home.',
      'Hospitals provide basics like pads, mesh underwear, and diapers, but bringing your own comfort items makes your stay more pleasant. Pack practical items, not your entire house.',
      'Consider packing two bags: one for labor/delivery and one for postpartum. Leave bags in car or near door starting at 36 weeks.',
    ],
    keyPoints: [
      'Pack by 36 weeks in case of early labor',
      'Bring ID, insurance cards, birth plan copies',
      'Comfortable clothes for labor and going home',
      'Toiletries and comfort items',
      'Baby outfit and car seat (required to leave)',
      'Phone charger and camera',
      'Snacks for after delivery and partner',
    ],
    whatToKnow: [
      'Hospital provides: pads, mesh underwear, diapers, wipes, basic toiletries',
      'Most clothing during labor won\'t fit same afterward - bring options',
      'Baby outfit should be newborn size (may be small)',
      'Must have car seat to leave hospital',
      'Keep bags in car or near door from 36 weeks',
      'Don\'t bring valuables',
      'Partner should pack bag too',
    ],
    howToPrepare: [
      'Make list and check off items as packed',
      'Pack essentials in one easily-grabbed bag',
      'Include copies of birth plan',
      'Pre-install car seat and have it checked',
      'Bring multiple size baby outfits just in case',
      'Pack phone charger and long cord',
      'Include going-home outfit for you (maternity-sized)',
      'Leave bags accessible from 36 weeks on',
    ],
    relatedTopics: ['birth-plan', 'labor-signs', 'postpartum-recovery'],
  },
  {
    slug: 'birth-plan',
    title: 'Creating a Birth Plan',
    category: 'preparation',
    shortDescription: 'How to create a flexible birth plan communicating your preferences for labor and delivery.',
    detailedDescription: [
      'A birth plan is a document communicating your preferences for labor, delivery, and immediate postpartum. It helps your healthcare team understand what\'s important to you, but should be flexible as birth is unpredictable.',
      'Effective birth plans are concise (one page), cover key preferences, and acknowledge things may change. They\'re conversation starters with your provider, not rigid demands.',
      'Cover pain management preferences, labor atmosphere, who you want present, positions for labor and delivery, interventions, and newborn care preferences.',
    ],
    keyPoints: [
      'Keep it to one page',
      'Cover pain relief, atmosphere, support people',
      'Include position preferences and interventions',
      'Address newborn care (skin-to-skin, feeding)',
      'Note what matters most vs. flexible points',
      'Discuss with provider beforehand',
    ],
    whatToKnow: [
      'Birth is unpredictable - flexibility is key',
      'Staff wants to support your preferences when possible',
      'Some preferences may not be possible for safety',
      'C-section birth plan may also be needed',
      'Bring multiple copies to hospital',
      'Partner should be familiar with your wishes',
      'Revisit and revise as pregnancy progresses',
    ],
    howToPrepare: [
      'Research options and hospital policies',
      'Discuss plan with provider at prenatal visit',
      'Make sure preferences are realistic and possible',
      'Prioritize what matters most',
      'Keep language positive and flexible',
      'Create C-section version too',
      'Give copies to provider, partner, doula',
      'Remember it\'s a guide, not a contract',
    ],
    relatedTopics: ['pain-management-options', 'hospital-bag', 'labor-positions'],
  },
  {
    slug: 'labor-positions',
    title: 'Labor Positions for Comfort & Progress',
    category: 'labor-basics',
    shortDescription: 'Best positions during labor to manage pain, encourage baby\'s descent, and facilitate delivery.',
    detailedDescription: [
      'Movement and position changes during labor help manage pain and encourage baby to move down and rotate into optimal position. Staying mobile in early and active labor has many benefits.',
      'Upright positions use gravity to help baby descend. Hands-and-knees relieves back labor. Side-lying is restful while keeping labor progressing. Squatting opens the pelvis.',
      'With epidural, you can still change positions with help. Use pillows, birthing balls, and support from partner to try different positions.',
    ],
    keyPoints: [
      'Movement and position changes aid labor progress',
      'Upright positions use gravity',
      'Hands-and-knees helps back labor',
      'Side-lying allows rest while progressing',
      'Squatting opens pelvis',
      'Can change positions even with epidural',
    ],
    whatToKnow: [
      'No single best position - change frequently',
      'Listen to your body',
      'Partner can support you in positions',
      'Birthing ball, peanut ball very helpful',
      'Water labor allows easy position changes',
      'Positions for pushing may differ from labor',
      'Staff can help you try different positions',
    ],
    howToPrepare: [
      'Practice positions during pregnancy',
      'Learn positions in childbirth class',
      'Discuss freedom of movement with provider',
      'Partner should know how to support you',
      'Bring comfort items (pillow, birthing ball if allowed)',
      'Ask about wireless monitoring if you want to move',
      'Stay open to trying new positions during labor',
    ],
    relatedTopics: ['natural-birth', 'back-labor', 'pushing-techniques'],
  },
  {
    slug: 'when-to-go-hospital',
    title: 'When to Go to the Hospital',
    category: 'labor-basics',
    shortDescription: 'Guidelines for knowing when it\'s time to head to hospital or birth center during labor.',
    detailedDescription: [
      'Timing your hospital arrival is important - going too early may lead to interventions, while waiting too long risks delivering en route. Use the 5-1-1 rule as general guidance for first babies.',
      'The 5-1-1 rule: contractions 5 minutes apart, lasting 1 minute each, for 1 hour. However, call immediately if water breaks, you have bleeding, or something feels wrong.',
      'Every pregnancy is different. Second babies often come faster. Trust your instincts and call your provider if unsure.',
    ],
    keyPoints: [
      '5-1-1 rule: Contractions 5 min apart, 1 min long, for 1 hour',
      'Go immediately if water breaks',
      'Go if bleeding or something feels wrong',
      'Active labor is usual time (6cm dilated)',
      'Second babies often progress faster',
      'Call provider first for guidance',
    ],
    whatToKnow: [
      'May be sent home if in early labor',
      'Laboring at home initially is often helpful',
      'Use contraction timer app',
      'Stay hydrated and nourished early on',
      'Different providers have different guidelines',
      'Consider drive time to hospital',
      'Have backup transportation plan',
    ],
    howToPrepare: [
      'Know your provider\'s specific guidelines',
      'Save hospital labor & delivery phone number',
      'Practice route and parking',
      'Know where to enter after hours',
      'Have hospital bag packed by 36 weeks',
      'Discuss timing with provider at appointments',
      'Trust your instincts - call if concerned',
    ],
    relatedTopics: ['labor-signs', 'stages-of-labor', 'false-labor'],
  },
  {
    slug: 'water-breaking',
    title: 'Water Breaking - What to Expect',
    category: 'labor-basics',
    shortDescription: 'Understanding when and how water breaks, what it means, and what to do when it happens.',
    detailedDescription: [
      'Your "water breaking" means the amniotic sac ruptures, releasing the fluid surrounding your baby. It can be a gush or slow trickle. Only 15% of labors begin with water breaking - for most, contractions start first.',
      'When water breaks, note the time, amount (gush or trickle), color (should be clear), and smell. Call your provider immediately as risk of infection increases after rupture.',
      'After water breaks, labor usually begins within 24 hours. If not, induction may be recommended to reduce infection risk.',
    ],
    keyPoints: [
      'Only 15% of labors start with water breaking',
      'Can be gush or trickle',
      'Should be clear and odorless',
      'Call provider immediately when water breaks',
      'Labor usually starts within 24 hours',
      'Risk of infection increases after rupture',
    ],
    whatToKnow: [
      'May not be dramatic gush - can trickle',
      'Different from discharge or urine',
      'Cannot be stopped once it starts',
      'Should be clear or pale yellow',
      'Green/brown color may indicate meconium',
      'May feel relief of pressure when it breaks',
      'Contractions may intensify after rupture',
    ],
    howToPrepare: [
      'Keep waterproof pad in bed after 36 weeks',
      'Use maxi pad if trickling to see amount',
      'Note time, color, and amount',
      'Call provider immediately',
      'Head to hospital even if no contractions yet',
      'Don\'t have sex or use tampons after water breaks',
      'Know that induction may be recommended if labor doesn\'t start',
    ],
    relatedTopics: ['labor-signs', 'labor-induction', 'when-to-go-hospital'],
  },
  {
    slug: 'labor-induction',
    title: 'Labor Induction Methods & Process',
    category: 'interventions',
    shortDescription: 'Medical methods to start labor including Pitocin, Foley catheter, and membrane sweeping.',
    detailedDescription: [
      'Labor induction means using medical methods to start labor before it begins naturally. Common reasons include post-dates pregnancy (41-42 weeks), medical conditions, or water breaking without contractions.',
      'Induction methods include ripening the cervix (if not dilated) with Foley catheter, prostaglandin gel, or medication, followed by Pitocin (synthetic oxytocin) to stimulate contractions.',
      'Induced labor can take 12-24+ hours, especially if cervix isn\'t favorable. Understanding the process and asking questions helps manage expectations.',
    ],
    keyPoints: [
      'Used when continuing pregnancy is riskier than delivery',
      'Common reasons: post-dates, preeclampsia, diabetes, water broke',
      'Methods: membrane sweep, Foley catheter, prostaglandins, Pitocin',
      'May take 12-24+ hours',
      'Success depends on cervical ripeness (Bishop score)',
      'Can increase need for pain relief',
    ],
    whatToKnow: [
      'Not same as spontaneous labor',
      'Pitocin contractions may feel stronger',
      'Continuous monitoring usually required',
      'May not be able to walk during Pitocin',
      'Takes longer than many expect',
      'Sometimes induction doesn\'t work - C-section needed',
      'Eat well before arriving if allowed',
    ],
    howToPrepare: [
      'Understand why induction is recommended',
      'Ask about Bishop score (cervical readiness)',
      'Discuss methods provider will use',
      'Ask about timeline expectations',
      'Understand this is a marathon, not sprint',
      'Consider pain management plan',
      'Bring entertainment for long process',
      'Have support person for entire process',
    ],
    relatedTopics: ['pitocin', 'membrane-sweep', 'overdue-pregnancy', 'bishop-score'],
  },
  {
    slug: 'pushing-techniques',
    title: 'Pushing Techniques for Delivery',
    category: 'labor-basics',
    shortDescription: 'How to push effectively during second stage of labor to deliver your baby.',
    detailedDescription: [
      'The pushing stage begins when you\'re fully dilated (10cm) and ends with baby\'s birth. How you push can affect the length of this stage and perineal trauma.',
      'Two main approaches: directed pushing (coached pushing on count of ten) and spontaneous pushing (following your body\'s urges). Research suggests spontaneous pushing may reduce perineal trauma.',
      'Pushing can last minutes to 3+ hours for first-time moms, less for subsequent births. Position matters - upright or side-lying may be more effective than traditional lying on back.',
    ],
    keyPoints: [
      'Begins at 10cm dilation',
      'Two methods: directed vs. spontaneous pushing',
      'Average 1-2 hours first baby, less for subsequent',
      'Position affects effectiveness',
      'Push when you feel urge (with or without epidural)',
      'May need vacuum or forceps assistance',
    ],
    whatToKnow: [
      'May not feel urge immediately at 10cm',
      '"Laboring down" lets baby descend before active pushing',
      'With epidural, may not feel urge to push as strongly',
      'Purple pushing (holding breath long) not recommended',
      'Short pushes with breathing more effective',
      'Position changes help if baby not descending',
      'Tearing or episiotomy possible',
    ],
    howToPrepare: [
      'Learn different pushing techniques in class',
      'Practice breathing and pushing exercises',
      'Discuss preferences with provider',
      'Consider positions besides lying on back',
      'Understand perineal massage may help',
      'Know when instruments (vacuum/forceps) may be used',
      'Trust your body and the process',
    ],
    relatedTopics: ['stages-of-labor', 'labor-positions', 'episiotomy', 'perineal-tearing'],
  },
  {
    slug: 'fetal-monitoring',
    title: 'Fetal Monitoring During Labor',
    category: 'interventions',
    shortDescription: 'How baby\'s heart rate is monitored during labor to ensure well-being.',
    detailedDescription: [
      'Fetal monitoring tracks your baby\'s heart rate during labor to ensure they\'re handling contractions well. It helps identify if baby is in distress and needs intervention.',
      'External monitoring uses two belts around your belly - one for baby\'s heartbeat, one for contractions. Intermittent monitoring checks periodically; continuous monitoring is constant.',
      'Low-risk labors often use intermittent monitoring, allowing more freedom of movement. High-risk labors, inductions, and epidurals typically require continuous monitoring.',
    ],
    keyPoints: [
      'Monitors baby\'s heart rate response to contractions',
      'Two types: intermittent and continuous',
      'External (belts) or internal (scalp electrode)',
      'Helps identify if baby is in distress',
      'Continuous required for epidural and high-risk',
      'Wireless monitors available at some hospitals',
    ],
    whatToKnow: [
      'Normal fetal heart rate: 110-160 beats per minute',
      'Heart rate should vary (variability is good)',
      'Accelerations are reassuring',
      'Decelerations happen - not all are concerning',
      'Continuous monitoring may limit movement',
      'Wireless monitors allow more mobility',
      'Sometimes needs adjustment to pick up signal',
    ],
    howToPrepare: [
      'Understand why monitoring is important',
      'Ask about wireless monitoring options',
      'Discuss intermittent vs. continuous',
      'Know that continuous limits mobility but ensures safety',
      'Don\'t refuse monitoring - it protects baby',
      'Ask questions if staff concerned about readings',
      'Position changes may affect monitor readings',
    ],
    relatedTopics: ['labor-complications', 'epidural', 'labor-induction'],
  },
  {
    slug: 'episiotomy',
    title: 'Episiotomy - Surgical Cut During Delivery',
    category: 'interventions',
    shortDescription: 'Surgical incision in perineum to widen vaginal opening during delivery - when it\'s necessary.',
    detailedDescription: [
      'An episiotomy is a surgical cut made in the perineum (tissue between vagina and anus) to enlarge the vaginal opening during delivery. Once routine, it\'s now only done when medically necessary.',
      'Episiotomies are no longer routine because natural tears often heal better than surgical cuts. They\'re reserved for situations like baby in distress needing quick delivery, shoulder dystocia, or to prevent severe tearing.',
      'The cut is made with scissors and repaired with dissolvable stitches after delivery. Recovery involves keeping area clean, using ice packs, and taking stool softeners.',
    ],
    keyPoints: [
      'Surgical cut in perineum during delivery',
      'No longer routine - only when medically necessary',
      'Two types: midline and mediolateral',
      'Made with local anesthetic',
      'Repaired with dissolvable stitches',
      'Recovery similar to tearing',
    ],
    whatToKnow: [
      'Only 12% of vaginal births involve episiotomy now',
      'Used when: baby in distress, shoulder dystocia, preventing severe tear',
      'Natural tears often heal better',
      'You can decline routine episiotomy',
      'May not prevent all tearing',
      'Heals in 2-3 weeks',
      'Can have sex again once healed (usually 6 weeks)',
    ],
    howToPrepare: [
      'Discuss provider\'s episiotomy rate and philosophy',
      'Include preference in birth plan',
      'Perineal massage in late pregnancy may help',
      'Understand when it may be medically necessary',
      'Don\'t fear tearing - most are minor',
      'Prepare postpartum care supplies: peri bottle, ice packs',
      'Know that refusal of routine episiotomy is reasonable',
    ],
    relatedTopics: ['perineal-tearing', 'pushing-techniques', 'perineal-massage'],
  },
  {
    slug: 'doula-support',
    title: 'Hiring a Doula for Birth Support',
    category: 'preparation',
    shortDescription: 'Professional labor support providing emotional and physical assistance during birth.',
    detailedDescription: [
      'A doula is a trained professional who provides continuous physical, emotional, and informational support during labor and birth. Unlike nurses who care for multiple patients, a doula stays with you the entire time.',
      'Research shows doulas reduce C-section rates, decrease labor length, reduce pain medication use, and improve satisfaction with birth experience. They don\'t replace your partner but support both of you.',
      'Doulas provide comfort measures like massage, position suggestions, breathing guidance, and emotional encouragement. They help you communicate with medical staff and advocate for your preferences.',
    ],
    keyPoints: [
      'Professional trained in labor support',
      'Stays with you entire labor',
      'Reduces interventions and increases satisfaction',
      'Provides comfort measures, positioning help',
      'Supports partner, doesn\'t replace them',
      'Costs $800-2500 depending on location and experience',
    ],
    whatToKnow: [
      'Not medical professional - doesn\'t do clinical tasks',
      'Evidence shows improved outcomes with doula',
      'Helps with natural pain management',
      'Can support epidural births too',
      'Works with medical staff, doesn\'t interfere',
      'Supports partner so they can focus on emotional support',
      'Usually includes prenatal visits and postpartum check-in',
    ],
    howToPrepare: [
      'Research and interview doulas by second trimester',
      'Ask about training, experience, philosophy',
      'Check if insurance covers (some do)',
      'Meet 2-3 doulas before deciding',
      'Discuss fees, backup doula, services included',
      'Introduce doula to your partner',
      'Ensure hospital allows doula (most do)',
      'Consider it worth the investment',
    ],
    relatedTopics: ['natural-birth', 'birth-plan', 'labor-support-techniques'],
  },
  {
    slug: 'back-labor',
    title: 'Back Labor - Causes & Relief',
    category: 'labor-basics',
    shortDescription: 'Intense lower back pain during labor when baby is in posterior position and how to relieve it.',
    detailedDescription: [
      'Back labor refers to intense lower back pain during labor, typically caused by baby being in "sunny-side up" (posterior) position with their head pressing on your spine. About 25% of babies are posterior.',
      'Back labor is more painful than typical labor because pressure is focused on the lower spine. Contractions are felt primarily in the back rather than abdomen.',
      'Position changes and counter-pressure can help relieve pain and encourage baby to rotate. Most posterior babies rotate during labor, but some deliver posterior.',
    ],
    keyPoints: [
      'Caused by baby in posterior (sunny-side up) position',
      'Intense lower back pain during contractions',
      'Affects about 25% of labors',
      'Often leads to longer labor',
      'Position changes can help baby rotate',
      'Counter-pressure provides relief',
    ],
    whatToKnow: [
      'More painful than typical labor',
      'Contractions felt in back, not belly',
      'May have irregular contraction pattern',
      'Labor often longer if baby stays posterior',
      'Many posterior babies rotate during labor',
      'Can still deliver vaginally if baby stays posterior',
      'Epidural may be especially helpful',
    ],
    howToPrepare: [
      'Learn positions that encourage rotation: hands-and-knees, lunges',
      'Practice counter-pressure techniques with partner',
      'Consider hiring doula experienced with back labor',
      'Use birthing ball during pregnancy for optimal positioning',
      'Understand position changes are key',
      'Prepare for potentially longer labor',
      'Know when to request pain relief',
    ],
    relatedTopics: ['labor-positions', 'doula-support', 'posterior-baby-position'],
  },
  {
    slug: 'childbirth-classes',
    title: 'Childbirth Education Classes',
    category: 'preparation',
    shortDescription: 'Preparing for labor and birth through childbirth education - what to expect from classes.',
    detailedDescription: [
      'Childbirth classes prepare you and your partner for labor, delivery, and early newborn care. They\'re typically taken in the third trimester and cover what happens during labor, pain management, and immediate postpartum.',
      'Different class types include hospital classes, Lamaze, Bradley Method, Hypnobirthing, and online options. Choose based on your birth philosophy and learning style.',
      'Classes reduce anxiety by demystifying the birth process, teach coping techniques, and help partners understand their support role.',
    ],
    keyPoints: [
      'Usually taken in third trimester (weeks 28-36)',
      'Cover labor stages, pain management, newborn care',
      'Different methods: hospital, Lamaze, Bradley, Hypnobirthing',
      'Often include tour of birth facility',
      'Teach partner how to support',
      'Reduce anxiety through education',
    ],
    whatToKnow: [
      'Series of classes (4-8 weeks) or one-day intensive',
      'In-person vs. online options',
      'Hospital classes free or low-cost',
      'Private instructors cost $200-400',
      'Cover breathing, positions, pain management',
      'Include newborn care basics',
      'Great place to meet other expecting parents',
    ],
    howToPrepare: [
      'Register by 28-30 weeks (fill up quickly)',
      'Decide what type aligns with your birth goals',
      'Check what hospital offers',
      'Research private instructors if desired',
      'Both partners should attend',
      'Take earlier rather than later',
      'Consider infant CPR class too',
      'Bring questions to ask instructor',
    ],
    relatedTopics: ['birth-plan', 'pain-management-options', 'newborn-care-basics'],
  },
  {
    slug: 'breech-baby',
    title: 'Breech Baby Position & Delivery Options',
    category: 'delivery-methods',
    shortDescription: 'When baby is bottom-down instead of head-down - turning techniques and delivery options.',
    detailedDescription: [
      'Breech position means baby is bottom-down or feet-down instead of head-down. About 3-4% of babies are breech at term. Most are head-down by 36 weeks.',
      'If baby is breech near term, options include external cephalic version (manually turning baby), waiting to see if baby turns, or scheduled C-section. Most providers recommend C-section for breech.',
      'Some techniques may encourage baby to turn: certain positions, chiropractic care, acupuncture. Success varies, but many babies turn on their own by 37 weeks.',
    ],
    keyPoints: [
      'Baby is bottom or feet-first instead of head-down',
      'Affects 3-4% of term pregnancies',
      'Types: frank (feet by head), complete (crossed legs), footling (feet first)',
      'External cephalic version can turn baby (50-70% success)',
      'Most breech babies delivered by C-section',
      'Some techniques may encourage turning',
    ],
    whatToKnow: [
      'Breech discovered at 32-36 week ultrasound',
      'Many babies turn on their own by 37 weeks',
      'External version attempted at 37 weeks if still breech',
      'Version uncomfortable but not usually painful',
      'Small risk of emergency C-section during version',
      'Few providers perform vaginal breech delivery',
      'C-section usually scheduled at 39 weeks',
    ],
    howToPrepare: [
      'Discuss options if baby breech at 32+ weeks',
      'Try positions: bridge, hands-and-knees, inversion',
      'Consider chiropractic (Webster technique)',
      'Ask about external cephalic version',
      'Understand risks and success rate of version',
      'Prepare mentally for possible C-section',
      'Get second opinion if desired',
      'Know that many babies turn last minute',
    ],
    relatedTopics: ['c-section-delivery', 'external-cephalic-version', 'baby-position'],
  },
  {
    slug: 'cord-blood-banking',
    title: 'Cord Blood Banking Options',
    category: 'preparation',
    shortDescription: 'Deciding whether to bank, donate, or discard umbilical cord blood after delivery.',
    detailedDescription: [
      'Cord blood banking involves collecting blood from the umbilical cord after delivery and storing it for potential future medical use. Cord blood contains stem cells that can treat certain diseases.',
      'Three options: private banking (storing for your family, costs $1000-2000 + annual fees), public donation (free, available to anyone who needs it), or discarding (standard practice).',
      'Private banking is expensive with low likelihood of use. Public donation helps others at no cost to you. Most medical organizations don\'t recommend routine private banking unless family history of conditions treatable with stem cells.',
    ],
    keyPoints: [
      'Collects blood from umbilical cord after birth',
      'Contains stem cells that can treat certain diseases',
      'Three options: private bank, public donate, discard',
      'Private banking costs $1000-2000 + $100-200/year storage',
      'Public donation is free and altruistic',
      'Likelihood of using own cord blood is low',
    ],
    whatToKnow: [
      'Collection must be arranged before delivery',
      'Doesn\'t interfere with delivery or delayed cord clamping',
      'Private banks are for-profit companies',
      'Public banks available in limited locations',
      'Treats certain cancers, blood disorders, immune conditions',
      'Your child\'s cord blood may not be usable for them (genetic conditions)',
      'Sibling match more likely than general population',
    ],
    howToPrepare: [
      'Decide by 34-36 weeks',
      'Research private banks if considering',
      'Check if hospital participates in public donation program',
      'Discuss with provider and pediatrician',
      'Consider family history of treatable conditions',
      'Understand likelihood of use is very low',
      'Don\'t let private banks pressure you',
      'Public donation is generous alternative',
    ],
    relatedTopics: ['delayed-cord-clamping', 'newborn-procedures'],
  },
  {
    slug: 'delayed-cord-clamping',
    title: 'Delayed Cord Clamping Benefits',
    category: 'preparation',
    shortDescription: 'Waiting to clamp umbilical cord after birth to allow blood transfer to baby.',
    detailedDescription: [
      'Delayed cord clamping means waiting 30-60 seconds (or longer) before clamping and cutting the umbilical cord, allowing blood to continue flowing from placenta to baby. This transfers about 30% more blood to baby.',
      'Benefits include higher iron levels in infancy, improved cardiovascular stability at birth, and better outcomes especially for preterm babies. It\'s now recommended by major medical organizations.',
      'Delay doesn\'t prevent cord blood banking, partner cutting cord, or skin-to-skin immediately after birth. Baby can be on your chest while cord is attached.',
    ],
    keyPoints: [
      'Wait 30-60+ seconds before clamping cord',
      'Transfers about 30% more blood to baby',
      'Improves iron levels for months',
      'Recommended by AAP, ACOG, WHO',
      'Compatible with most birth preferences',
      'No significant risks',
    ],
    whatToKnow: [
      'Most hospitals now do this routinely',
      'Usually wait 30-60 seconds for full-term',
      'Immediate clamping only if baby needs resuscitation',
      'Baby can be on your chest during wait',
      'Partner can still cut cord after delay',
      'Doesn\'t collect as much for cord blood banking',
      'Small increased risk of jaundice (not significant)',
    ],
    howToPrepare: [
      'Include preference in birth plan',
      'Discuss with provider prenatally',
      'Confirm hospital policy',
      'Ask how long they usually wait',
      'Know it\'s compatible with your other preferences',
      'Understand benefits for baby',
      'Request it if not standard practice',
    ],
    relatedTopics: ['cord-blood-banking', 'newborn-procedures', 'skin-to-skin'],
  },
  {
    slug: 'vaginal-birth',
    title: 'Vaginal Delivery Process',
    category: 'delivery-methods',
    shortDescription: 'What happens during normal vaginal birth from pushing through delivery and initial recovery.',
    detailedDescription: [
      'Vaginal delivery is the natural birth process through the birth canal. After complete dilation (10cm), you push during contractions until baby\'s head crowns and delivers, followed by the body.',
      'The process involves the pushing stage (stage 2 of labor), delivery of baby, immediate newborn care, and delivery of the placenta (stage 3). Most vaginal deliveries happen without complications.',
      'You may feel intense pressure, stretching, and burning sensation as baby crowns ("ring of fire"). After delivery, placenta is delivered with gentle pushing, and any tears are repaired.',
    ],
    keyPoints: [
      'Push during contractions when fully dilated',
      'Baby\'s head delivers first, then body',
      'Pressure and stretching sensation normal',
      '"Ring of fire" as baby crowns',
      'Placenta delivers 5-30 minutes after baby',
      'Skin-to-skin immediately after if all is well',
    ],
    whatToKnow: [
      'Pushing stage averages 1-2 hours first baby',
      'You may poop during pushing (normal and okay)',
      'Provider may stretch perineum or suggest positions',
      'Baby often has cone-shaped head at first (normal)',
      'Cord stops pulsing before it\'s cut',
      'Placenta delivery involves mild contractions',
      'Repair of tears done with local anesthetic',
    ],
    howToPrepare: [
      'Take childbirth class',
      'Practice breathing and pushing exercises',
      'Understand perineal anatomy',
      'Discuss pain management preferences',
      'Learn about positions for pushing',
      'Prepare mentally for intensity',
      'Know that instinct and staff guidance help',
      'Understand immediate newborn procedures',
    ],
    relatedTopics: ['pushing-techniques', 'perineal-tearing', 'episiotomy', 'stages-of-labor'],
  },
]

export function getLaborPrepData(slug: string): LaborPrepData | undefined {
  return laborPrepData.find((topic) => topic.slug === slug)
}

export function getLaborPrepByCategory(category: string): LaborPrepData[] {
  return laborPrepData.filter((topic) => topic.category === category)
}
