// Pregnancy medical tests and procedures data

export interface MedicalTestData {
  slug: string
  title: string
  category: 'ultrasound' | 'blood-test' | 'screening' | 'diagnostic' | 'routine' | 'specialized'
  whenPerformed: string
  isRoutine: boolean
  shortDescription: string
  detailedDescription: string[]
  purpose: string[]
  howItsPerformed: string[]
  whatToExpect: string[]
  resultsTimeline: string
  normalResults: string
  abnormalResults: string[]
  risks: string[]
  preparation: string[]
  relatedTests: string[]
}

export const medicalTestsData: MedicalTestData[] = [
  {
    slug: 'dating-ultrasound',
    title: 'Dating Ultrasound (First Trimester Ultrasound)',
    category: 'ultrasound',
    whenPerformed: 'Weeks 8-13, typically around 10-12 weeks',
    isRoutine: true,
    shortDescription: 'First ultrasound to confirm pregnancy, determine due date, check for heartbeat, and assess early development.',
    detailedDescription: [
      'The dating ultrasound, also called the first trimester ultrasound, is typically your first glimpse of your baby. This early scan confirms your pregnancy, establishes an accurate due date, and checks that the pregnancy is developing normally in the uterus.',
      'Your provider uses sound waves to create images of your baby. At this early stage, your baby is still very small (about 1-2 inches), but you can usually see the heartbeat flickering on the screen - one of the most exciting moments of early pregnancy.',
      'This scan is crucial for determining your accurate due date, which will be used throughout your pregnancy for scheduling tests and monitoring development. Dating by ultrasound is more accurate than calculating by your last menstrual period.',
    ],
    purpose: [
      'Confirm pregnancy and viable intrauterine pregnancy',
      'Establish accurate due date and gestational age',
      'Detect baby\'s heartbeat',
      'Rule out ectopic pregnancy',
      'Determine if you\'re carrying multiples (twins, triplets)',
      'Check for early signs of complications',
      'Measure crown-rump length to confirm dating',
      'Assess early development of placenta',
    ],
    howItsPerformed: [
      'May be done trans-abdominally (on your belly) or trans-vaginally',
      'Trans-vaginal is more common before 10 weeks for clearer images',
      'For abdominal ultrasound, you may need a full bladder',
      'Gel applied to skin to help sound waves transmit',
      'Technician moves wand (transducer) across belly or inserts it gently',
      'Images appear on screen in real-time',
      'Takes about 15-30 minutes',
      'Completely painless, though full bladder can be uncomfortable',
    ],
    whatToExpect: [
      'You\'ll see your baby on screen - very small but visible',
      'Heartbeat usually visible as flickering movement',
      'Baby measures about 1-2 inches at this stage',
      'May see arms and legs budding',
      'Yolk sac visible providing nutrition',
      'Can determine if single or multiple pregnancy',
      'Photos usually provided to take home',
      'May be emotional seeing your baby for first time',
    ],
    resultsTimeline: 'Immediate - technician can see and discuss findings during scan',
    normalResults: 'Single intrauterine pregnancy with heartbeat visible, dating matches expected timeline, normal development',
    abnormalResults: [
      'No heartbeat detected (may indicate miscarriage or incorrect dating)',
      'Ectopic pregnancy (outside the uterus)',
      'Molar pregnancy (abnormal placental growth)',
      'Blighted ovum (empty gestational sac)',
      'Multiple pregnancies when unexpected',
      'Dating significantly different from expected',
      'Abnormalities in early development',
    ],
    risks: [
      'No known risks - ultrasound uses sound waves, not radiation',
      'Non-invasive and safe for baby and mother',
      'Trans-vaginal ultrasound may cause slight discomfort but is safe',
      'Very small risk of false reassurance if abnormality not yet visible',
    ],
    preparation: [
      'May need full bladder for abdominal ultrasound (drink 32oz water 1 hour before)',
      'Wear comfortable, loose clothing',
      'Consider bringing partner or support person',
      'Have questions written down to ask technician or doctor',
      'Bring tissues - emotional moment for many parents',
      'Expect to see very tiny baby, not developed features yet',
    ],
    relatedTests: ['nuchal-translucency', 'anatomy-scan', 'nipt'],
  },
  {
    slug: 'anatomy-scan',
    title: 'Anatomy Scan (20-Week Ultrasound)',
    category: 'ultrasound',
    whenPerformed: 'Weeks 18-22, typically around week 20',
    isRoutine: true,
    shortDescription: 'Detailed mid-pregnancy ultrasound examining baby\'s anatomy, growth, and development. Often when you can learn baby\'s sex.',
    detailedDescription: [
      'The anatomy scan, also called the 20-week ultrasound or level II ultrasound, is the most detailed ultrasound of pregnancy. This comprehensive examination checks your baby\'s anatomy from head to toe, ensuring all organs and systems are developing normally.',
      'During this scan, the technician systematically examines your baby\'s brain, face, spine, heart, stomach, kidneys, bladder, arms, legs, and all major structures. They also check the placenta location, amniotic fluid levels, and umbilical cord.',
      'This is often the scan where parents choose to learn their baby\'s sex if they want to know. However, the primary purpose is medical - to check for any developmental issues or abnormalities that may need monitoring or treatment.',
    ],
    purpose: [
      'Examine all major organs and body structures',
      'Check heart structure and function in detail',
      'Assess brain and spinal cord development',
      'Measure growth and confirm due date',
      'Determine placenta location (rule out placenta previa)',
      'Check amniotic fluid levels',
      'Detect structural abnormalities or birth defects',
      'Optionally determine baby\'s sex',
    ],
    howItsPerformed: [
      'Standard abdominal ultrasound with gel on belly',
      'Takes 30-60 minutes (longer than other scans)',
      'Technician systematically examines every part of baby',
      'Multiple images captured from different angles',
      'May need to reposition if baby isn\'t cooperative',
      'Non-invasive and painless',
      'Performed by specialized ultrasound technician',
      'Doctor reviews images and provides official results',
    ],
    whatToExpect: [
      'Much clearer, detailed images than first ultrasound',
      'Can see baby\'s face, fingers, toes clearly',
      'Baby is much more developed, about 10 inches long',
      'May see baby moving, sucking thumb, or yawning',
      'Technician will be quiet during exam (needs to concentrate)',
      'Questions answered after exam is complete',
      'Photos and possibly video provided',
      'Can usually learn sex if desired and baby cooperates',
    ],
    resultsTimeline: 'Preliminary findings immediately, official results within 1-2 days from doctor',
    normalResults: 'All structures developing normally, appropriate growth, normal placenta position, normal fluid levels',
    abnormalResults: [
      'Structural abnormalities (heart defects, neural tube defects, etc.)',
      'Growth restriction or concerns',
      'Placenta previa (placenta covering cervix)',
      'Too much or too little amniotic fluid',
      'Markers for chromosomal conditions',
      'Umbilical cord abnormalities',
      'Multiple pregnancy complications',
    ],
    risks: [
      'No risks to mother or baby',
      'Non-invasive with no radiation',
      'Completely safe',
      'Slight chance of false positive findings requiring further testing',
    ],
    preparation: [
      'Usually don\'t need full bladder (unlike early ultrasounds)',
      'Wear two-piece outfit for easy belly access',
      'Bring partner or support person',
      'Allow extra time - can take 45-60 minutes',
      'Prepare questions for technician or doctor',
      'Decide beforehand if you want to know sex',
      'Some practices give 3D/4D images - ask if interested',
    ],
    relatedTests: ['dating-ultrasound', 'growth-scan', 'fetal-echocardiogram'],
  },
  {
    slug: 'glucose-test',
    title: 'Glucose Screening Test (Gestational Diabetes Test)',
    category: 'blood-test',
    whenPerformed: 'Weeks 24-28',
    isRoutine: true,
    shortDescription: 'Blood test to screen for gestational diabetes by measuring how your body processes sugar.',
    detailedDescription: [
      'The glucose screening test checks how your body processes sugar to detect gestational diabetes, a condition that develops during pregnancy when your body can\'t produce enough insulin. Gestational diabetes affects 2-10% of pregnancies.',
      'Most women take a one-hour glucose challenge test first. You drink a very sweet glucose solution and have your blood drawn one hour later to measure blood sugar levels. If results are high, you\'ll need the more comprehensive three-hour glucose tolerance test.',
      'Catching gestational diabetes early is important because it can be managed with diet, exercise, and sometimes medication to prevent complications for you and your baby.',
    ],
    purpose: [
      'Screen for gestational diabetes',
      'Identify women who need further testing',
      'Assess how body processes glucose during pregnancy',
      'Detect insulin resistance',
      'Prevent complications from unmanaged high blood sugar',
      'Determine need for dietary changes or treatment',
    ],
    howItsPerformed: [
      'One-hour test (screening): Drink 50g glucose solution (very sweet drink)',
      'Wait exactly one hour in clinic',
      'Blood drawn from arm to measure glucose level',
      'No fasting required for screening test',
      'If screening fails, three-hour test performed with fasting',
      'Three-hour test: Fasting blood draw, drink 100g glucose, blood drawn at 1, 2, and 3 hours',
    ],
    whatToExpect: [
      'Glucose drink is very sweet, similar to flat soda',
      'Comes in different flavors (orange, fruit punch, lemon-lime)',
      'Must drink entire bottle within 5 minutes',
      'Some women feel nauseated from sugar rush',
      'May feel shaky or lightheaded',
      'Bring something to do during one-hour wait',
      'Blood draw is standard needle stick in arm',
      'Results usually available within 1-2 days',
    ],
    resultsTimeline: '1-2 days for results',
    normalResults: 'One-hour test: Below 140 mg/dL (some use 130 mg/dL cutoff) - passed, no further testing needed',
    abnormalResults: [
      'One-hour test above 140 mg/dL - need three-hour glucose tolerance test',
      'Failing three-hour test (2 or more elevated values) - diagnosed with gestational diabetes',
      'Requires dietary changes and blood sugar monitoring',
      'May need medication or insulin',
      'Additional monitoring throughout pregnancy',
      'Increased fetal monitoring and possibly earlier delivery',
    ],
    risks: [
      'No physical risks from the test itself',
      'Nausea or vomiting from sweet drink',
      'Feeling lightheaded or shaky from glucose',
      'Normal blood draw risks (bruising, slight pain)',
      'Anxiety about results',
    ],
    preparation: [
      'Screening test: Eat normally, no fasting required',
      'Avoid very high-carb breakfast before screening',
      'Three-hour test: Requires 8-hour overnight fast',
      'Bring snacks for after test (you\'ll be hungry)',
      'Wear short sleeves or easy-access clothing',
      'Bring entertainment for waiting period',
      'Schedule morning appointment if possible',
      'Don\'t exercise heavily before test',
    ],
    relatedTests: ['glucose-tolerance-test', 'hemoglobin-a1c'],
  },
  {
    slug: 'group-b-strep-test',
    title: 'Group B Strep (GBS) Test',
    category: 'screening',
    whenPerformed: 'Weeks 35-37',
    isRoutine: true,
    shortDescription: 'Quick vaginal and rectal swab to test for Group B streptococcus bacteria that could affect baby during delivery.',
    detailedDescription: [
      'Group B streptococcus (GBS) is a common bacteria that about 25% of healthy women carry in their vagina or rectum. While harmless to adults, GBS can cause serious infections in newborns if passed during delivery.',
      'The test involves a simple swab of the vagina and rectum to check for GBS bacteria. If you test positive, you\'ll receive antibiotics during labor to protect your baby. Testing is done late in pregnancy because GBS status can change.',
      'Receiving antibiotics during labor if you\'re GBS positive reduces the risk of infection in your newborn by 80-90%. This is a crucial screening test for all pregnant women.',
    ],
    purpose: [
      'Detect presence of Group B streptococcus bacteria',
      'Identify women who need antibiotics during labor',
      'Prevent GBS infection in newborns',
      'Reduce risk of sepsis, pneumonia, and meningitis in babies',
      'Standard screening for all pregnant women',
    ],
    howItsPerformed: [
      'Simple swab test performed at prenatal visit',
      'Provider or you swab lower vagina',
      'Then swab rectum (outside area)',
      'Takes less than one minute',
      'Sample sent to lab for culture',
      'Results ready in 24-48 hours',
      'Some women prefer to do self-swab for comfort',
    ],
    whatToExpect: [
      'Very quick test, less than a minute',
      'Minimal discomfort',
      'Similar to pap smear but quicker and less invasive',
      'No preparation needed',
      'Can be done at regular prenatal appointment',
      'Results available before delivery',
      'If positive, plan for IV antibiotics during labor',
    ],
    resultsTimeline: '24-48 hours',
    normalResults: 'Negative - no GBS bacteria detected, no antibiotics needed during labor',
    abnormalResults: [
      'Positive - GBS bacteria present (affects 25% of women)',
      'Need IV antibiotics during labor (penicillin or alternative)',
      'Antibiotics given every 4 hours during labor',
      'Baby monitored closely after birth',
      'If antibiotics given for at least 4 hours before delivery, baby\'s risk is very low',
      'Not treated during pregnancy, only during labor',
    ],
    risks: [
      'No risks from the test itself',
      'Slight discomfort from swabbing',
      'If positive: need IV during labor (slight inconvenience)',
      'Rare allergic reaction to antibiotics during labor',
    ],
    preparation: [
      'No special preparation needed',
      'Don\'t douche or use vaginal medications 24 hours before',
      'Routine prenatal appointment',
      'Can schedule as part of regular 36-week visit',
      'Empty bladder before test for comfort',
    ],
    relatedTests: ['cervical-exam', 'urine-culture'],
  },
  {
    slug: 'nipt',
    title: 'NIPT - Non-Invasive Prenatal Testing (Cell-Free DNA)',
    category: 'screening',
    whenPerformed: 'Week 10 or later',
    isRoutine: false,
    shortDescription: 'Blood test analyzing fetal DNA to screen for chromosomal conditions like Down syndrome with high accuracy.',
    detailedDescription: [
      'Non-invasive prenatal testing (NIPT), also called cell-free DNA testing, analyzes tiny fragments of fetal DNA circulating in your blood to screen for chromosomal conditions. It\'s highly accurate for detecting Down syndrome (trisomy 21), Edwards syndrome (trisomy 18), and Patau syndrome (trisomy 13).',
      'This test can be done as early as 10 weeks and only requires a simple blood draw from your arm. It\'s "non-invasive" meaning there\'s no risk to the baby, unlike diagnostic tests like amniocentesis.',
      'NIPT can also reveal your baby\'s sex very early in pregnancy. While it\'s a screening test (not diagnostic), it\'s much more accurate than older screening methods and has largely replaced them for many women.',
    ],
    purpose: [
      'Screen for Down syndrome (trisomy 21) with 99% accuracy',
      'Screen for Edwards syndrome (trisomy 18) and Patau syndrome (trisomy 13)',
      'Detect some sex chromosome abnormalities',
      'Determine baby\'s sex (optional)',
      'Provide reassurance or identify need for diagnostic testing',
      'Risk-free screening available early in pregnancy',
    ],
    howItsPerformed: [
      'Simple blood draw from your arm',
      'Can be done after 10 weeks of pregnancy',
      'Blood contains small fragments of placental DNA',
      'Lab analyzes DNA for chromosomal abnormalities',
      'Takes 1-2 weeks for results',
      'Some tests also check for microdeletions',
      'Sex can be determined from Y chromosome presence',
    ],
    whatToExpect: [
      'Quick blood draw, just like any blood test',
      'No risks to pregnancy',
      'Results in 1-2 weeks (sometimes up to 10 days)',
      'High-risk results warrant follow-up with genetic counselor',
      'May need diagnostic test (amnio) to confirm positive result',
      'Low-risk result is very reassuring',
      'Occasionally test needs to be redrawn (low fetal fraction)',
    ],
    resultsTimeline: '1-2 weeks',
    normalResults: 'Low risk for all conditions tested - very reassuring, no further testing needed',
    abnormalResults: [
      'High risk result means increased chance of condition',
      'NOT a diagnosis - screening test only',
      'Positive result should be confirmed with amniocentesis or CVS',
      'False positives possible (rare but occur)',
      'Meet with genetic counselor to discuss results',
      'Decide if diagnostic testing desired',
      'High-risk result is stressful but not definitive',
    ],
    risks: [
      'No physical risks - just a blood draw',
      'Small risk of inconclusive result (need redraw)',
      'Psychological stress if high-risk result',
      'Rare false positive or false negative',
      'May reveal incidental findings (like maternal chromosomal condition)',
      'Not covered by all insurance, can be expensive',
    ],
    preparation: [
      'No fasting or special preparation required',
      'Must be at least 10 weeks pregnant',
      'Discuss with provider if appropriate for your situation',
      'Understand it\'s screening, not diagnostic',
      'Decide if you want to know sex',
      'Check if insurance covers test (expensive without coverage)',
      'Be prepared for waiting period for results',
    ],
    relatedTests: ['nuchal-translucency', 'quad-screen', 'amniocentesis', 'cvs'],
  },
  {
    slug: 'amniocentesis',
    title: 'Amniocentesis',
    category: 'diagnostic',
    whenPerformed: 'Weeks 15-20 (genetic testing) or later (lung maturity)',
    isRoutine: false,
    shortDescription: 'Diagnostic test using a needle to collect amniotic fluid for genetic testing and chromosomal analysis.',
    detailedDescription: [
      'Amniocentesis is a diagnostic test that involves inserting a thin needle through your abdomen into the amniotic sac to collect a small amount of amniotic fluid. The fluid contains fetal cells that can be analyzed for chromosomal conditions and genetic disorders.',
      'Unlike screening tests, amniocentesis provides definitive answers about genetic conditions like Down syndrome, rather than just risk assessments. It\'s considered the gold standard for genetic diagnosis during pregnancy.',
      'The procedure is typically offered when screening tests show high risk, when there\'s a family history of genetic conditions, or for women over 35. While it carries a small risk of miscarriage, the test provides valuable information that screening tests cannot.',
    ],
    purpose: [
      'Diagnose chromosomal conditions (Down syndrome, trisomy 18, trisomy 13)',
      'Detect genetic disorders (cystic fibrosis, sickle cell, etc.)',
      'Identify neural tube defects via AFP levels',
      'Confirm abnormalities found on ultrasound',
      'Test for lung maturity in third trimester if early delivery needed',
      'Provide definitive diagnosis rather than risk assessment',
    ],
    howItsPerformed: [
      'Ultrasound guides needle placement',
      'Abdomen cleaned with antiseptic',
      'Local anesthetic may or may not be used',
      'Thin needle inserted through abdomen into amniotic sac',
      'About 1-2 tablespoons of fluid withdrawn',
      'Needle removed, bandage applied',
      'Takes about 5-10 minutes for procedure',
      'Rest recommended for 24 hours after',
    ],
    whatToExpect: [
      'Procedure done in doctor\'s office or hospital',
      'Ultrasound throughout to visualize baby and needle',
      'Brief sharp sensation as needle enters',
      'Cramping similar to menstrual cramps common',
      'Spotting or fluid leakage may occur',
      'Rest recommended for remainder of day',
      'Avoid heavy lifting or exercise for 24-48 hours',
      'Results take 1-2 weeks (rapid results available in 2-3 days)',
    ],
    resultsTimeline: 'Rapid results (FISH): 2-3 days for major chromosomal conditions; Full karyotype: 1-2 weeks',
    normalResults: 'Normal number and structure of chromosomes, no genetic abnormalities detected',
    abnormalResults: [
      'Chromosomal abnormality detected (trisomy 21, 18, 13, sex chromosome issues)',
      'Genetic disorder identified',
      'Neural tube defect confirmed',
      'Need to meet with genetic counselor and specialist',
      'Discuss implications and options with healthcare team',
      'Additional testing or monitoring may be recommended',
    ],
    risks: [
      'Miscarriage risk: about 1 in 300-500 (0.2-0.3%)',
      'Infection (very rare)',
      'Needle injury to baby (extremely rare with ultrasound guidance)',
      'Amniotic fluid leakage (usually resolves on its own)',
      'Cramping and discomfort after procedure',
      'Vaginal bleeding or spotting',
      'Rh sensitization if mother is Rh-negative (prevented with RhoGAM)',
    ],
    preparation: [
      'Empty bladder before procedure (unless otherwise instructed)',
      'Bring support person',
      'Plan to rest afterwards',
      'Arrange transportation (shouldn\'t drive immediately after)',
      'Discuss concerns and questions with doctor beforehand',
      'Understand what conditions are being tested for',
      'Consider genetic counseling before and after',
      'Rh-negative women receive RhoGAM shot after procedure',
    ],
    relatedTests: ['nipt', 'cvs', 'quad-screen', 'anatomy-scan'],
  },
  {
    slug: 'nuchal-translucency',
    title: 'Nuchal Translucency Screening (NT Scan)',
    category: 'screening',
    whenPerformed: 'Weeks 11-14',
    isRoutine: false,
    shortDescription: 'First trimester ultrasound measuring fluid at back of baby\'s neck to assess risk for Down syndrome and heart defects.',
    detailedDescription: [
      'The nuchal translucency (NT) scan is a special ultrasound that measures the clear space in the tissue at the back of your baby\'s neck. Babies with chromosomal conditions like Down syndrome tend to have increased fluid in this area during the first trimester.',
      'The NT measurement is combined with blood tests (measuring hCG and PAPP-A) to create the "first trimester combined screening." This screening provides an individual risk assessment for Down syndrome and trisomy 18.',
      'The NT scan must be performed during a specific window (11-14 weeks) by a specially trained technician, as the measurement needs to be very precise. It\'s one of the earlier screening options available.',
    ],
    purpose: [
      'Screen for Down syndrome (trisomy 21)',
      'Screen for trisomy 18 and trisomy 13',
      'Assess risk for heart defects',
      'Detect some other chromosomal abnormalities',
      'Early screening option at 11-14 weeks',
      'Combined with blood work for more accurate assessment',
    ],
    howItsPerformed: [
      'Special ultrasound with precise measurements',
      'Performed by certified sonographer or maternal-fetal medicine specialist',
      'Measures fluid at back of baby\'s neck',
      'Must be done between exactly 11 weeks 0 days and 13 weeks 6 days',
      'Measurement accurate to within 0.1mm',
      'Blood drawn same day for PAPP-A and hCG',
      'Results combined with blood work and maternal age to calculate risk',
    ],
    whatToExpect: [
      'Standard ultrasound on belly',
      'May need full bladder',
      'Baby must be in specific position for accurate measurement',
      'May take longer than regular ultrasound to get right image',
      'Completely painless',
      'Blood draw from arm',
      'Results available in a few days to a week',
      'Risk assessment provided, not diagnosis',
    ],
    resultsTimeline: '3-7 days for combined results',
    normalResults: 'NT measurement under 3mm, combined screening shows low risk (less than 1 in 1000)',
    abnormalResults: [
      'Increased NT measurement (over 3mm)',
      'High-risk screening result (greater than 1 in 250-300)',
      'Offered diagnostic testing (CVS or amniocentesis)',
      'Meeting with genetic counselor recommended',
      'May need additional ultrasounds or fetal echocardiogram',
      'High NT can indicate heart defects even if chromosomes normal',
      'Further testing recommended but not required',
    ],
    risks: [
      'No risks - non-invasive ultrasound',
      'Anxiety from waiting for results',
      'False positive results possible',
      'May lead to unnecessary worry',
      'Some women may choose invasive testing based on results',
    ],
    preparation: [
      'Schedule between 11-14 weeks exactly',
      'May need full bladder for ultrasound',
      'Bring support person if desired',
      'Understand test provides risk assessment, not diagnosis',
      'Consider whether you\'ll pursue diagnostic testing if high risk',
      'Prepare questions for genetic counselor',
    ],
    relatedTests: ['nipt', 'quad-screen', 'cvs', 'amniocentesis'],
  },
  {
    slug: 'quad-screen',
    title: 'Quad Screen (AFP Plus)',
    category: 'screening',
    whenPerformed: 'Weeks 15-22, ideally 16-18 weeks',
    isRoutine: false,
    shortDescription: 'Second trimester blood test measuring four substances to screen for Down syndrome and neural tube defects.',
    detailedDescription: [
      'The quad screen is a second-trimester blood test that measures four substances produced by the baby and placenta: AFP (alpha-fetoprotein), hCG, estriol, and inhibin-A. The levels of these substances, combined with your age and other factors, provide a risk assessment for certain birth defects.',
      'This test can screen for Down syndrome, trisomy 18, and neural tube defects like spina bifida. It\'s been largely replaced by NIPT for chromosomal screening, but it\'s still valuable for detecting neural tube defects, which NIPT cannot screen for.',
      'The quad screen is an older screening option but is still commonly used, especially for women who don\'t opt for first trimester screening or NIPT.',
    ],
    purpose: [
      'Screen for Down syndrome (trisomy 21)',
      'Screen for trisomy 18',
      'Detect neural tube defects (spina bifida, anencephaly)',
      'Screen for abdominal wall defects',
      'Provide risk assessment in second trimester',
      'Alternative or addition to first trimester screening',
    ],
    howItsPerformed: [
      'Simple blood draw from arm',
      'Best performed at 16-18 weeks',
      'Lab measures AFP, hCG, estriol, and inhibin-A levels',
      'Results analyzed along with age, weight, and gestational age',
      'Computer calculates individual risk',
      'Results ready in about 1 week',
    ],
    whatToExpect: [
      'Quick, routine blood draw',
      'No fasting required',
      'Can be done at regular prenatal appointment',
      'Results in about 1 week',
      'Risk assessment provided, not diagnosis',
      'High-risk result may warrant ultrasound or amniocentesis',
      'Low-risk result provides reassurance',
    ],
    resultsTimeline: '1 week',
    normalResults: 'Low risk (less than 1 in 250-300) for all conditions screened',
    abnormalResults: [
      'High risk for Down syndrome (1 in 250 or higher)',
      'Elevated AFP suggesting neural tube defect',
      'High risk for trisomy 18',
      'Need for detailed ultrasound to rule out defects',
      'May be offered amniocentesis for definitive diagnosis',
      'Meet with genetic counselor',
      'Elevated AFP can also indicate twins, incorrect dating, or other issues',
    ],
    risks: [
      'No physical risks - just blood draw',
      'High false-positive rate (5% get abnormal result)',
      'Anxiety from abnormal results',
      'May lead to unnecessary further testing',
      'Many abnormal results turn out to be false alarms',
    ],
    preparation: [
      'No fasting or special preparation',
      'Accurate dating (by early ultrasound) important for interpretation',
      'Schedule between 15-22 weeks',
      'Discuss with provider if appropriate for you',
      'Understand limitations and false-positive rate',
      'Consider if you\'ll pursue further testing if abnormal',
    ],
    relatedTests: ['nipt', 'nuchal-translucency', 'amniocentesis', 'anatomy-scan'],
  },
  {
    slug: 'nonstress-test',
    title: 'Non-Stress Test (NST)',
    category: 'specialized',
    whenPerformed: 'Third trimester, usually after 28 weeks',
    isRoutine: false,
    shortDescription: 'Monitoring test that tracks baby\'s heart rate and movements to assess well-being in late pregnancy.',
    detailedDescription: [
      'A non-stress test (NST) monitors your baby\'s heart rate and movement to ensure your baby is getting enough oxygen and responding normally. It\'s called "non-stress" because nothing is done to stress or challenge the baby - you simply rest while being monitored.',
      'The test looks for accelerations in baby\'s heart rate when baby moves. A healthy baby\'s heart rate speeds up with movement. If the heart rate doesn\'t accelerate appropriately, it may indicate the baby needs further evaluation.',
      'NSTs are often performed weekly or twice weekly in the third trimester for women with certain pregnancy complications or when the pregnancy goes past the due date.',
    ],
    purpose: [
      'Assess baby\'s well-being in late pregnancy',
      'Monitor baby\'s heart rate response to movement',
      'Check that baby is getting adequate oxygen',
      'Surveillance in high-risk pregnancies',
      'Monitor post-dates pregnancies (after 40-41 weeks)',
      'Evaluate decreased fetal movement',
    ],
    howItsPerformed: [
      'Two sensors placed on your belly with elastic belts',
      'One sensor monitors baby\'s heart rate',
      'Second sensor detects contractions',
      'You lie semi-reclined or on left side',
      'Monitoring typically lasts 20-30 minutes',
      'Push button when you feel baby move',
      'May be given juice or snack to encourage movement',
      'Printout shows baby\'s heart rate pattern',
    ],
    whatToExpect: [
      'Rest comfortably in reclining chair or bed',
      'Monitoring is completely painless',
      'May hear baby\'s heartbeat',
      'Baby may or may not be active during test',
      'If baby is sleeping, test may take longer',
      'External vibration may be used to wake baby',
      'Usually takes 20-40 minutes',
      'May need extended monitoring if baby not active',
    ],
    resultsTimeline: 'Immediate - results reviewed right away',
    normalResults: 'Reactive NST: Two or more heart rate accelerations of 15 bpm lasting 15 seconds within 20 minutes. Baby is doing well.',
    abnormalResults: [
      'Non-reactive NST: Insufficient heart rate accelerations',
      'Doesn\'t always mean problem - baby may be sleeping',
      'Extended monitoring or biophysical profile ordered',
      'May need additional testing same day',
      'Rarely indicates need for immediate delivery',
      'Often followed up with ultrasound',
      'May indicate need for closer monitoring',
    ],
    risks: [
      'No risks to mother or baby',
      'Completely non-invasive',
      'Time-consuming appointment',
      'Anxiety if results non-reactive',
      'False positive results possible',
    ],
    preparation: [
      'Eat a meal or snack before test (helps baby be active)',
      'Drink juice before arriving',
      'Bring something to do (book, phone, headphones)',
      'Empty bladder before test',
      'Wear comfortable clothing',
      'Plan for 45-60 minutes at office',
      'Bring partner or support person if desired',
    ],
    relatedTests: ['biophysical-profile', 'contraction-stress-test', 'doppler-ultrasound'],
  },
  {
    slug: 'biophysical-profile',
    title: 'Biophysical Profile (BPP)',
    category: 'specialized',
    whenPerformed: 'Third trimester, usually 32 weeks onward',
    isRoutine: false,
    shortDescription: 'Combined ultrasound and heart rate monitoring to assess baby\'s health and amniotic fluid levels.',
    detailedDescription: [
      'A biophysical profile (BPP) combines an ultrasound with a non-stress test to comprehensively assess your baby\'s well-being. It evaluates five components: fetal heart rate, breathing movements, body movements, muscle tone, and amniotic fluid volume.',
      'Each component is scored as either 2 points (normal) or 0 points (abnormal), with a maximum score of 10. The test provides a snapshot of your baby\'s health and the environment inside the uterus.',
      'BPPs are typically used in high-risk pregnancies, when the pregnancy goes past the due date, or when there are concerns about baby\'s growth or well-being.',
    ],
    purpose: [
      'Assess overall fetal well-being',
      'Monitor high-risk pregnancies',
      'Evaluate post-dates pregnancies',
      'Check amniotic fluid levels',
      'Assess placental function indirectly',
      'Determine if baby should be delivered early',
    ],
    howItsPerformed: [
      'Ultrasound performed for 30 minutes observing baby',
      'NST performed simultaneously or sequentially',
      'Technician observes breathing movements',
      'Counts body and limb movements',
      'Assesses muscle tone (flexion/extension)',
      'Measures amniotic fluid pockets',
      'NST monitors heart rate reactivity',
      'Each component scored 0 or 2',
    ],
    whatToExpect: [
      'Similar to anatomy scan ultrasound',
      'Takes 30-45 minutes total',
      'Monitoring belts on belly for NST portion',
      'Need to observe baby\'s activities',
      'Baby may not cooperate immediately',
      'Completely painless',
      'May receive juice to encourage movement',
      'Results available immediately',
    ],
    resultsTimeline: 'Immediate - scored during the test',
    normalResults: 'Score of 8-10: Baby is doing well, normal result',
    abnormalResults: [
      'Score of 6: Equivocal, may repeat test or deliver',
      'Score of 4 or less: Concerning, may indicate need for delivery',
      'Low amniotic fluid (oligohydramnios) is significant finding',
      'Further testing or immediate delivery may be recommended',
      'Meet with doctor to discuss findings and plan',
      'May indicate placental insufficiency',
    ],
    risks: [
      'No risks - non-invasive',
      'Anxiety if score is low',
      'May lead to unnecessary intervention in some cases',
      'False positive results possible',
    ],
    preparation: [
      'Eat before test to encourage baby activity',
      'Bring something to entertain yourself',
      'Wear comfortable clothing',
      'Allow 45-60 minutes for appointment',
      'May need repeat testing same day if baby not cooperative',
      'Bring partner or support person',
    ],
    relatedTests: ['nonstress-test', 'amniotic-fluid-index', 'doppler-ultrasound'],
  },
  {
    slug: 'cvs',
    title: 'CVS - Chorionic Villus Sampling',
    category: 'diagnostic',
    whenPerformed: 'Weeks 10-13',
    isRoutine: false,
    shortDescription: 'Early diagnostic test collecting placental tissue to test for genetic and chromosomal conditions.',
    detailedDescription: [
      'Chorionic villus sampling (CVS) is a diagnostic test that collects a small sample of placental tissue to test for genetic conditions. Since the placenta develops from the same cells as the baby, it contains the same genetic information.',
      'CVS can be performed earlier than amniocentesis (10-13 weeks vs. 15-20 weeks), allowing for earlier diagnosis of genetic conditions. This earlier timing can be important for families making decisions about the pregnancy.',
      'The procedure can be performed through the abdomen (transabdominal) or through the cervix (transcervical), depending on placenta location. Like amniocentesis, CVS provides definitive genetic diagnosis rather than risk assessment.',
    ],
    purpose: [
      'Diagnose chromosomal conditions (Down syndrome, trisomies)',
      'Test for inherited genetic disorders',
      'Provide early genetic diagnosis (earlier than amnio)',
      'Confirm abnormalities found on ultrasound',
      'Test when family history of genetic condition',
      'Definitive diagnosis by first trimester',
    ],
    howItsPerformed: [
      'Two methods: transcervical (through cervix) or transabdominal (through belly)',
      'Method chosen based on placenta location',
      'Ultrasound guidance throughout procedure',
      'Transcervical: Thin catheter through cervix to placenta',
      'Transabdominal: Needle through abdomen (like amnio)',
      'Small sample of chorionic villi collected',
      'Takes 5-10 minutes',
      'Rest recommended after procedure',
    ],
    whatToExpect: [
      'Procedure performed in office or hospital',
      'Ultrasound used to visualize placenta',
      'Brief discomfort or cramping',
      'Transcervical may feel like pap smear',
      'Transabdominal similar to amniocentesis',
      'Spotting or cramping common after',
      'Rest recommended for 24 hours',
      'Results in 1-2 weeks (rapid results in 2-3 days)',
    ],
    resultsTimeline: 'Rapid results: 2-3 days; Full results: 1-2 weeks',
    normalResults: 'Normal chromosomes, no genetic abnormalities detected',
    abnormalResults: [
      'Chromosomal abnormality detected',
      'Genetic disorder identified',
      'Meet with genetic counselor',
      'Discuss implications and options',
      'Additional testing may be recommended',
      'Rarely, confined placental mosaicism (abnormality only in placenta, not baby)',
    ],
    risks: [
      'Miscarriage risk: about 1 in 200-500 (0.2-0.5%)',
      'Slightly higher risk than amnio',
      'Infection (rare)',
      'Vaginal spotting or bleeding',
      'Cramping after procedure',
      'Amniotic fluid leakage (rare)',
      'Rh sensitization if mother Rh-negative (RhoGAM given)',
    ],
    preparation: [
      'Full bladder may be needed for transabdominal',
      'Bring support person',
      'Arrange transportation',
      'Plan to rest afterwards',
      'Discuss concerns with doctor beforehand',
      'Consider genetic counseling before test',
      'Understand what conditions are being tested',
      'Rh-negative women receive RhoGAM after',
    ],
    relatedTests: ['amniocentesis', 'nipt', 'nuchal-translucency'],
  },
  {
    slug: 'hemoglobin-test',
    title: 'Hemoglobin & Hematocrit Test (Anemia Screening)',
    category: 'blood-test',
    whenPerformed: 'First prenatal visit and again at 24-28 weeks',
    isRoutine: true,
    shortDescription: 'Blood test checking for anemia by measuring red blood cell count and iron levels.',
    detailedDescription: [
      'Hemoglobin and hematocrit tests measure the amount of oxygen-carrying red blood cells in your blood to check for anemia. Anemia is common in pregnancy because your blood volume increases significantly while red blood cell production doesn\'t always keep pace.',
      'Your body needs extra iron during pregnancy to support your increased blood volume and your baby\'s development. Anemia can cause fatigue, weakness, and in severe cases, complications for you and baby.',
      'These tests are performed at your first prenatal visit and repeated in the second or third trimester to check if you\'ve developed anemia as your pregnancy progresses.',
    ],
    purpose: [
      'Screen for anemia (low red blood cell count)',
      'Check iron levels',
      'Monitor maternal health during pregnancy',
      'Identify need for iron supplementation',
      'Prevent complications from severe anemia',
      'Ensure adequate oxygen delivery to baby',
    ],
    howItsPerformed: [
      'Simple blood draw from arm',
      'Usually part of comprehensive prenatal blood panel',
      'Measures hemoglobin (oxygen-carrying protein)',
      'Measures hematocrit (percentage of blood that is red blood cells)',
      'May also test ferritin (iron storage)',
      'Results available in 1-2 days',
    ],
    whatToExpect: [
      'Standard blood draw',
      'No fasting required',
      'Done at first prenatal appointment',
      'Repeated at 24-28 weeks',
      'Quick results',
      'If anemic, iron supplements prescribed',
      'May need dietary counseling',
    ],
    resultsTimeline: '1-2 days',
    normalResults: 'Hemoglobin above 11 g/dL, hematocrit above 33%',
    abnormalResults: [
      'Anemia: Hemoglobin below 11 g/dL (first trimester) or 10.5 g/dL (second/third)',
      'Need for iron supplementation',
      'Dietary changes recommended',
      'Recheck levels in 4-6 weeks',
      'Investigate cause if severe or not improving',
      'May need IV iron in severe cases',
      'Rarely indicates other conditions requiring workup',
    ],
    risks: [
      'No risks beyond standard blood draw',
      'Slight bruising possible',
      'Minimal discomfort',
    ],
    preparation: [
      'No special preparation needed',
      'Part of routine prenatal care',
      'No fasting required',
      'Let doctor know if taking iron supplements',
    ],
    relatedTests: ['complete-blood-count', 'ferritin-test', 'vitamin-b12-folate'],
  },
  {
    slug: 'blood-type-test',
    title: 'Blood Type & Rh Factor Test',
    category: 'blood-test',
    whenPerformed: 'First prenatal visit',
    isRoutine: true,
    shortDescription: 'Blood test determining your blood type and Rh status to prevent complications from Rh incompatibility.',
    detailedDescription: [
      'Blood type and Rh factor testing identifies your blood type (A, B, AB, or O) and whether you\'re Rh positive or Rh negative. This information is crucial because if you\'re Rh negative and your baby is Rh positive, your immune system could create antibodies against your baby\'s blood.',
      'About 15% of people are Rh negative. If you\'re Rh negative, you\'ll receive RhoGAM injections during pregnancy and after delivery to prevent your body from producing antibodies that could harm this or future pregnancies.',
      'This test is done at your first prenatal appointment and the information is critical for your care throughout pregnancy, delivery, and future pregnancies.',
    ],
    purpose: [
      'Determine blood type (A, B, AB, O)',
      'Identify Rh factor (positive or negative)',
      'Prevent Rh incompatibility problems',
      'Plan for RhoGAM if Rh negative',
      'Ensure compatible blood available if transfusion needed',
      'Important for managing pregnancy complications',
    ],
    howItsPerformed: [
      'Simple blood draw from arm',
      'Part of initial prenatal blood panel',
      'Lab determines ABO blood type',
      'Tests for presence of Rh factor (D antigen)',
      'Results available quickly',
      'Antibody screen also performed',
    ],
    whatToExpect: [
      'Standard blood draw at first appointment',
      'Results available same day or next day',
      'If Rh negative, plan for RhoGAM at 28 weeks',
      'RhoGAM also given after delivery if baby is Rh positive',
      'May need RhoGAM after bleeding, amnio, or trauma',
      'Blood type recorded in medical chart',
    ],
    resultsTimeline: 'Same day to 1-2 days',
    normalResults: 'Any blood type is "normal" - results just inform your care plan',
    abnormalResults: [
      'Rh negative status requires RhoGAM shots',
      'Positive antibody screen indicates sensitization (serious)',
      'Need for special monitoring if antibodies present',
      'More frequent ultrasounds to check baby',
      'Possible need for early delivery or intrauterine transfusion',
      'Previous sensitization complicates current pregnancy',
    ],
    risks: [
      'No risks from test itself',
      'Standard blood draw',
      'If Rh negative, need injections (RhoGAM) but this prevents problems',
    ],
    preparation: [
      'No preparation needed',
      'Routine part of first prenatal visit',
      'Important to know for entire pregnancy',
      'Previous pregnancy history matters if Rh negative',
    ],
    relatedTests: ['antibody-screen', 'hemoglobin-test'],
  },
  {
    slug: 'urine-test',
    title: 'Urine Test (Urinalysis)',
    category: 'routine',
    whenPerformed: 'Every prenatal visit',
    isRoutine: true,
    shortDescription: 'Routine urine test at each appointment checking for protein, glucose, bacteria, and infection.',
    detailedDescription: [
      'A urine sample is checked at every prenatal appointment to screen for various pregnancy complications and infections. The test looks for protein (sign of preeclampsia), glucose (sign of gestational diabetes), and bacteria (sign of infection).',
      'You\'ll provide a urine sample in a cup at each appointment - it\'s a quick, non-invasive way to monitor for several important conditions. The test can catch problems early before you have symptoms.',
      'Urinary tract infections (UTIs) are common in pregnancy and need to be treated promptly. Protein in urine can be an early warning sign of preeclampsia, a serious pregnancy complication.',
    ],
    purpose: [
      'Screen for urinary tract infections',
      'Detect protein (sign of preeclampsia)',
      'Check for glucose (gestational diabetes screening)',
      'Monitor kidney function',
      'Detect bacteria or white blood cells',
      'Screen for dehydration',
    ],
    howItsPerformed: [
      'Provide urine sample in sterile cup',
      'Clean-catch midstream sample preferred',
      'Dipstick test performed immediately',
      'Checks protein, glucose, ketones, blood, leukocytes, nitrites',
      'Takes less than a minute',
      'Results available immediately',
      'If abnormal, may send sample to lab',
    ],
    whatToExpect: [
      'Done at every prenatal visit',
      'Quick and easy',
      'Results reviewed immediately',
      'Abnormal results may require follow-up testing',
      'If infection found, antibiotics prescribed',
      'If protein found, blood pressure monitored closely',
    ],
    resultsTimeline: 'Immediate',
    normalResults: 'Negative for protein, glucose, bacteria, blood, ketones',
    abnormalResults: [
      'Protein in urine: Possible preeclampsia, needs immediate evaluation',
      'Glucose in urine: May indicate gestational diabetes',
      'Bacteria/leukocytes/nitrites: Urinary tract infection, needs antibiotics',
      'Ketones: Possible dehydration or inadequate nutrition',
      'Blood in urine: May indicate infection or kidney stones',
      'Follow-up testing required for any abnormality',
    ],
    risks: [
      'No risks whatsoever',
      'Completely non-invasive',
      'Simple urine collection',
    ],
    preparation: [
      'Empty bladder fully',
      'Clean-catch method: wipe front to back, catch midstream',
      'Don\'t need to fast',
      'Stay hydrated',
    ],
    relatedTests: ['urine-culture', 'protein-urine-24-hour', 'glucose-test'],
  },
  {
    slug: 'thyroid-test',
    title: 'Thyroid Function Test (TSH)',
    category: 'blood-test',
    whenPerformed: 'First prenatal visit, repeated if abnormal',
    isRoutine: false,
    shortDescription: 'Blood test checking thyroid hormone levels to ensure proper thyroid function during pregnancy.',
    detailedDescription: [
      'Thyroid function testing measures TSH (thyroid stimulating hormone) and sometimes T4 to check if your thyroid is working properly. The thyroid gland controls metabolism, and thyroid problems are more common in pregnant women.',
      'Both hypothyroidism (underactive thyroid) and hyperthyroidism (overactive thyroid) can affect pregnancy and baby\'s development. Untreated thyroid problems can lead to miscarriage, preterm birth, or developmental issues.',
      'Women with known thyroid conditions are tested regularly during pregnancy. Those without prior thyroid problems may be tested if they have symptoms or risk factors.',
    ],
    purpose: [
      'Screen for hypothyroidism (underactive thyroid)',
      'Screen for hyperthyroidism (overactive thyroid)',
      'Monitor thyroid levels in women with known thyroid disease',
      'Ensure adequate thyroid hormone for baby\'s brain development',
      'Prevent pregnancy complications from thyroid problems',
    ],
    howItsPerformed: [
      'Simple blood draw from arm',
      'Measures TSH (primary test)',
      'May also measure T4, T3, or thyroid antibodies',
      'No fasting required',
      'Results in 1-3 days',
      'Repeated periodically if abnormal',
    ],
    whatToExpect: [
      'Standard blood test',
      'Usually part of first prenatal panel',
      'Quick results',
      'If abnormal, medication prescribed',
      'Regular monitoring if on thyroid medication',
      'Dose adjustments common during pregnancy',
    ],
    resultsTimeline: '1-3 days',
    normalResults: 'TSH 0.5-2.5 in first trimester, 0.5-3.0 in second/third trimester (ranges vary slightly)',
    abnormalResults: [
      'High TSH: Hypothyroidism, need thyroid hormone replacement',
      'Low TSH: Hyperthyroidism, may need medication to reduce thyroid',
      'Untreated thyroid problems affect baby\'s development',
      'Need medication adjustment and regular monitoring',
      'Endocrinologist consultation may be needed',
      'Recheck thyroid levels every 4-6 weeks',
    ],
    risks: [
      'No risks from test - standard blood draw',
    ],
    preparation: [
      'No fasting needed',
      'If on thyroid medication, take as prescribed',
      'Inform doctor of any thyroid history',
      'Let provider know about family history',
    ],
    relatedTests: ['t4-test', 'thyroid-antibodies'],
  },
  {
    slug: 'growth-scan',
    title: 'Growth Scan (Third Trimester Ultrasound)',
    category: 'ultrasound',
    whenPerformed: 'Third trimester (28+ weeks), frequency varies',
    isRoutine: false,
    shortDescription: 'Ultrasound measuring baby\'s size and growth to ensure appropriate development in late pregnancy.',
    detailedDescription: [
      'Growth scans are ultrasounds performed in the third trimester to measure your baby\'s size and ensure they\'re growing appropriately. The technician measures baby\'s head, abdomen, and thigh bone to estimate weight and percentile.',
      'Not all women receive routine growth scans, but they\'re common for high-risk pregnancies, suspected growth problems, gestational diabetes, or when the fundal height measurement is concerning.',
      'These scans help identify babies who are too small (growth restriction) or too large (macrosomia), both of which can affect delivery planning and need monitoring.',
    ],
    purpose: [
      'Monitor baby\'s growth and size',
      'Estimate fetal weight',
      'Detect growth restriction (baby too small)',
      'Detect macrosomia (baby too large)',
      'Check amniotic fluid levels',
      'Assess placental function indirectly',
    ],
    howItsPerformed: [
      'Standard abdominal ultrasound',
      'Measures head circumference, abdominal circumference, femur length',
      'Computer calculates estimated fetal weight',
      'Compares measurements to growth charts',
      'Determines percentile',
      'Checks amniotic fluid volume',
      'Takes 15-30 minutes',
    ],
    whatToExpect: [
      'Similar to anatomy scan',
      'Can see baby\'s features clearly',
      'May see baby practicing breathing, moving',
      'Photos provided',
      'Estimated weight calculated (within 10-15% accuracy)',
      'Results discussed immediately',
      'Follow-up scans if concerns',
    ],
    resultsTimeline: 'Immediate preliminary results, official report within 1-2 days',
    normalResults: 'Baby growing along consistent percentile (10th-90th percentile), normal fluid levels',
    abnormalResults: [
      'Growth restriction (below 10th percentile)',
      'Macrosomia (above 90th percentile, estimated weight over 9 lbs)',
      'Slowing growth velocity',
      'Low or high amniotic fluid',
      'May need more frequent monitoring',
      'Possible early delivery if severe restriction',
      'Consider induction if baby very large',
    ],
    risks: [
      'No risks - ultrasound is safe',
      'Anxiety from measurements',
      'Weight estimates can be inaccurate (10-15% margin of error)',
      'May lead to unnecessary intervention based on estimates',
    ],
    preparation: [
      'No special preparation',
      'Don\'t need full bladder in third trimester',
      'Bring support person',
      'Discuss concerns with provider',
    ],
    relatedTests: ['anatomy-scan', 'biophysical-profile', 'doppler-ultrasound'],
  },
  {
    slug: 'fetal-echocardiogram',
    title: 'Fetal Echocardiogram',
    category: 'specialized',
    whenPerformed: 'Weeks 18-24',
    isRoutine: false,
    shortDescription: 'Specialized ultrasound examining baby\'s heart structure and function in detail.',
    detailedDescription: [
      'A fetal echocardiogram is a detailed ultrasound specifically examining your baby\'s heart. It\'s performed by a pediatric cardiologist or specially trained technician and provides much more detailed images of the heart than a standard anatomy scan.',
      'This test is recommended when there\'s increased risk of heart defects - such as family history, abnormal anatomy scan, maternal diabetes, or certain medications. Congenital heart defects are the most common birth defect.',
      'The fetal echo can detect structural heart problems, abnormal heart rhythms, and issues with heart function, allowing for planning of delivery and immediate care after birth.',
    ],
    purpose: [
      'Detailed examination of heart structure',
      'Detect congenital heart defects',
      'Assess heart function',
      'Check heart rhythm',
      'Evaluate blood flow through heart chambers and vessels',
      'Plan for delivery and newborn care if heart defect found',
    ],
    howItsPerformed: [
      'Specialized ultrasound, similar to anatomy scan',
      'Takes 45-60 minutes (longer than standard ultrasound)',
      'Multiple views and measurements of heart',
      'Doppler used to assess blood flow',
      'Color flow imaging shows blood movement',
      'Performed by pediatric cardiologist or specialist',
      'Very detailed and technical',
    ],
    whatToExpect: [
      'Longer appointment (1-2 hours total)',
      'Similar to regular ultrasound',
      'Focused on heart only',
      'Very detailed examination',
      'May be referred to maternal-fetal medicine center',
      'Cardiologist discusses findings',
      'If abnormality found, plan for delivery at hospital with cardiac care',
    ],
    resultsTimeline: 'Same day discussion, official report in 1-2 days',
    normalResults: 'Normal four-chamber heart, normal valves, normal blood flow, regular rhythm',
    abnormalResults: [
      'Congenital heart defect detected',
      'Abnormal heart rhythm',
      'Abnormal blood flow or valve function',
      'May need delivery at specialized hospital',
      'Pediatric cardiac surgery may be needed after birth',
      'Genetic counseling recommended',
      'May need additional testing (amnio, fetal MRI)',
      'Prognosis varies greatly depending on specific defect',
    ],
    risks: [
      'No risks - non-invasive ultrasound',
      'Anxiety about findings',
      'Potential for detecting minor findings that resolve',
    ],
    preparation: [
      'Referral from OB usually required',
      'Bring medical records',
      'Allow 2+ hours for appointment',
      'Bring support person',
      'Prepare questions for cardiologist',
      'Understand that detection allows for planning, even if stressful',
    ],
    relatedTests: ['anatomy-scan', 'nuchal-translucency', 'nipt'],
  },
  {
    slug: 'cervical-length-scan',
    title: 'Cervical Length Scan',
    category: 'ultrasound',
    whenPerformed: 'Weeks 18-24, may be repeated',
    isRoutine: false,
    shortDescription: 'Transvaginal ultrasound measuring cervix length to assess preterm birth risk.',
    detailedDescription: [
      'A cervical length scan uses transvaginal ultrasound to measure the length of your cervix. A short cervix can indicate increased risk of preterm labor and delivery.',
      'The cervix should remain long and closed during pregnancy. If it starts to shorten too early, it may not stay closed until term. This is called cervical insufficiency.',
      'This scan is typically done for women with history of preterm birth, previous cervical surgery, or unexplained pregnancy loss. If cervix is short, interventions like progesterone or cerclage may prevent preterm birth.',
    ],
    purpose: [
      'Assess risk of preterm birth',
      'Detect cervical insufficiency',
      'Monitor women with history of preterm labor',
      'Determine need for interventions (progesterone, cerclage)',
      'Identify women who need closer monitoring',
    ],
    howItsPerformed: [
      'Transvaginal ultrasound (probe inserted in vagina)',
      'Empty bladder before scan',
      'Measures cervix length in millimeters',
      'Checks if cervix is opening (funneling)',
      'Takes 5-10 minutes',
      'May be repeated every 2-4 weeks',
      'Performed by trained sonographer',
    ],
    whatToExpect: [
      'Similar to early pregnancy ultrasound',
      'Transvaginal probe inserted gently',
      'Painless but may be slightly uncomfortable',
      'Very quick scan',
      'Immediate results',
      'If short, discuss treatment options',
      'May need serial scans to monitor',
    ],
    resultsTimeline: 'Immediate',
    normalResults: 'Cervical length 30mm or longer at mid-pregnancy',
    abnormalResults: [
      'Short cervix (less than 25mm at 18-24 weeks)',
      'Funneling (cervix opening from inside)',
      'Need for progesterone supplementation',
      'May need cerclage (cervical stitch)',
      'Activity restriction or modified bed rest',
      'Increased risk of preterm delivery',
      'Need for closer monitoring and follow-up scans',
    ],
    risks: [
      'No risks - safe transvaginal ultrasound',
      'Slight discomfort from probe',
      'Anxiety about results',
    ],
    preparation: [
      'Empty bladder completely before scan',
      'No other special preparation',
      'Quick appointment',
      'Discuss risk factors with provider beforehand',
    ],
    relatedTests: ['cervical-exam', 'fetal-fibronectin-test'],
  },
  {
    slug: 'std-screening',
    title: 'STD/STI Screening Panel',
    category: 'screening',
    whenPerformed: 'First prenatal visit, sometimes repeated third trimester',
    isRoutine: true,
    shortDescription: 'Blood and urine tests screening for sexually transmitted infections that can affect pregnancy.',
    detailedDescription: [
      'STD screening is a routine part of prenatal care because many sexually transmitted infections can affect pregnancy and be passed to baby. Even if you\'ve been in a monogamous relationship, screening is recommended as some infections can be dormant for years.',
      'Testing typically includes HIV, syphilis, hepatitis B, chlamydia, and gonorrhea. Some providers also test for hepatitis C. Many of these infections have no symptoms but can seriously harm your baby if untreated.',
      'Early detection and treatment of STDs during pregnancy can prevent transmission to baby and reduce complications. Most infections can be safely treated during pregnancy.',
    ],
    purpose: [
      'Screen for HIV, syphilis, hepatitis B',
      'Test for chlamydia and gonorrhea',
      'Prevent transmission to baby',
      'Allow treatment during pregnancy',
      'Reduce risk of pregnancy complications',
      'Ensure healthy pregnancy and delivery',
    ],
    howItsPerformed: [
      'Blood draw tests for HIV, syphilis, hepatitis B, sometimes hepatitis C',
      'Urine sample or vaginal/cervical swab for chlamydia and gonorrhea',
      'Part of comprehensive first prenatal panel',
      'Results in 3-7 days',
      'High-risk women may be retested third trimester',
      'Confidential results',
    ],
    whatToExpect: [
      'Standard blood draw and urine/swab collection',
      'Part of routine prenatal care',
      'Results discussed at next appointment or by phone',
      'If positive, treatment started immediately',
      'Partner treatment also necessary',
      'Follow-up testing to confirm cure',
      'Third trimester repeat for high-risk women',
    ],
    resultsTimeline: '3-7 days',
    normalResults: 'Negative for all infections tested',
    abnormalResults: [
      'Positive result requires immediate treatment',
      'HIV: Start antiretroviral therapy, plan for special delivery precautions',
      'Syphilis: Penicillin treatment, can cure with early treatment',
      'Hepatitis B: Baby receives vaccine and immunoglobulin at birth',
      'Chlamydia/Gonorrhea: Antibiotics safe in pregnancy',
      'Partner must be treated',
      'Repeat testing after treatment',
      'Additional monitoring during pregnancy',
    ],
    risks: [
      'No risks from testing',
      'Standard blood draw and urine/swab',
      'Psychological stress if positive result',
      'Stigma concerns (all testing is confidential)',
    ],
    preparation: [
      'No special preparation',
      'Part of first prenatal visit',
      'Important regardless of relationship status',
      'Honest discussion with provider about risk factors',
    ],
    relatedTests: ['urine-test', 'blood-type-test', 'hepatitis-c-test'],
  },
]

export function getMedicalTestData(slug: string): MedicalTestData | undefined {
  return medicalTestsData.find((test) => test.slug === slug)
}

export function getTestsByCategory(category: string): MedicalTestData[] {
  return medicalTestsData.filter((test) => test.category === category)
}

export function getRoutineTests(): MedicalTestData[] {
  return medicalTestsData.filter((test) => test.isRoutine)
}
