// Pregnancy nutrition data

export interface NutritionData {
  slug: string
  title: string
  category: 'vitamins' | 'foods' | 'nutrients' | 'safety' | 'diet-plans'
  shortDescription: string
  detailedDescription: string[]
  keyBenefits: string[]
  recommendedIntake: string
  bestSources: string[]
  importantConsiderations: string[]
  whenToTalk: string[]
  relatedTopics: string[]
  trimesterInfo: { first: string; second: string; third: string }
}

export const nutritionData: NutritionData[] = [
  {
    slug: 'prenatal-vitamins',
    title: 'Prenatal Vitamins',
    category: 'vitamins',
    shortDescription: 'Essential vitamin and mineral supplements designed specifically for pregnancy. Help fill nutritional gaps and support baby\'s development.',
    detailedDescription: [
      'Prenatal vitamins are specially formulated multivitamins designed to meet the increased nutritional demands of pregnancy. They contain higher amounts of certain nutrients that are crucial for fetal development and maternal health.',
      'While a healthy diet is the foundation of good nutrition during pregnancy, prenatal vitamins act as an insurance policy to ensure you and your baby get all the essential nutrients needed for optimal growth and development.',
      'Ideally, you should start taking prenatal vitamins at least 3 months before trying to conceive, as many critical developmental processes occur in the very early weeks of pregnancy before you even know you\'re pregnant.',
    ],
    keyBenefits: [
      'Provides 400-800 mcg of folic acid to prevent neural tube defects',
      'Supplies 27mg of iron to support increased blood volume and prevent anemia',
      'Contains calcium for baby\'s bone development',
      'Includes vitamin D for calcium absorption and immune function',
      'Provides DHA (omega-3) for brain and eye development in many formulations',
      'Ensures adequate B vitamins for energy metabolism',
      'Helps fill nutritional gaps when food aversions limit diet variety',
    ],
    recommendedIntake: 'One prenatal vitamin daily, preferably taken with food to enhance absorption and reduce nausea. Start ideally 3 months before conception.',
    bestSources: [
      'Prescription prenatal vitamins (often covered by insurance, higher quality control)',
      'Over-the-counter prenatal vitamins (choose reputable brands with third-party testing)',
      'Look for USP, NSF, or ConsumerLab certification on the label',
      'Gummy vitamins (easier to take if nausea is severe, but often lack iron)',
      'Whole food-based prenatals (derived from concentrated foods, gentler on stomach)',
      'Liquid prenatal vitamins (alternative for those who can\'t swallow pills)',
    ],
    importantConsiderations: [
      'Don\'t take prenatal vitamins on an empty stomach if they cause nausea - try at bedtime or with meals',
      'Iron can cause constipation - increase fiber and water intake, or ask about slow-release formulas',
      'Gummy prenatals often lack iron and have less folic acid - may need separate supplements',
      'Never exceed the recommended dose - more is not better and can be harmful',
      'Store prenatals away from children as iron overdose can be fatal',
      'If taking separate supplements, inform your healthcare provider to avoid excessive intake',
      'Dark or greenish stool is normal when taking iron supplements',
      'Some women need prescription-strength prenatal vitamins due to medical conditions',
    ],
    whenToTalk: [
      'You have trouble swallowing pills or keeping prenatal vitamins down',
      'You experience severe constipation from iron in prenatal vitamins',
      'You have a medical condition (like anemia) requiring additional supplementation',
      'You follow a vegetarian or vegan diet and need B12 guidance',
      'You\'re pregnant with multiples and need higher nutrient doses',
      'You\'re experiencing symptoms of vitamin deficiency (fatigue, weakness, dizziness)',
      'You want guidance on which prenatal vitamin brand is best for your needs',
    ],
    relatedTopics: ['folic-acid', 'iron-rich-foods', 'calcium-needs', 'foods-to-avoid'],
    trimesterInfo: {
      first: 'Most critical period for taking prenatal vitamins. Folic acid in the first trimester prevents neural tube defects. Morning sickness may make it hard to keep vitamins down - try taking at bedtime or with food.',
      second: 'Continue prenatal vitamins daily. Iron needs increase to support expanding blood volume. You may tolerate vitamins better as nausea subsides.',
      third: 'Maintain prenatal vitamin routine through delivery. Baby is rapidly developing brain and storing iron for after birth. Some providers add extra vitamin D or iron if levels are low.',
    },
  },
  {
    slug: 'folic-acid',
    title: 'Folic Acid (Folate)',
    category: 'vitamins',
    shortDescription: 'A B vitamin crucial for preventing neural tube defects and supporting rapid cell division during pregnancy. Most important in the first trimester.',
    detailedDescription: [
      'Folic acid is the synthetic form of folate, a B vitamin that plays a critical role in cell division and DNA synthesis. During pregnancy, it\'s essential for the proper development of your baby\'s neural tube, which becomes the brain and spinal cord.',
      'Neural tube defects like spina bifida occur in the first 28 days of pregnancy - often before you even know you\'re pregnant. This is why it\'s crucial to have adequate folic acid levels before conception and during early pregnancy.',
      'Getting enough folic acid can reduce the risk of neural tube defects by up to 70%. It also helps prevent other birth defects, supports placenta development, and may reduce the risk of preeclampsia and premature birth.',
    ],
    keyBenefits: [
      'Reduces neural tube defect risk by up to 70% when taken before and during early pregnancy',
      'Supports rapid cell growth and division throughout pregnancy',
      'Helps produce red blood cells and prevents anemia',
      'Aids in DNA and RNA synthesis for baby\'s development',
      'May reduce risk of heart defects, cleft lip/palate, and preterm birth',
      'Supports placenta development and function',
      'Helps prevent maternal anemia during pregnancy',
    ],
    recommendedIntake: '400-800 mcg daily for most women. Women with history of neural tube defects may need 4000 mcg (4mg) daily as prescribed by their doctor.',
    bestSources: [
      'Prenatal vitamins (most reliable source of adequate folic acid)',
      'Fortified breakfast cereals (check labels - some provide 100% daily value)',
      'Dark leafy greens like spinach and kale (100 mcg per 1/2 cup cooked)',
      'Lentils and beans (180 mcg per 1/2 cup cooked)',
      'Asparagus (134 mcg per 4 spears)',
      'Broccoli (52 mcg per 1/2 cup cooked)',
      'Avocado (90 mcg per 1/2 avocado)',
      'Fortified breads and pasta',
      'Orange juice (35 mcg per 3/4 cup)',
      'Enriched rice and grains',
    ],
    importantConsiderations: [
      'Start taking folic acid at least 3 months before trying to conceive',
      'Food sources alone typically don\'t provide enough - supplementation is recommended',
      'Folic acid (synthetic) is better absorbed than natural folate from foods',
      'Some genetic variations (MTHFR gene mutation) may require methylfolate instead',
      'Continue taking throughout pregnancy, not just the first trimester',
      'Don\'t exceed 1000 mcg daily unless prescribed by your doctor',
      'Alcohol and certain medications can interfere with folate absorption',
    ],
    whenToTalk: [
      'You have a family or personal history of neural tube defects',
      'You take anti-seizure medications that interfere with folate',
      'You have been diagnosed with MTHFR gene mutation',
      'You have had a previous pregnancy affected by neural tube defects',
      'You have a malabsorption disorder like celiac disease or Crohn\'s disease',
      'You\'re pregnant with twins or multiples and need guidance on dosage',
    ],
    relatedTopics: ['prenatal-vitamins', 'foods-to-avoid', 'iron-rich-foods'],
    trimesterInfo: {
      first: 'MOST CRITICAL period for folic acid. Neural tube closes by day 28 of pregnancy. Take 400-800 mcg daily. This is why preconception supplementation is so important.',
      second: 'Continue folic acid for ongoing cell division and red blood cell production. Your baby is rapidly growing and needs continued folate support.',
      third: 'Maintain folic acid intake through delivery. Supports baby\'s continued brain development and helps prevent maternal anemia.',
    },
  },
  {
    slug: 'iron-rich-foods',
    title: 'Iron-Rich Foods',
    category: 'nutrients',
    shortDescription: 'Foods high in iron to support increased blood volume during pregnancy and prevent anemia. Essential for oxygen transport to your baby.',
    detailedDescription: [
      'Iron is a crucial mineral during pregnancy because your blood volume increases by about 50% to support your growing baby. Your body needs iron to make hemoglobin, the protein in red blood cells that carries oxygen to your tissues and your baby.',
      'Pregnant women need 27mg of iron per day - almost double the amount needed before pregnancy. Iron deficiency anemia is one of the most common pregnancy complications, affecting about 15-25% of pregnant women.',
      'There are two types of dietary iron: heme iron (from animal sources) which is more easily absorbed, and non-heme iron (from plant sources) which requires vitamin C for optimal absorption.',
    ],
    keyBenefits: [
      'Supports 50% increase in blood volume during pregnancy',
      'Delivers oxygen to baby through the placenta',
      'Prevents iron deficiency anemia which causes fatigue and weakness',
      'Supports baby\'s brain development and growth',
      'Helps baby build iron stores for first 6 months of life',
      'Reduces risk of preterm delivery and low birth weight',
      'Supports your energy levels throughout pregnancy',
    ],
    recommendedIntake: '27mg of iron daily during pregnancy. Many prenatal vitamins contain this amount, but food sources help meet needs too.',
    bestSources: [
      'Lean red meat like beef (3.5mg per 3oz) - best source of heme iron',
      'Poultry like chicken and turkey (1mg per 3oz dark meat)',
      'Pork (0.8mg per 3oz)',
      'Fortified breakfast cereals (up to 18mg per serving - check labels)',
      'Beans and lentils (3mg per 1/2 cup cooked)',
      'Spinach and other dark leafy greens (3mg per 1/2 cup cooked)',
      'Tofu (3mg per 1/2 cup)',
      'Blackstrap molasses (1 tablespoon = 3.5mg)',
      'Dried fruits like apricots and raisins',
      'Quinoa (1.5mg per 1/2 cup cooked)',
      'Pumpkin seeds (4mg per 1oz)',
      'Enriched breads and pasta',
    ],
    importantConsiderations: [
      'Pair plant-based iron sources with vitamin C (citrus, tomatoes, peppers) for better absorption',
      'Don\'t drink tea or coffee with iron-rich meals - tannins block absorption',
      'Calcium supplements can interfere with iron absorption - take them at different times',
      'Cook in cast iron cookware to increase iron content of foods',
      'Iron from meat is absorbed 2-3 times better than iron from plants',
      'Prenatal vitamin iron can cause constipation - increase fiber and fluids',
      'Some women need additional iron supplements beyond prenatal vitamins if anemic',
      'Iron needs continue through breastfeeding but at slightly lower levels',
    ],
    whenToTalk: [
      'You feel constantly tired, weak, or dizzy despite adequate rest',
      'You have pale skin, shortness of breath, or rapid heartbeat',
      'You have a history of anemia or heavy menstrual periods before pregnancy',
      'Your blood tests show low iron levels or anemia',
      'You follow a vegetarian or vegan diet',
      'You\'re experiencing severe constipation from prenatal vitamins',
      'You\'re pregnant with multiples and need higher iron intake',
    ],
    relatedTopics: ['prenatal-vitamins', 'foods-to-avoid', 'protein-intake'],
    trimesterInfo: {
      first: 'Iron needs are slightly lower in early pregnancy but still important. Start building your iron stores. Morning sickness may make it hard to eat iron-rich foods.',
      second: 'Iron needs increase as blood volume expands rapidly. This is when anemia often develops if iron intake is inadequate. Get screened for anemia at prenatal visits.',
      third: 'Highest iron needs occur in the third trimester. Your baby is storing iron for the first 6 months of life. Continue iron-rich foods and supplements through delivery.',
    },
  },
  {
    slug: 'calcium-needs',
    title: 'Calcium During Pregnancy',
    category: 'nutrients',
    shortDescription: 'Essential mineral for building your baby\'s bones and teeth. Pregnant women need 1000mg daily to support fetal development.',
    detailedDescription: [
      'Calcium is the most abundant mineral in the body and is critical for developing your baby\'s bones, teeth, heart, nerves, and muscles. If you don\'t get enough calcium from your diet, your body will take it from your bones to give to your baby.',
      'Most women don\'t get enough calcium even before pregnancy. During pregnancy, your body adapts by absorbing calcium more efficiently, but adequate intake is still essential to protect your bone health and support your baby\'s development.',
      'The good news is that your body prioritizes your baby\'s calcium needs, so your baby will develop normally even if your calcium intake is low - but this comes at the expense of your own bone density.',
    ],
    keyBenefits: [
      'Builds baby\'s bones, teeth, heart, nerves, and muscles',
      'Protects your bone density during and after pregnancy',
      'Helps blood clot normally',
      'Supports proper muscle and nerve function for both you and baby',
      'May reduce risk of pregnancy-induced hypertension and preeclampsia',
      'Helps regulate heart rhythm',
      'Essential for baby\'s skeletal development throughout pregnancy',
    ],
    recommendedIntake: '1000mg daily for pregnant women ages 19-50. Teenagers (14-18) need 1300mg daily during pregnancy.',
    bestSources: [
      'Milk - dairy or fortified plant-based (300mg per 8oz glass)',
      'Yogurt (450mg per 8oz)',
      'Cheese - cheddar, mozzarella, Swiss (200-300mg per 1oz)',
      'Fortified orange juice (300mg per 8oz)',
      'Fortified breakfast cereals (100-1000mg per serving - check labels)',
      'Tofu made with calcium sulfate (400mg per 1/2 cup)',
      'Salmon with bones (180mg per 3oz)',
      'Dark leafy greens like collards and kale (100-150mg per 1/2 cup cooked)',
      'White beans (80mg per 1/2 cup)',
      'Almonds (75mg per 1oz)',
      'Fortified almond, soy, or oat milk (300mg per 8oz)',
      'Chia seeds (180mg per 1oz)',
    ],
    importantConsiderations: [
      'Vitamin D is necessary for calcium absorption - make sure you\'re getting enough',
      'Your body can only absorb about 500mg of calcium at once - spread intake throughout the day',
      'Calcium supplements can cause constipation - get calcium from food when possible',
      'Don\'t take calcium supplements at the same time as iron supplements - they compete for absorption',
      'If lactose intolerant, try lactose-free dairy or fortified plant milks',
      'Oxalates in spinach bind calcium making it less bioavailable - choose other leafy greens',
      'Most prenatal vitamins contain only 150-300mg calcium - you need food sources too',
      'Excessive caffeine and sodium can increase calcium loss through urine',
    ],
    whenToTalk: [
      'You have lactose intolerance or dairy allergy and need alternative sources',
      'You follow a vegan diet and need guidance on plant-based calcium',
      'You have a history of kidney stones',
      'You\'re taking medications that interfere with calcium absorption',
      'You have a family history of osteoporosis',
      'You\'re pregnant with multiples and need higher calcium intake',
      'You experience leg cramps (though not always calcium-related)',
    ],
    relatedTopics: ['prenatal-vitamins', 'protein-intake', 'foods-to-avoid'],
    trimesterInfo: {
      first: 'Begin establishing good calcium habits. Baby\'s bones begin forming. Your body starts absorbing calcium more efficiently. Aim for 3-4 servings of calcium-rich foods daily.',
      second: 'Baby\'s skeleton is rapidly hardening and accumulating calcium. Continue 1000mg daily. If you have aversions to dairy, find alternative calcium sources.',
      third: 'Peak calcium transfer to baby occurs in the third trimester. Baby\'s bones are storing calcium for after birth. Maintain adequate intake to protect your bone health.',
    },
  },
  {
    slug: 'protein-intake',
    title: 'Protein During Pregnancy',
    category: 'nutrients',
    shortDescription: 'Essential macronutrient for building baby\'s tissues, organs, and supporting your body\'s changes. Pregnant women need about 71 grams daily.',
    detailedDescription: [
      'Protein is made up of amino acids - the building blocks your body uses to create new tissues, including your baby\'s organs, muscles, and skin. During pregnancy, you need extra protein to support your baby\'s growth and your body\'s changes.',
      'Protein requirements increase by about 25 grams per day during pregnancy. This extra protein supports the development of the placenta, increases your blood volume, grows the uterus, and builds your baby\'s tissues.',
      'Most women in developed countries easily meet or exceed protein needs, but vegetarians, vegans, and women with severe morning sickness or food aversions may need to make a conscious effort to get enough.',
    ],
    keyBenefits: [
      'Builds baby\'s organs, muscles, skin, and all body tissues',
      'Supports placenta development and function',
      'Helps increase maternal blood volume',
      'Supports breast and uterine tissue growth',
      'Provides energy and helps stabilize blood sugar',
      'Supports immune function for both mother and baby',
      'Helps maintain your muscle mass during pregnancy',
      'May reduce risk of low birth weight',
    ],
    recommendedIntake: '71 grams of protein daily during pregnancy (about 25g more than before pregnancy). This equals roughly 3-4 servings of protein-rich foods per day.',
    bestSources: [
      'Chicken breast (26g per 3oz)',
      'Lean beef (25g per 3oz)',
      'Fish like salmon (22g per 3oz - choose low-mercury options)',
      'Eggs (6g per large egg)',
      'Greek yogurt (17g per 6oz)',
      'Cottage cheese (14g per 1/2 cup)',
      'Lentils (9g per 1/2 cup cooked)',
      'Black beans (8g per 1/2 cup cooked)',
      'Tofu (10g per 1/2 cup)',
      'Quinoa (4g per 1/2 cup cooked - complete protein)',
      'Nuts and nut butters (peanut butter = 8g per 2 Tbsp)',
      'Edamame (9g per 1/2 cup)',
      'Milk (8g per 8oz)',
      'Protein powder (if approved by your doctor)',
    ],
    importantConsiderations: [
      'Spread protein intake throughout the day for optimal absorption',
      'Combine plant proteins (beans + rice, hummus + pita) to get all essential amino acids',
      'Choose lean protein sources to avoid excess saturated fat',
      'Avoid high-mercury fish - stick to salmon, sardines, trout',
      'Cook all meat, poultry, and eggs thoroughly to prevent foodborne illness',
      'Vegetarians and vegans can meet protein needs but must plan carefully',
      'Protein helps with nausea - eat protein-rich snacks to maintain stable blood sugar',
      'If you have gestational diabetes, protein helps manage blood sugar levels',
    ],
    whenToTalk: [
      'You follow a vegetarian or vegan diet and want to ensure adequate protein',
      'You have severe morning sickness or food aversions limiting protein intake',
      'You have gestational diabetes and need guidance on protein portions',
      'You\'re pregnant with multiples and have higher protein needs',
      'You have kidney disease which may affect protein recommendations',
      'You\'re considering protein supplements or powder during pregnancy',
    ],
    relatedTopics: ['iron-rich-foods', 'foods-to-avoid', 'prenatal-vitamins'],
    trimesterInfo: {
      first: 'Protein needs increase slightly. Morning sickness may make it hard to eat meat - try eggs, yogurt, smoothies with protein powder, or plant proteins. Focus on getting at least 60g daily.',
      second: 'Baby is growing rapidly. Increase protein to 71g daily. This is often when appetite returns and protein is easier to consume. Add extra servings at meals.',
      third: 'Maintain 71g daily protein. Baby is gaining weight quickly and needs maximum protein for growth. This helps prevent low birth weight and supports your body for labor.',
    },
  },
  {
    slug: 'foods-to-avoid',
    title: 'Foods to Avoid During Pregnancy',
    category: 'safety',
    shortDescription: 'Comprehensive guide to foods that pose risks during pregnancy including raw fish, unpasteurized products, and high-mercury seafood.',
    detailedDescription: [
      'During pregnancy, your immune system is naturally suppressed to prevent your body from rejecting the baby. This makes you more susceptible to foodborne illnesses, which can cause serious complications for you and your baby.',
      'Certain foods also contain substances or bacteria that can harm your developing baby, even if they don\'t make you sick. The good news is that by avoiding a relatively short list of foods, you can significantly reduce your risk of food-related pregnancy complications.',
      'While the list of foods to avoid might seem overwhelming at first, most women find it becomes second nature after a few weeks. The key is understanding why each food is risky and finding safe alternatives.',
    ],
    keyBenefits: [
      'Reduces risk of listeria infection which can cause miscarriage or stillbirth',
      'Prevents toxoplasmosis from undercooked meat or contaminated produce',
      'Avoids mercury exposure which harms baby\'s developing nervous system',
      'Eliminates alcohol which can cause fetal alcohol spectrum disorders',
      'Prevents foodborne illness that could harm you and baby',
      'Reduces exposure to harmful bacteria like salmonella and E. coli',
      'Protects baby from excessive caffeine which increases miscarriage risk',
    ],
    recommendedIntake: 'Completely avoid high-risk foods throughout pregnancy. Check food labels and ask about preparation methods when eating out.',
    bestSources: [
      'This section covers foods to AVOID - see related articles for safe alternatives',
      'Choose fully cooked meats, pasteurized dairy, and low-mercury fish',
      'Wash all produce thoroughly under running water',
      'Reheat deli meats and hot dogs to steaming (165°F) before eating',
      'Choose hard cheeses over soft cheeses',
      'Drink pasteurized juice and milk only',
    ],
    importantConsiderations: [
      'RAW OR UNDERCOOKED SEAFOOD: No sushi with raw fish, raw oysters, ceviche, or undercooked fish. Cooked sushi is safe.',
      'HIGH-MERCURY FISH: Avoid shark, swordfish, king mackerel, tilefish, bigeye tuna. Limit albacore tuna to 6oz/week.',
      'RAW OR UNDERCOOKED MEAT: Cook beef/pork to 145°F, ground meat to 160°F, poultry to 165°F. No rare steaks.',
      'RAW EGGS: Avoid raw cookie dough, cake batter, homemade mayo, hollandaise, Caesar dressing, tiramisu. Cooked eggs are safe.',
      'UNPASTEURIZED DAIRY: No raw milk, soft cheeses (brie, camembert, feta, queso fresco) unless labeled pasteurized.',
      'DELI MEATS & HOT DOGS: Can contain listeria. Reheat to steaming hot (165°F) before eating.',
      'ALCOHOL: No amount is considered safe. Even small amounts can harm baby\'s development.',
      'EXCESSIVE CAFFEINE: Limit to 200mg/day (one 12oz coffee). High intake linked to miscarriage.',
      'UNWASHED PRODUCE: Can carry toxoplasmosis or listeria. Wash all fruits/vegetables thoroughly.',
      'UNPASTEURIZED JUICE: Can contain harmful bacteria. Choose pasteurized juice only.',
      'RAW SPROUTS: High risk for E. coli and salmonella. Avoid alfalfa, clover, radish sprouts.',
      'LIVER/PÂTÉ: Extremely high vitamin A can cause birth defects. Limit or avoid.',
    ],
    whenToTalk: [
      'You accidentally ate a high-risk food and are concerned',
      'You\'re experiencing symptoms of food poisoning (fever, vomiting, diarrhea)',
      'You have questions about specific foods not on common avoid lists',
      'You travel frequently and need guidance on food safety',
      'You have cultural dietary practices and want to know what\'s safe',
      'You\'re confused about conflicting food safety information',
    ],
    relatedTopics: ['prenatal-vitamins', 'protein-intake', 'seafood-safety', 'caffeine-limits'],
    trimesterInfo: {
      first: 'Most critical time to avoid harmful foods as baby\'s organs are forming. Alcohol is especially dangerous. Morning sickness may make it easier to avoid aversive foods anyway.',
      second: 'Continue vigilant food safety. Your immune system is most suppressed mid-pregnancy. Be especially careful with deli meats, soft cheeses, and unwashed produce.',
      third: 'Maintain food safety practices through delivery. Listeria infection in late pregnancy can cause premature labor. Continue avoiding high-risk foods while breastfeeding.',
    },
  },
  {
    slug: 'seafood-safety',
    title: 'Seafood Safety During Pregnancy',
    category: 'safety',
    shortDescription: 'Guide to choosing low-mercury fish that provide omega-3 benefits while avoiding high-mercury varieties that harm fetal development.',
    detailedDescription: [
      'Fish is an excellent source of high-quality protein and omega-3 fatty acids (especially DHA) which are crucial for your baby\'s brain and eye development. However, some fish contain high levels of mercury, which can damage your baby\'s developing nervous system.',
      'Mercury accumulates in fish over time, with larger, longer-lived predatory fish containing the highest levels. The key to seafood safety during pregnancy is choosing low-mercury options and limiting portion sizes of moderate-mercury fish.',
      'Most experts recommend eating 8-12 ounces (2-3 servings) of low-mercury fish per week during pregnancy to get the omega-3 benefits without mercury risks. This amount has been shown to support optimal fetal brain development.',
    ],
    keyBenefits: [
      'Provides DHA omega-3 fatty acids crucial for baby\'s brain development',
      'Supports baby\'s eye and vision development',
      'Excellent source of lean protein with all essential amino acids',
      'Rich in vitamin D which aids calcium absorption',
      'Contains selenium, an important antioxidant',
      'May reduce risk of preterm birth and low birth weight',
      'Supports your cardiovascular health during pregnancy',
      'Low in saturated fat compared to other protein sources',
    ],
    recommendedIntake: '8-12 ounces (2-3 servings) of low-mercury fish per week. One serving is about the size of your palm (4 ounces cooked).',
    bestSources: [
      'BEST CHOICES (eat 2-3 servings/week): Salmon, sardines, herring, anchovies, trout, Atlantic mackerel, pollock',
      'Shrimp, tilapia, cod, catfish (low mercury, less omega-3s)',
      'Canned light tuna (2-3 servings/week - lower mercury than albacore)',
      'Freshwater trout',
      'Pacific halibut (in moderation)',
      'Canned salmon with bones (bonus calcium)',
      'GOOD CHOICES (eat 1 serving/week): Albacore (white) tuna, mahi-mahi, snapper, grouper',
    ],
    importantConsiderations: [
      'AVOID COMPLETELY: Shark, swordfish, king mackerel, tilefish, bigeye tuna, marlin, orange roughy',
      'Limit albacore (white) tuna to 6 ounces per week - higher mercury than light tuna',
      'Choose wild-caught salmon over farmed when possible (less contaminants)',
      'If you eat local fish from lakes/rivers, check advisories first - may contain pollutants',
      'Sushi with cooked fish or vegetarian options is safe - avoid raw fish',
      'Cook all fish to 145°F internal temperature to kill harmful bacteria',
      'Consider fish oil supplements if you don\'t eat fish - look for purified, pregnancy-safe brands',
      'Canned fish is convenient and safe - light tuna, salmon, sardines all good choices',
    ],
    whenToTalk: [
      'You don\'t eat fish and wonder about omega-3 supplements',
      'You ate high-mercury fish before knowing you were pregnant',
      'You have concerns about local fish safety or water quality',
      'You\'re allergic to fish and need alternative omega-3 sources',
      'You follow a diet that restricts fish consumption',
      'You ate raw fish (sushi) and are concerned about parasites',
    ],
    relatedTopics: ['protein-intake', 'foods-to-avoid', 'prenatal-vitamins'],
    trimesterInfo: {
      first: 'Begin eating low-mercury fish regularly. DHA is critical for early brain development. If morning sickness makes fish unappealing, try mild options like tilapia or consider supplements.',
      second: 'Baby\'s brain is rapidly developing. Aim for 2-3 servings of low-mercury fish weekly. This is often when fish aversions improve and you can enjoy more varieties.',
      third: 'Continue omega-3 intake as baby\'s brain development accelerates. The third trimester is a critical period for DHA accumulation in baby\'s brain. Don\'t stop eating fish.',
    },
  },
  {
    slug: 'caffeine-limits',
    title: 'Caffeine During Pregnancy',
    category: 'safety',
    shortDescription: 'Guidelines for safe caffeine consumption during pregnancy. Limit to 200mg daily to reduce miscarriage and low birth weight risks.',
    detailedDescription: [
      'Caffeine is a stimulant that crosses the placenta and reaches your baby. Unlike adults, fetuses cannot efficiently metabolize caffeine, so it stays in their system longer. High caffeine intake during pregnancy has been linked to increased risks of miscarriage, low birth weight, and other complications.',
      'Current recommendations from most major medical organizations suggest limiting caffeine to 200mg per day during pregnancy - about the amount in one 12-ounce cup of coffee. Some women choose to eliminate caffeine entirely, especially in the first trimester.',
      'The good news is that moderate caffeine consumption (under 200mg daily) appears to be safe for most pregnant women. The key is being aware of all sources of caffeine in your diet and keeping track of your daily total.',
    ],
    keyBenefits: [
      'Limiting caffeine reduces miscarriage risk (high intake linked to increased risk)',
      'Helps prevent low birth weight',
      'Reduces risk of premature delivery',
      'May help you sleep better during pregnancy',
      'Prevents caffeine withdrawal symptoms if you cut back gradually',
      'Reduces anxiety and jitteriness which can worsen in pregnancy',
      'Helps manage heart palpitations common in pregnancy',
    ],
    recommendedIntake: 'Less than 200mg of caffeine per day. Many doctors recommend even less in the first trimester when miscarriage risk is highest.',
    bestSources: [
      'These are caffeine amounts to TRACK and LIMIT:',
      'Home brewed coffee: 80-100mg per 8oz',
      'Starbucks Pike Place: 180mg per 12oz (tall), 260mg per 16oz (grande)',
      'Instant coffee: 60-80mg per 8oz',
      'Black tea: 40-70mg per 8oz',
      'Green tea: 25-50mg per 8oz',
      'Decaf coffee: 2-5mg per 8oz (safe option)',
      'Cola/soda: 30-40mg per 12oz',
      'Energy drinks: 80-150mg per 8oz (AVOID - often exceed daily limit in one serving)',
      'Dark chocolate: 20mg per 1oz',
      'Milk chocolate: 6mg per 1oz',
      'Coffee ice cream: 30-45mg per 1/2 cup',
    ],
    importantConsiderations: [
      'Coffee strength varies widely - stronger brews have more caffeine',
      'Espresso has 60-80mg per shot - a grande latte has 2 shots (160mg)',
      'Tea steeped longer has more caffeine - steep for less time to reduce content',
      'Energy drinks and pre-workout supplements often exceed the daily limit - avoid completely',
      'Some medications contain caffeine - check labels of pain relievers',
      'Caffeine is also found in some foods like chocolate and coffee-flavored desserts',
      'Switch to half-caf or decaf coffee to reduce intake while maintaining routine',
      'Caffeine is a diuretic - drink extra water if consuming caffeinated beverages',
      'Cut back gradually over a week to avoid withdrawal headaches',
      'Yerba mate and guarana are herbal sources of caffeine - still count toward limit',
    ],
    whenToTalk: [
      'You\'re experiencing heart palpitations or anxiety and wonder if caffeine is contributing',
      'You have a history of miscarriage and want personalized guidance',
      'You drink multiple cups of coffee daily and need help cutting back',
      'You\'re experiencing severe caffeine withdrawal symptoms',
      'You accidentally exceeded the limit and are concerned',
      'You have high blood pressure or gestational hypertension',
    ],
    relatedTopics: ['foods-to-avoid', 'prenatal-vitamins'],
    trimesterInfo: {
      first: 'Most critical time to limit caffeine. Studies link high intake (>200mg) to increased miscarriage risk. Consider eliminating or reducing to under 200mg daily. Morning sickness may naturally reduce caffeine tolerance.',
      second: 'Continue limiting caffeine to 200mg daily. May help with pregnancy-related heart palpitations and anxiety. Energy levels often improve naturally in second trimester, making it easier to rely less on caffeine.',
      third: 'Maintain caffeine limits. High intake may contribute to sleep problems already common in late pregnancy. Some studies suggest high caffeine intake may increase low birth weight risk.',
    },
  },
]

// Helper function to get nutrition data by slug
export function getNutritionData(slug: string): NutritionData | undefined {
  return nutritionData.find(item => item.slug === slug)
}

// Helper function to get all nutrition data
export function getAllNutritionData(): NutritionData[] {
  return nutritionData
}
