// Symptom tracker specific data - focused symptoms for tracking

export interface SymptomTrackerData {
  slug: string
  title: string
  shortDescription: string
  detailedDescription: string[]
  whatItIs: string[]
  whyItHappens: string[]
  commonWeeks: string
  trimestersAffected: string[]
  reliefTips: string[]
  safeRemedies: string[]
  whenToCallDoctor: string[]
  warningDangerSigns: string[]
  relatedSymptoms: string[]
  weeklyLinks: number[]
  userExperiences: { quote: string; name: string; week: number }[]
  faqs: { question: string; answer: string }[]
}

export const symptomTrackerData: SymptomTrackerData[] = [
  {
    slug: 'morning-sickness-nausea',
    title: 'Morning Sickness & Nausea',
    shortDescription: 'Nausea and vomiting that can occur any time of day, affecting up to 80% of pregnant women, especially in the first trimester.',
    detailedDescription: [
      'Morning sickness is one of the earliest and most common pregnancy symptoms. Despite its name, nausea and vomiting can strike at any time of day or night. The condition ranges from mild queasiness to severe vomiting that interferes with daily life.',
      'While uncomfortable, morning sickness is generally a sign of a healthy pregnancy with normal hormone levels. Most women find relief by the end of the first trimester, though some experience symptoms throughout their entire pregnancy.',
      'The severity varies greatly between individuals and even between different pregnancies for the same woman. Understanding triggers and relief strategies can help you manage this challenging symptom.',
    ],
    whatItIs: [
      'Persistent feelings of nausea, often accompanied by increased saliva production',
      'Vomiting that may occur once or multiple times per day',
      'Heightened sensitivity to smells, tastes, and certain foods',
      'Aversion to foods you normally enjoy',
      'Nausea that may worsen on an empty stomach or with certain triggers',
      'Symptoms typically worse in the morning but can occur anytime',
    ],
    whyItHappens: [
      'Rapidly rising hCG (human chorionic gonadotropin) hormone levels in early pregnancy',
      'Elevated estrogen levels affecting the gastrointestinal system',
      'Enhanced sense of smell making you hypersensitive to odors',
      'Slower digestion and delayed stomach emptying caused by progesterone',
      'Low blood sugar levels, particularly after fasting overnight',
      'Stress, fatigue, and emotional changes amplifying physical symptoms',
      'Possible evolutionary protective mechanism to avoid potentially harmful foods during critical fetal development',
    ],
    commonWeeks: 'Weeks 6-14 (peaks at weeks 8-11)',
    trimestersAffected: ['First trimester (most common)', 'Early second trimester for some', 'Rarely persists into third trimester'],
    reliefTips: [
      'Eat small, frequent meals every 2-3 hours to maintain stable blood sugar',
      'Keep dry crackers, toast, or cereal by your bedside to eat before rising',
      'Stay hydrated with small sips of water, ginger ale, or clear fluids throughout the day',
      'Avoid strong smells, greasy foods, and spicy meals that trigger your nausea',
      'Get plenty of fresh air and take short walks to help settle your stomach',
      'Eat bland, room-temperature foods which have less odor than hot meals',
      'Rest frequently as fatigue can worsen nausea',
      'Try cold foods like popsicles, frozen fruit, or chilled smoothies',
      'Avoid brushing teeth immediately after eating to prevent triggering gag reflex',
      'Wear loose, comfortable clothing that doesn\'t constrict your abdomen',
    ],
    safeRemedies: [
      'Ginger tea, ginger ale (with real ginger), or ginger supplements (250mg four times daily)',
      'Vitamin B6 supplements (25mg three times daily) - clinically proven to reduce nausea',
      'Acupressure wristbands (Sea-Bands) on P6 pressure points on inner wrists',
      'Peppermint tea or peppermint aromatherapy',
      'Lemon water, lemon slices, or inhaling lemon scent',
      'Protein-rich snacks before bed to prevent morning nausea',
      'Unisom (doxylamine) combined with B6 - consult your doctor first',
      'Prescription medications like Zofran for severe cases (doctor prescribed only)',
      'Eating sour or tart foods like pickles or citrus fruits',
      'Small amounts of ice chips or frozen fruit to stay hydrated',
    ],
    whenToCallDoctor: [
      'Unable to keep any food or liquids down for 24 hours',
      'Vomiting multiple times per day (more than 3-4 episodes)',
      'Signs of dehydration: dark urine, dizziness, rapid heartbeat, extreme thirst',
      'Weight loss exceeding 5% of your pre-pregnancy weight',
      'Blood in vomit or vomit that resembles coffee grounds',
      'Severe abdominal pain accompanying the vomiting',
      'High fever (over 101°F/38.3°C) along with nausea and vomiting',
      'Unable to take prenatal vitamins or prescribed medications',
    ],
    warningDangerSigns: [
      'Hyperemesis gravidarum (severe, persistent vomiting requiring hospitalization)',
      'Extreme dehydration requiring IV fluids',
      'Ketones in urine indicating body is breaking down fat for energy',
      'Rapid pulse or irregular heartbeat',
      'Confusion or extreme weakness',
    ],
    relatedSymptoms: ['fatigue-exhaustion', 'heartburn-indigestion', 'mood-swings-anxiety', 'frequent-urination'],
    weeklyLinks: [6, 7, 8, 9, 10, 11, 12, 13, 14],
    userExperiences: [
      {
        quote: 'Keeping saltines by my bed and eating a few before getting up was a game-changer. The nausea was still there but much more manageable.',
        name: 'Sarah M.',
        week: 9,
      },
      {
        quote: 'Ginger tea became my best friend. I drank it throughout the day and it really helped settle my stomach. By week 14, I finally felt human again.',
        name: 'Jessica T.',
        week: 11,
      },
      {
        quote: 'My doctor prescribed vitamin B6 and Unisom, and it made such a difference. I went from vomiting 5-6 times a day to maybe once or twice.',
        name: 'Amanda R.',
        week: 8,
      },
    ],
    faqs: [
      {
        question: 'Is morning sickness a sign of a healthy pregnancy?',
        answer: 'Yes, morning sickness is generally associated with positive pregnancy outcomes and lower miscarriage rates. The nausea is caused by rising pregnancy hormones, which indicate your body is properly supporting the pregnancy. However, the absence of morning sickness doesn\'t indicate a problem either - about 20-30% of women never experience it.',
      },
      {
        question: 'Can morning sickness harm my baby?',
        answer: 'Typical morning sickness does not harm your baby. Your baby takes the nutrients it needs from your body\'s reserves. However, severe cases (hyperemesis gravidarum) with significant weight loss and dehydration require medical treatment to ensure both you and baby stay healthy.',
      },
      {
        question: 'When should morning sickness start to improve?',
        answer: 'Most women notice improvement by weeks 14-16 as hormone levels stabilize. For about 80-90% of women, symptoms resolve by the end of the first trimester. However, 10-20% of women may experience nausea into the second trimester, and a small percentage throughout pregnancy.',
      },
      {
        question: 'Why is it called morning sickness if it happens all day?',
        answer: 'The term "morning sickness" is misleading. While symptoms are often worse in the morning due to an empty stomach and low blood sugar after sleeping, nausea and vomiting can occur at any time of day. Many women report evening nausea or all-day symptoms. A more accurate term would be "pregnancy-related nausea and vomiting."',
      },
    ],
  },
  {
    slug: 'fatigue-exhaustion',
    title: 'Fatigue & Exhaustion',
    shortDescription: 'Overwhelming tiredness and lack of energy that affects nearly all pregnant women, especially in the first and third trimesters.',
    detailedDescription: [
      'Pregnancy fatigue is not your average tiredness - it\'s an overwhelming exhaustion that can make even the simplest tasks feel impossible. Many women describe it as feeling like they\'ve run a marathon when all they\'ve done is get dressed.',
      'This extreme fatigue is one of the earliest signs of pregnancy and can begin as soon as one week after conception. Your body is working incredibly hard behind the scenes to support the developing baby, build the placenta, and dramatically increase blood volume.',
      'While fatigue often improves during the "golden" second trimester, it typically returns in the third trimester as your body carries extra weight and sleep becomes more difficult.',
    ],
    whatItIs: [
      'Overwhelming tiredness that feels different from normal fatigue',
      'Difficulty staying awake during the day despite adequate sleep',
      'Physical and mental exhaustion that affects daily activities',
      'Feeling like you need to nap frequently',
      'Difficulty concentrating or focusing on tasks',
      'Heaviness in limbs and body',
    ],
    whyItHappens: [
      'Dramatic increase in progesterone hormone, which has a natural sedative effect',
      'Your body working 24/7 to build the placenta and support fetal development',
      'Blood volume increasing by up to 50% by the end of pregnancy',
      'Lower blood sugar and blood pressure levels in early pregnancy',
      'Significantly increased metabolism as your body works overtime',
      'Physical and emotional adjustments to pregnancy causing mental fatigue',
      'Frequent nighttime wake-ups for bathroom trips disrupting sleep quality',
      'Iron deficiency anemia, common in pregnancy',
      'In third trimester: carrying extra weight and physical discomfort preventing quality sleep',
    ],
    commonWeeks: 'Weeks 1-13 (severe), improves weeks 14-27, returns weeks 28-40',
    trimestersAffected: ['First trimester (most intense)', 'Second trimester (usually improves)', 'Third trimester (returns)'],
    reliefTips: [
      'Prioritize sleep - aim for 8-10 hours per night plus daytime naps when possible',
      'Go to bed earlier and establish a consistent sleep schedule',
      'Take short 20-30 minute power naps during the day if needed',
      'Don\'t fight your body\'s signals - rest when you feel tired',
      'Reduce commitments and give yourself permission to slow down',
      'Ask for help with household chores and errands',
      'Stay hydrated as dehydration significantly worsens fatigue',
      'Get some gentle exercise like short walks to boost energy',
      'Limit caffeine and avoid it after 2pm to protect nighttime sleep quality',
      'Use pregnancy pillows to improve sleep comfort in later stages',
    ],
    safeRemedies: [
      'Iron-rich foods (red meat, spinach, lentils, fortified cereals) with vitamin C for absorption',
      'Small, frequent meals with protein to maintain steady blood sugar',
      'Complex carbohydrates for sustained energy (whole grains, sweet potatoes)',
      'Prenatal vitamins with iron (take with food to avoid nausea)',
      'B-complex vitamins for energy support',
      'Mild exercise like prenatal yoga or swimming',
      'Fresh air and natural light exposure during the day',
      'Magnesium-rich foods (nuts, seeds, leafy greens) for better sleep',
      'Limit sugar and processed foods that cause energy crashes',
      'Consider iron supplements if blood tests show anemia (doctor prescribed)',
    ],
    whenToCallDoctor: [
      'Extreme exhaustion that interferes with basic daily functioning',
      'Fatigue accompanied by dizziness, fainting, or rapid heartbeat',
      'Shortness of breath even with minimal activity',
      'Pale skin, cold hands and feet (possible severe anemia)',
      'Severe fatigue combined with depression or anxiety',
      'No improvement in second trimester as expected',
      'Sudden onset of extreme fatigue in later pregnancy',
      'Fatigue accompanied by swelling, headaches, or vision changes',
    ],
    warningDangerSigns: [
      'Severe anemia requiring medical intervention',
      'Thyroid dysfunction causing extreme fatigue',
      'Gestational diabetes symptoms',
      'Preeclampsia indicators (with swelling and high blood pressure)',
      'Depression or prenatal anxiety requiring treatment',
    ],
    relatedSymptoms: ['morning-sickness-nausea', 'mood-swings-anxiety', 'frequent-urination', 'back-pain-sciatica'],
    weeklyLinks: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
    userExperiences: [
      {
        quote: 'I felt like I could fall asleep standing up during my first trimester. I gave myself permission to nap every day after work and it helped immensely.',
        name: 'Maria L.',
        week: 10,
      },
      {
        quote: 'Adding iron-rich foods and making sure I took my prenatal vitamin with orange juice really helped. My energy came back in the second trimester.',
        name: 'Emily K.',
        week: 16,
      },
      {
        quote: 'Third trimester exhaustion was different - more physical. Pregnancy pillows and going to bed at 9pm became essential.',
        name: 'Rachel P.',
        week: 34,
      },
    ],
    faqs: [
      {
        question: 'Is extreme fatigue normal in early pregnancy?',
        answer: 'Yes, extreme fatigue is completely normal in early pregnancy and affects 90-95% of pregnant women. Your body is undergoing massive physiological changes, building a placenta, and producing significantly more blood. The hormone progesterone also acts as a natural sedative. This fatigue typically improves significantly by the second trimester.',
      },
      {
        question: 'Will my energy come back during pregnancy?',
        answer: 'Most women experience a significant energy boost during the second trimester (weeks 14-27), often called the "golden period" of pregnancy. However, fatigue typically returns in the third trimester due to the physical demands of carrying extra weight, sleep disruptions, and your body preparing for labor.',
      },
      {
        question: 'How much sleep do I need during pregnancy?',
        answer: 'Most pregnant women need 8-10 hours of sleep per night, which is more than the typical 7-9 hours recommended for adults. Listen to your body and nap when needed. Quality sleep is crucial for fetal development and your own health during pregnancy.',
      },
      {
        question: 'Can exercise help with pregnancy fatigue?',
        answer: 'Yes, moderate exercise can actually boost energy levels during pregnancy. Gentle activities like walking, prenatal yoga, or swimming can improve circulation, mood, and sleep quality. Start with just 10-15 minutes if you\'re exhausted, and build up gradually. Always listen to your body and don\'t overdo it.',
      },
    ],
  },
  {
    slug: 'back-pain-sciatica',
    title: 'Back Pain & Sciatica',
    shortDescription: 'Lower back pain and sciatica nerve pain affecting 50-70% of pregnant women, especially in the second and third trimesters.',
    detailedDescription: [
      'Back pain is one of the most common complaints during pregnancy, affecting more than half of all expectant mothers. The pain can range from mild discomfort to severe pain that interferes with daily activities and sleep.',
      'Sciatica occurs when the sciatic nerve (which runs from your lower back down through your hips and legs) becomes compressed or irritated. This creates a sharp, shooting pain that radiates from your lower back through your buttock and down your leg.',
      'As your pregnancy progresses and your baby grows, the additional weight and shift in your center of gravity puts increasing strain on your back. Understanding proper posture, body mechanics, and relief strategies is essential for managing this discomfort.',
    ],
    whatItIs: [
      'Dull, aching pain in the lower back or upper back',
      'Sharp, shooting pain from lower back down the leg (sciatica)',
      'Muscle tension and stiffness in the back',
      'Pain that worsens with standing, walking, or sitting for long periods',
      'Difficulty getting up from sitting or lying positions',
      'Numbness or tingling in the buttocks or legs (sciatica)',
    ],
    whyItHappens: [
      'Growing uterus and baby shifting your center of gravity forward',
      'Additional weight gain putting strain on back muscles and spine',
      'Hormone relaxin loosening ligaments and joints in preparation for birth',
      'Postural changes as you adjust to carrying weight in front',
      'Weakened abdominal muscles unable to support the spine as effectively',
      'Uterus putting pressure on sciatic nerve (causing sciatica)',
      'Stress and tension causing muscle tightness',
      'Poor sleeping positions or inadequate mattress support',
    ],
    commonWeeks: 'Weeks 18-40 (intensifies as pregnancy progresses)',
    trimestersAffected: ['Second trimester (begins)', 'Third trimester (most severe)'],
    reliefTips: [
      'Practice good posture - keep shoulders back and avoid arching your lower back',
      'Use a pregnancy support belt to help distribute weight',
      'Wear supportive, low-heeled shoes (avoid high heels completely)',
      'Sleep on your left side with a pillow between your knees',
      'Use a pregnancy pillow for full-body support while sleeping',
      'Avoid standing for long periods - take frequent sitting breaks',
      'When sitting, use a footstool to keep knees higher than hips',
      'Apply heat or cold packs to painful areas (20 minutes at a time)',
      'Get up slowly from sitting or lying positions',
      'Avoid lifting heavy objects and ask for help when needed',
    ],
    safeRemedies: [
      'Prenatal yoga focusing on back-strengthening poses and stretches',
      'Swimming or water aerobics to relieve pressure on the spine',
      'Gentle stretching exercises targeting back and hip muscles',
      'Prenatal massage from a certified therapist experienced in pregnancy',
      'Physical therapy with exercises tailored to pregnancy',
      'Warm (not hot) baths to relax muscles',
      'Pelvic tilts and cat-cow stretches to relieve lower back tension',
      'Acetaminophen (Tylenol) for pain relief - always consult your doctor first',
      'Sleeping with pillow support under belly and between knees',
      'Chiropractor care specializing in prenatal adjustments',
    ],
    whenToCallDoctor: [
      'Severe pain that doesn\'t improve with rest or position changes',
      'Numbness or weakness in one or both legs',
      'Back pain accompanied by vaginal bleeding',
      'Fever along with back pain (possible kidney infection)',
      'Pain when urinating combined with back pain',
      'Rhythmic back pain that comes and goes (could be contractions)',
      'Sudden severe pain that takes your breath away',
      'Back pain beginning before 12 weeks (unusual timing)',
    ],
    warningDangerSigns: [
      'Signs of preterm labor (back pain with contractions before 37 weeks)',
      'Kidney infection symptoms requiring immediate treatment',
      'Severe sciatica with loss of bladder or bowel control',
      'Inability to walk or bear weight',
      'Progressive weakness in legs',
    ],
    relatedSymptoms: ['round-ligament-pain', 'leg-cramps', 'swelling-edema', 'braxton-hicks'],
    weeklyLinks: [18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40],
    userExperiences: [
      {
        quote: 'The pregnancy support belt was a lifesaver. I could actually walk around the grocery store without wanting to cry from the back pain.',
        name: 'Jennifer H.',
        week: 28,
      },
      {
        quote: 'Prenatal yoga and stretching every morning made such a difference. I also slept with a pillow between my knees and under my belly.',
        name: 'Nicole D.',
        week: 32,
      },
      {
        quote: 'My sciatica was terrible until I started seeing a prenatal chiropractor. The adjustments gave me so much relief.',
        name: 'Stephanie W.',
        week: 35,
      },
    ],
    faqs: [
      {
        question: 'Is back pain normal during pregnancy?',
        answer: 'Yes, back pain is very common and affects 50-70% of pregnant women. It\'s caused by multiple factors including weight gain, hormonal changes that loosen ligaments, and shifts in your center of gravity. While normal, severe or persistent pain should be evaluated by your healthcare provider.',
      },
      {
        question: 'What\'s the difference between regular back pain and sciatica?',
        answer: 'Regular pregnancy back pain is typically a dull ache in the lower back. Sciatica is more specific - it\'s a sharp, shooting pain that starts in your lower back or buttock and radiates down the back of your leg, sometimes all the way to your foot. Sciatica may also cause numbness, tingling, or weakness in the leg.',
      },
      {
        question: 'When does pregnancy back pain typically start?',
        answer: 'Back pain most commonly begins in the second trimester (around weeks 18-24) as your baby grows and your belly expands. However, some women experience it earlier, and it typically intensifies throughout the third trimester. The pain usually resolves gradually after delivery as your body returns to its pre-pregnancy state.',
      },
      {
        question: 'Can I use heating pads for pregnancy back pain?',
        answer: 'Yes, but with caution. Use heating pads on the lowest setting and limit application to 20 minutes at a time. Avoid placing heat directly on your abdomen. Warm (not hot) baths are also safe and effective. Alternating between heat and cold therapy often provides the best relief.',
      },
    ],
  },
  {
    slug: 'swelling-edema',
    title: 'Swelling (Edema)',
    shortDescription: 'Fluid retention causing swelling in hands, feet, ankles, and face, affecting about 75% of pregnant women, especially in the third trimester.',
    detailedDescription: [
      'Swelling, medically known as edema, is a normal part of pregnancy for most women. Your body produces approximately 50% more blood and body fluids during pregnancy to meet the needs of your developing baby, and some of this extra fluid accumulates in your tissues.',
      'While mild to moderate swelling is normal, especially at the end of the day or during hot weather, sudden or severe swelling can be a warning sign of preeclampsia or other complications that require immediate medical attention.',
      'The swelling typically starts in the second trimester and becomes more noticeable in the third trimester. Understanding what\'s normal versus concerning is crucial for both your comfort and safety.',
    ],
    whatItIs: [
      'Puffiness or swelling in feet, ankles, and legs (most common)',
      'Swollen fingers and hands (rings may not fit)',
      'Mild facial swelling, especially around eyes in the morning',
      'Tight feeling when wearing shoes or rings',
      'Skin that looks stretched or shiny',
      'Indentation remaining after pressing on swollen area',
    ],
    whyItHappens: [
      '50% increase in blood volume and body fluids during pregnancy',
      'Growing uterus putting pressure on veins returning blood from legs',
      'Hormones causing body to retain more sodium and water',
      'Gravity pulling fluid down to lower extremities',
      'Hot weather causing blood vessels to expand',
      'Standing or sitting for extended periods without movement',
      'Diet high in sodium increasing fluid retention',
      'Increased blood flow to support baby\'s development',
    ],
    commonWeeks: 'Weeks 22-40 (increases gradually, most noticeable in third trimester)',
    trimestersAffected: ['Late second trimester (begins)', 'Third trimester (most common and severe)'],
    reliefTips: [
      'Elevate your feet above heart level when resting (use pillows)',
      'Avoid standing or sitting for long periods - move frequently',
      'Sleep on your left side to improve circulation',
      'Wear comfortable, supportive shoes that can accommodate swelling',
      'Remove rings before swelling makes them difficult to remove',
      'Stay cool in hot weather - use fans or air conditioning',
      'Avoid crossing your legs when sitting',
      'Take short walks to improve circulation',
      'Swim or stand in pool - water pressure helps reduce swelling',
      'Wear compression stockings to prevent fluid accumulation in legs',
    ],
    safeRemedies: [
      'Stay well hydrated (8-10 glasses of water daily) - counterintuitive but helps flush excess sodium',
      'Reduce sodium intake - avoid processed foods, fast food, and adding salt',
      'Eat potassium-rich foods (bananas, sweet potatoes, avocados) to balance fluids',
      'Gentle exercise like walking or swimming to improve circulation',
      'Prenatal massage focusing on lymphatic drainage',
      'Support stockings or compression socks (15-20 mmHg)',
      'Cold compresses or foot soaks for comfort',
      'Magnesium supplements (consult doctor first) may help reduce fluid retention',
      'Eat natural diuretic foods (cucumber, watermelon, celery)',
      'Keep feet elevated whenever possible throughout the day',
    ],
    whenToCallDoctor: [
      'Sudden or severe swelling, especially in hands and face',
      'Swelling in only one leg (possible blood clot)',
      'Swelling accompanied by severe headache',
      'Visual changes with swelling (blurred vision, seeing spots)',
      'Swelling with upper abdominal pain',
      'Rapid weight gain (more than 2-4 pounds in a week)',
      'Swelling that doesn\'t improve with elevation or rest',
      'Difficulty breathing with swelling',
    ],
    warningDangerSigns: [
      'Preeclampsia (severe swelling with high blood pressure and protein in urine)',
      'Deep vein thrombosis (blood clot, usually one-sided leg swelling with pain)',
      'Heart or kidney problems causing severe fluid retention',
      'Sudden onset swelling as potential emergency sign',
    ],
    relatedSymptoms: ['leg-cramps', 'back-pain-sciatica', 'frequent-urination', 'heartburn-indigestion'],
    weeklyLinks: [22, 24, 26, 28, 30, 32, 34, 36, 38, 40],
    userExperiences: [
      {
        quote: 'My feet swelled so much by the end of the day. Putting them up for 20 minutes when I got home from work really helped, and I bought shoes one size bigger.',
        name: 'Lauren S.',
        week: 32,
      },
      {
        quote: 'Swimming was amazing for the swelling. I felt so light in the water and my ankles looked almost normal afterward.',
        name: 'Michelle B.',
        week: 36,
      },
      {
        quote: 'I had to take my rings off at week 28 and couldn\'t wear them again until after delivery. The swelling in my hands was intense!',
        name: 'Ashley C.',
        week: 33,
      },
    ],
    faqs: [
      {
        question: 'Is swelling normal during pregnancy?',
        answer: 'Yes, mild to moderate swelling is very common and affects about 75% of pregnant women, especially in the third trimester. It\'s caused by increased blood volume and fluid retention. However, sudden or severe swelling, particularly in your face and hands accompanied by headaches or vision changes, could indicate preeclampsia and requires immediate medical attention.',
      },
      {
        question: 'When should I worry about swelling during pregnancy?',
        answer: 'Contact your doctor immediately if you experience sudden, severe swelling (especially in face and hands), swelling in only one leg, swelling accompanied by severe headache or vision changes, rapid weight gain (more than 2-4 pounds in a week), or difficulty breathing. These could be signs of preeclampsia or blood clots.',
      },
      {
        question: 'Will drinking more water make swelling worse?',
        answer: 'No, this is a common misconception. Staying well-hydrated actually helps reduce swelling by flushing excess sodium from your system and preventing your body from retaining water. Aim for 8-10 glasses of water daily. Dehydration can actually worsen swelling as your body holds onto fluids.',
      },
      {
        question: 'How long does postpartum swelling last?',
        answer: 'Most pregnancy-related swelling resolves within the first week after delivery as your body eliminates excess fluid. Some women experience increased swelling in the first few days postpartum as IV fluids from labor are processed. If swelling persists beyond 1-2 weeks postpartum, contact your healthcare provider.',
      },
    ],
  },
  {
    slug: 'heartburn-indigestion',
    title: 'Heartburn & Indigestion',
    shortDescription: 'Burning sensation in chest and throat affecting up to 80% of pregnant women, especially in the second and third trimesters.',
    detailedDescription: [
      'Heartburn and indigestion are among the most uncomfortable pregnancy symptoms, creating a burning sensation in your chest and throat that can be particularly bothersome at night. The condition worsens as pregnancy progresses and your growing baby takes up more space.',
      'Also called acid reflux or gastroesophageal reflux (GERD), pregnancy heartburn occurs when stomach acid flows back up into your esophagus. While extremely uncomfortable, it\'s a common and generally harmless pregnancy symptom.',
      'The good news is that heartburn almost always resolves completely after delivery. In the meantime, dietary changes, lifestyle modifications, and safe remedies can provide significant relief.',
    ],
    whatItIs: [
      'Burning sensation in chest, often behind the breastbone',
      'Sour or bitter taste in mouth and throat',
      'Burning feeling that rises from stomach to chest and throat',
      'Discomfort that worsens after eating, lying down, or bending over',
      'Burping or regurgitation of food or sour liquid',
      'Difficulty swallowing or feeling of food stuck in throat',
    ],
    whyItHappens: [
      'Progesterone hormone relaxing the valve between stomach and esophagus',
      'Growing uterus pushing stomach upward and increasing pressure',
      'Slower digestion causing food to remain in stomach longer',
      'Reduced space in abdomen as baby grows',
      'Hormones relaxing smooth muscle throughout digestive tract',
      'Certain foods triggering increased acid production',
      'Eating large meals overwhelming digestive system',
    ],
    commonWeeks: 'Weeks 20-40 (intensifies throughout second and third trimesters)',
    trimestersAffected: ['Second trimester (begins)', 'Third trimester (most severe)'],
    reliefTips: [
      'Eat smaller, more frequent meals instead of three large meals',
      'Avoid eating within 2-3 hours of bedtime',
      'Stay upright for at least an hour after eating',
      'Elevate head of bed 6-8 inches or sleep propped up on pillows',
      'Eat slowly and chew food thoroughly',
      'Wear loose-fitting clothing that doesn\'t constrict waist or abdomen',
      'Avoid bending over after meals - squat instead',
      'Sip water throughout the day but avoid drinking large amounts with meals',
      'Chew gum after eating to increase saliva and neutralize acid',
      'Track foods that trigger your heartburn and avoid them',
    ],
    safeRemedies: [
      'Antacids (Tums, Rolaids) for immediate relief - safe during pregnancy',
      'Calcium carbonate supplements which also act as antacids',
      'H2 blockers like Pepcid or Zantac (consult doctor first)',
      'Proton pump inhibitors for severe cases (doctor prescribed)',
      'Drink cold milk for temporary relief',
      'Eat yogurt or drink small amounts of buttermilk',
      'Try papaya or papaya enzymes to aid digestion',
      'Almonds - small handful can help neutralize acid',
      'Ginger tea or ginger lozenges',
      'Apple cider vinegar diluted in water before meals (1 tablespoon in 8oz water)',
    ],
    whenToCallDoctor: [
      'Severe heartburn not relieved by over-the-counter antacids',
      'Difficulty or pain when swallowing',
      'Heartburn accompanied by severe abdominal pain',
      'Vomiting blood or material that looks like coffee grounds',
      'Black, tarry stools (possible bleeding)',
      'Heartburn with shortness of breath or chest pain (rule out heart issues)',
      'Significant weight loss due to inability to eat',
      'Heartburn interfering with sleep or daily activities',
    ],
    warningDangerSigns: [
      'Signs of esophageal damage from chronic acid exposure',
      'Chest pain that could indicate heart problems (rare but serious)',
      'Severe reflux causing aspiration or breathing problems',
      'Inability to keep down food or medications',
    ],
    relatedSymptoms: ['morning-sickness-nausea', 'constipation', 'swelling-edema', 'shortness-of-breath'],
    weeklyLinks: [20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40],
    userExperiences: [
      {
        quote: 'Sleeping propped up on pillows was the only way I could sleep in the third trimester. Heartburn hit every single night after dinner.',
        name: 'Diana M.',
        week: 34,
      },
      {
        quote: 'I kept Tums in my purse, car, bedside table, everywhere! Small frequent meals and avoiding spicy food helped a lot.',
        name: 'Kristin J.',
        week: 29,
      },
      {
        quote: 'My doctor prescribed Pepcid and it was life-changing. I could finally sleep through the night without waking up with acid in my throat.',
        name: 'Rebecca F.',
        week: 32,
      },
    ],
    faqs: [
      {
        question: 'Is heartburn during pregnancy harmful to the baby?',
        answer: 'No, heartburn is uncomfortable for you but does not harm your baby. It\'s caused by hormonal changes and your growing uterus putting pressure on your stomach. The old wives\' tale that heartburn means your baby will have lots of hair has actually been supported by one small study, but more research is needed.',
      },
      {
        question: 'What medications are safe for pregnancy heartburn?',
        answer: 'Antacids containing calcium carbonate (Tums, Rolaids) are generally safe and provide quick relief. H2 blockers like Pepcid (famotidine) are also considered safe. Avoid antacids containing sodium bicarbonate or aspirin. Always consult your healthcare provider before taking any medication, even over-the-counter options.',
      },
      {
        question: 'Why is heartburn worse at night?',
        answer: 'Heartburn worsens at night because lying flat allows stomach acid to flow more easily into the esophagus. Gravity isn\'t helping keep acid down when you\'re horizontal. Additionally, the valve between your stomach and esophagus is already relaxed due to pregnancy hormones, making nighttime reflux more likely.',
      },
      {
        question: 'Will heartburn go away after delivery?',
        answer: 'Yes, for most women, heartburn resolves completely within a few days to weeks after delivery. Once the baby is born, the pressure on your stomach is relieved and hormone levels return to normal, allowing the valve between your stomach and esophagus to function properly again.',
      },
    ],
  },
  {
    slug: 'constipation',
    title: 'Constipation',
    shortDescription: 'Difficult, infrequent bowel movements affecting up to 40% of pregnant women throughout pregnancy, caused by hormones and iron supplements.',
    detailedDescription: [
      'Constipation is one of the most common and uncomfortable digestive issues during pregnancy. It can begin as early as the first trimester and persist throughout your entire pregnancy if not properly managed.',
      'The condition ranges from mild discomfort to severe pain and can lead to hemorrhoids if you strain during bowel movements. Many women find that constipation also contributes to bloating, gas, and general abdominal discomfort.',
      'Understanding the causes and implementing multiple relief strategies early in pregnancy can help prevent constipation from becoming a persistent problem that affects your quality of life.',
    ],
    whatItIs: [
      'Fewer than three bowel movements per week',
      'Hard, dry, lumpy stools that are difficult to pass',
      'Straining during bowel movements',
      'Feeling of incomplete evacuation after bowel movement',
      'Bloating and abdominal discomfort',
      'Stomach cramping and gas pain',
    ],
    whyItHappens: [
      'Progesterone hormone relaxing intestinal muscles and slowing digestion',
      'Iron in prenatal vitamins causing harder stools',
      'Growing uterus putting pressure on intestines',
      'Changes in diet or eating habits',
      'Reduced physical activity or exercise',
      'Not drinking enough water throughout the day',
      'Ignoring the urge to have bowel movements',
      'Stress and hormonal changes affecting digestion',
    ],
    commonWeeks: 'Weeks 1-40 (can occur throughout entire pregnancy)',
    trimestersAffected: ['First trimester (begins)', 'Second trimester (continues)', 'Third trimester (may worsen)'],
    reliefTips: [
      'Drink plenty of water - at least 8-10 glasses (64-80 oz) daily',
      'Increase fiber intake gradually to 25-30 grams per day',
      'Eat prunes or drink prune juice - natural laxative effect',
      'Exercise daily, even just a 20-30 minute walk',
      'Establish regular bathroom routine - don\'t ignore the urge to go',
      'Take your time in bathroom - don\'t rush',
      'Use a footstool to elevate feet while on toilet (better position)',
      'Drink warm liquids, especially in the morning, to stimulate bowels',
      'Try warm water with lemon first thing in the morning',
      'Reduce processed foods and increase whole foods',
    ],
    safeRemedies: [
      'High-fiber foods: fruits, vegetables, whole grains, beans, legumes',
      'Prunes, figs, and other dried fruits (natural laxatives)',
      'Chia seeds, flax seeds, or psyllium husk added to food or smoothies',
      'Probiotics from yogurt, kefir, or supplements to support gut health',
      'Magnesium supplements (consult doctor - also helps with leg cramps)',
      'Stool softeners like Colace (docusate) - generally safe during pregnancy',
      'Psyllium fiber supplements like Metamucil',
      'Mild herbal teas (consult doctor about which are pregnancy-safe)',
      'Switch to low-iron or slow-release prenatal vitamin if iron is the culprit',
      'Over-the-counter remedies like MiraLAX (consult doctor first)',
    ],
    whenToCallDoctor: [
      'No bowel movement for more than 4-5 days',
      'Severe abdominal pain or cramping',
      'Nausea and vomiting with constipation',
      'Constipation alternating with diarrhea',
      'Blood in stool or rectal bleeding',
      'Severe hemorrhoids causing significant pain or bleeding',
      'Over-the-counter remedies not providing relief',
      'Constipation accompanied by back pain or fever',
    ],
    warningDangerSigns: [
      'Bowel obstruction symptoms (severe pain, vomiting, no gas passing)',
      'Signs of hemorrhoids becoming thrombosed (severely painful)',
      'Rectal prolapse from excessive straining',
      'Severe pain that could indicate other complications',
    ],
    relatedSymptoms: ['heartburn-indigestion', 'swelling-edema', 'back-pain-sciatica', 'hemorrhoids'],
    weeklyLinks: [6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40],
    userExperiences: [
      {
        quote: 'Prune juice became my morning ritual. Not the most glamorous part of pregnancy, but it worked! I drank a small glass every morning.',
        name: 'Samantha R.',
        week: 20,
      },
      {
        quote: 'Adding ground flax seeds to my yogurt and making sure I walked 30 minutes daily really helped. Also, drinking tons of water!',
        name: 'Lisa M.',
        week: 25,
      },
      {
        quote: 'My doctor suggested Colace stool softeners and they were a game changer. Safe for pregnancy and made such a difference.',
        name: 'Catherine L.',
        week: 18,
      },
    ],
    faqs: [
      {
        question: 'Is constipation dangerous during pregnancy?',
        answer: 'While uncomfortable, constipation itself is not dangerous to you or your baby. However, chronic constipation can lead to hemorrhoids, anal fissures, and significant discomfort. Severe straining should be avoided. If constipation is accompanied by severe pain, bleeding, or persists despite home remedies, contact your healthcare provider.',
      },
      {
        question: 'Can I take laxatives during pregnancy?',
        answer: 'Some laxatives are safe during pregnancy, but always consult your doctor first. Stool softeners like Colace (docusate) are generally considered safe. Bulk-forming laxatives like Metamucil are also typically safe. Avoid stimulant laxatives like Ex-Lax or castor oil unless specifically recommended by your healthcare provider, as they can cause cramping and potentially stimulate uterine contractions.',
      },
      {
        question: 'Should I stop taking iron if it causes constipation?',
        answer: 'Don\'t stop taking your prenatal vitamins without consulting your doctor, as iron is crucial for preventing anemia during pregnancy. Instead, try taking your vitamin with food, drinking more water, increasing fiber intake, or ask your doctor about switching to a low-iron formula or slow-release iron supplement that may be easier on your digestive system.',
      },
      {
        question: 'How much fiber should I eat during pregnancy?',
        answer: 'Aim for 25-30 grams of fiber per day. Increase fiber intake gradually to avoid gas and bloating. Good sources include fruits, vegetables, whole grains, beans, lentils, and chia or flax seeds. Be sure to increase water intake as you increase fiber, as fiber needs water to work effectively.',
      },
    ],
  },
  {
    slug: 'mood-swings-anxiety',
    title: 'Mood Swings & Anxiety',
    shortDescription: 'Emotional ups and downs, irritability, and anxiety affecting most pregnant women, caused by hormones and life changes.',
    detailedDescription: [
      'Pregnancy brings a rollercoaster of emotions - you might feel overjoyed one moment and burst into tears the next. Mood swings are completely normal and affect nearly all pregnant women to varying degrees, especially in the first and third trimesters.',
      'These emotional changes aren\'t just "in your head" - they\'re caused by dramatic hormonal shifts, physical discomfort, fatigue, and the psychological adjustment to becoming a parent. Anxiety about the pregnancy, delivery, and parenting is also very common.',
      'While some emotional ups and downs are normal, severe anxiety, persistent sadness, or symptoms of depression require professional support. Understanding the difference between normal mood changes and concerning symptoms is important for your mental health.',
    ],
    whatItIs: [
      'Sudden emotional shifts from happy to sad or angry',
      'Crying easily or becoming tearful over small things',
      'Increased irritability or feeling short-tempered',
      'Anxiety or worry about pregnancy, baby, or parenthood',
      'Feeling overwhelmed by small tasks or decisions',
      'Heightened sensitivity to comments or situations',
    ],
    whyItHappens: [
      'Dramatic fluctuations in estrogen and progesterone hormones',
      'Physical discomfort and fatigue affecting emotional state',
      'Worry and anxiety about pregnancy health and baby development',
      'Stress about upcoming life changes and new responsibilities',
      'Sleep deprivation and exhaustion depleting emotional resources',
      'Changes in body image and identity',
      'Financial concerns about providing for a baby',
      'Previous history of anxiety or depression',
    ],
    commonWeeks: 'Weeks 1-12 (first trimester peaks), improves mid-pregnancy, returns weeks 28-40',
    trimestersAffected: ['First trimester (hormonal surges)', 'Second trimester (usually improves)', 'Third trimester (anxiety increases)'],
    reliefTips: [
      'Talk about your feelings with partner, friends, or family',
      'Join pregnancy support groups online or in-person',
      'Get adequate rest - fatigue worsens emotional symptoms',
      'Exercise regularly - even short walks boost mood',
      'Practice relaxation techniques: deep breathing, meditation, prenatal yoga',
      'Reduce stress by saying no to non-essential commitments',
      'Ask for and accept help from others',
      'Maintain social connections and activities you enjoy',
      'Journal your thoughts and feelings',
      'Educate yourself about pregnancy to reduce anxiety',
    ],
    safeRemedies: [
      'Prenatal yoga classes combining movement and mindfulness',
      'Meditation and mindfulness apps (Expectful, Calm, Headspace)',
      'Omega-3 fatty acids from fish oil or walnuts (supports brain health)',
      'B vitamins from whole foods or supplements',
      'Regular exercise (releases endorphins naturally)',
      'Adequate sleep (7-9 hours) and rest when needed',
      'Therapy or counseling with prenatal mental health specialist',
      'Prenatal massage to reduce stress hormones',
      'Aromatherapy with pregnancy-safe essential oils (lavender, citrus)',
      'Magnesium supplements for relaxation (consult doctor)',
    ],
    whenToCallDoctor: [
      'Persistent sadness lasting more than two weeks',
      'Loss of interest in activities you normally enjoy',
      'Difficulty bonding with or feeling disconnected from pregnancy',
      'Constant worry or anxiety interfering with daily life',
      'Panic attacks or severe anxiety symptoms',
      'Thoughts of harming yourself or the baby',
      'Inability to eat or sleep due to anxiety or depression',
      'Mood symptoms affecting your ability to function or care for yourself',
    ],
    warningDangerSigns: [
      'Prenatal depression requiring treatment',
      'Anxiety disorders needing professional intervention',
      'Suicidal thoughts or ideation (emergency)',
      'Signs of obsessive-compulsive disorder',
      'Severe panic disorder',
    ],
    relatedSymptoms: ['fatigue-exhaustion', 'morning-sickness-nausea', 'frequent-urination', 'insomnia'],
    weeklyLinks: [4, 6, 8, 10, 12, 28, 30, 32, 34, 36, 38, 40],
    userExperiences: [
      {
        quote: 'I cried watching commercials! My husband was so patient. Knowing it was hormones and not me "being crazy" helped me accept the emotions.',
        name: 'Emma T.',
        week: 9,
      },
      {
        quote: 'Prenatal yoga really helped with anxiety. The breathing exercises gave me tools to calm down when I felt overwhelmed about becoming a mom.',
        name: 'Sophia K.',
        week: 32,
      },
      {
        quote: 'I finally talked to my doctor about the constant worry. She recommended a therapist who specialized in prenatal anxiety and it made all the difference.',
        name: 'Olivia P.',
        week: 28,
      },
    ],
    faqs: [
      {
        question: 'Are mood swings normal during pregnancy?',
        answer: 'Yes, mood swings are very common and normal during pregnancy, affecting the majority of pregnant women. They\'re caused by dramatic hormonal changes, particularly surges in estrogen and progesterone. These hormones affect neurotransmitters in your brain that regulate mood. Combined with physical discomfort, fatigue, and anxiety about upcoming life changes, emotional ups and downs are to be expected.',
      },
      {
        question: 'When should I worry about pregnancy mood changes?',
        answer: 'While mood swings are normal, you should contact your healthcare provider if you experience persistent sadness lasting more than two weeks, loss of interest in activities, severe anxiety interfering with daily life, panic attacks, thoughts of self-harm, or inability to function. These could be signs of prenatal depression or anxiety disorders, which are treatable conditions affecting 10-20% of pregnant women.',
      },
      {
        question: 'Can I take anxiety or depression medication while pregnant?',
        answer: 'Some medications for anxiety and depression are considered safe during pregnancy, while others are not recommended. Never stop taking prescribed psychiatric medications without consulting your doctor, as untreated mental health conditions can pose risks to both you and your baby. Your healthcare provider can help you weigh the risks and benefits and find the safest treatment option.',
      },
      {
        question: 'Will my mood improve after the first trimester?',
        answer: 'Many women experience emotional improvement during the second trimester, often called the "golden period" of pregnancy. Hormone levels stabilize, energy typically returns, and the pregnancy feels more real after seeing baby on ultrasound. However, anxiety may increase again in the third trimester as you approach labor and delivery. Every woman\'s experience is different.',
      },
    ],
  },
  {
    slug: 'breast-tenderness',
    title: 'Breast Tenderness',
    shortDescription: 'Sore, sensitive, swollen breasts - often one of the earliest pregnancy signs, affecting over 75% of women in the first trimester.',
    detailedDescription: [
      'Breast tenderness and soreness is often one of the first signs of pregnancy, sometimes occurring even before a missed period. Many women describe it as feeling similar to premenstrual breast pain, but often more intense and persistent.',
      'Your breasts are preparing for breastfeeding from the very beginning of pregnancy. They\'re growing, developing milk ducts, and increasing blood flow - all of which can create significant discomfort, especially in the first trimester.',
      'While breast tenderness typically improves after the first trimester as your body adjusts to hormone levels, your breasts will continue to grow and change throughout pregnancy. Understanding what to expect and how to find comfort is essential.',
    ],
    whatItIs: [
      'Soreness and tenderness throughout breasts',
      'Increased sensitivity, especially to touch or pressure',
      'Swelling and feeling of heaviness in breasts',
      'Tingling or prickling sensations',
      'Darkening of areolas and visible veins',
      'Painful nipples that are extra sensitive',
    ],
    whyItHappens: [
      'Rapidly increasing estrogen and progesterone hormone levels',
      'Breast tissue expanding and milk ducts developing',
      'Increased blood flow to breast tissue',
      'Fat layer building up in preparation for milk production',
      'Prolactin hormone stimulating mammary gland development',
      'Stretching of ligaments as breasts grow',
      'Increased sensitivity of nerve endings in breast tissue',
    ],
    commonWeeks: 'Weeks 4-12 (peaks early), improves weeks 13-27, may return weeks 28-40',
    trimestersAffected: ['First trimester (most intense)', 'Second trimester (usually improves)', 'Third trimester (some tenderness returns)'],
    reliefTips: [
      'Wear a supportive, well-fitting bra at all times, even to sleep',
      'Get professionally fitted for maternity bras as size changes',
      'Choose soft, seamless bras without underwires for comfort',
      'Apply cool or warm compresses (whichever feels better)',
      'Sleep in a comfortable sleep bra for nighttime support',
      'Avoid high-impact activities that cause breast bouncing',
      'Choose loose-fitting clothing that doesn\'t constrict breasts',
      'Be gentle when washing and drying breast area',
      'Apply soothing breast gel pads or cold cabbage leaves',
      'Avoid caffeine which can increase breast tenderness',
    ],
    safeRemedies: [
      'Supportive maternity bras with wide straps and full coverage',
      'Sports bras for additional support during exercise',
      'Warm showers letting water flow over breasts',
      'Breast massage with pregnancy-safe lotion or oil',
      'Acetaminophen (Tylenol) for pain relief if needed - consult doctor',
      'Vitamin E supplements may help (consult doctor first)',
      'Evening primrose oil (consult doctor about dosage)',
      'Magnesium supplements to reduce breast pain',
      'Cold gel packs wrapped in soft cloth for 10-15 minutes',
      'Lanolin cream for nipple soreness',
    ],
    whenToCallDoctor: [
      'Severe, persistent pain in one breast only',
      'Hard lump or significant breast mass',
      'Red, hot, or inflamed area on breast',
      'Nipple discharge that is bloody or unusual color',
      'Fever accompanied by breast pain',
      'Breast pain that suddenly worsens or changes character',
      'Skin changes like dimpling, puckering, or rash',
      'Inverted nipple that wasn\'t inverted before',
    ],
    warningDangerSigns: [
      'Signs of breast infection (mastitis) requiring treatment',
      'Breast abscess needing medical intervention',
      'Rare possibility of inflammatory breast cancer',
      'Significant changes requiring evaluation',
    ],
    relatedSymptoms: ['fatigue-exhaustion', 'morning-sickness-nausea', 'mood-swings-anxiety', 'frequent-urination'],
    weeklyLinks: [4, 5, 6, 7, 8, 9, 10, 11, 12],
    userExperiences: [
      {
        quote: 'My breasts were so tender I couldn\'t even hug people! Sleeping in a soft bra helped so much. By the second trimester, thankfully it got better.',
        name: 'Anna W.',
        week: 8,
      },
      {
        quote: 'I went up two cup sizes in the first trimester. Getting properly fitted for supportive maternity bras was a lifesaver.',
        name: 'Caroline D.',
        week: 11,
      },
      {
        quote: 'Cold compresses and avoiding caffeine helped with the tenderness. It was one of my first pregnancy symptoms before I even knew I was pregnant.',
        name: 'Grace H.',
        week: 6,
      },
    ],
    faqs: [
      {
        question: 'When does breast tenderness start in pregnancy?',
        answer: 'Breast tenderness often begins 1-2 weeks after conception, sometimes even before a missed period. It\'s one of the earliest pregnancy symptoms. For most women, it peaks around weeks 8-10 when hormone levels are highest, then gradually improves during the second trimester as your body adjusts.',
      },
      {
        question: 'Is breast pain a sign of a healthy pregnancy?',
        answer: 'Breast tenderness is generally a positive sign indicating normal hormone production, but its absence doesn\'t indicate a problem. About 75% of women experience breast tenderness, but 25% don\'t and have perfectly healthy pregnancies. The presence or absence of symptoms varies greatly between individuals.',
      },
      {
        question: 'How much will my breasts grow during pregnancy?',
        answer: 'Breast size typically increases 1-3 cup sizes during pregnancy, with most growth occurring in the first and third trimesters. Individual variation is significant - some women experience dramatic changes while others have minimal growth. Your breasts are preparing to produce milk, developing milk ducts and increasing fat stores.',
      },
      {
        question: 'Should I wear a bra to sleep during pregnancy?',
        answer: 'Many pregnant women find sleeping in a comfortable, supportive sleep bra or soft sports bra helps reduce breast pain and provides needed support. This is especially helpful if you\'re a stomach sleeper transitioning to side sleeping. Choose seamless, stretchy bras without underwires for nighttime comfort.',
      },
    ],
  },
  {
    slug: 'frequent-urination',
    title: 'Frequent Urination',
    shortDescription: 'Need to urinate more often, day and night, affecting nearly all pregnant women throughout pregnancy.',
    detailedDescription: [
      'Frequent urination is one of the earliest and most persistent symptoms of pregnancy. You may find yourself making multiple trips to the bathroom throughout the day and night, which can be especially disruptive to sleep in the first and third trimesters.',
      'This symptom typically begins in the first few weeks of pregnancy, improves somewhat during the second trimester, then returns with a vengeance in the third trimester as your growing baby puts increasing pressure on your bladder.',
      'While annoying and inconvenient, frequent urination is a normal part of pregnancy. However, understanding the difference between normal frequency and signs of a urinary tract infection (UTI) is important for your health.',
    ],
    whatItIs: [
      'Needing to urinate more frequently than usual',
      'Waking up multiple times at night to use bathroom',
      'Feeling urgency to urinate with little warning',
      'Passing only small amounts of urine despite strong urge',
      'Bladder feeling full even after urinating',
      'Occasional urine leakage when coughing, sneezing, or laughing (stress incontinence)',
    ],
    whyItHappens: [
      'Increased blood volume (50% more) needing to be filtered by kidneys',
      'Kidneys working more efficiently, processing fluids faster',
      'hCG hormone increasing blood flow to pelvic area',
      'Growing uterus putting pressure on bladder',
      'Baby\'s head pressing on bladder in third trimester',
      'Relaxation of pelvic floor muscles due to progesterone',
      'Increased fluid intake recommended during pregnancy',
      'Reduced bladder capacity as uterus takes up more space',
    ],
    commonWeeks: 'Weeks 4-12 (first appearance), improves weeks 14-27, returns and worsens weeks 28-40',
    trimestersAffected: ['First trimester (begins)', 'Second trimester (improves)', 'Third trimester (most frequent)'],
    reliefTips: [
      'Lean forward when urinating to fully empty bladder',
      'Do pelvic floor exercises (Kegels) daily to strengthen muscles',
      'Limit fluids 2-3 hours before bedtime to reduce nighttime trips',
      'Stay hydrated during the day but front-load fluid intake',
      'Avoid caffeine and carbonated beverages which increase urination',
      'Empty bladder completely each time you urinate',
      'Go to bathroom as soon as you feel the urge - don\'t hold it',
      'Wear pantiliners if experiencing leakage for comfort',
      'Avoid foods and drinks that irritate bladder (citrus, spicy foods)',
      'Double void - urinate, wait a moment, then try again',
    ],
    safeRemedies: [
      'Kegel exercises to strengthen pelvic floor: contract for 5 seconds, repeat 10-15 times, 3x daily',
      'Bladder training (if approved by doctor) to increase time between bathroom visits',
      'Pregnancy-safe pads or liners for leak protection',
      'Avoid diuretic foods and beverages that increase urination',
      'Maintain healthy weight gain as recommended by doctor',
      'Physical therapy specializing in pelvic floor if having significant issues',
      'Stay well hydrated despite frequency - don\'t limit water dangerously',
      'Cranberry juice (unsweetened) to support urinary tract health',
      'Wear comfortable clothing that\'s easy to remove quickly',
      'Plan routes with bathroom access when going out',
    ],
    whenToCallDoctor: [
      'Pain or burning sensation during urination',
      'Cloudy, bloody, or foul-smelling urine',
      'Fever or chills accompanying urinary symptoms',
      'Lower abdominal or back pain with urination',
      'Feeling like you need to urinate but unable to go',
      'Leaking urine continuously (possible rupture of membranes)',
      'Urinating significantly less than usual with normal fluid intake',
      'Severe urgency or incontinence suddenly worsening',
    ],
    warningDangerSigns: [
      'Urinary tract infection (UTI) requiring antibiotic treatment',
      'Kidney infection (more serious, needs immediate treatment)',
      'Gestational diabetes symptoms (excessive urination with increased thirst)',
      'Possible amniotic fluid leakage mistaken for urine',
    ],
    relatedSymptoms: ['fatigue-exhaustion', 'morning-sickness-nausea', 'swelling-edema', 'back-pain-sciatica'],
    weeklyLinks: [4, 5, 6, 7, 8, 9, 10, 28, 30, 32, 34, 36, 38, 39, 40],
    userExperiences: [
      {
        quote: 'I felt like I lived in the bathroom! I couldn\'t go anywhere without mapping out bathroom locations. It was exhausting but completely normal.',
        name: 'Victoria S.',
        week: 36,
      },
      {
        quote: 'The second trimester was such a relief - I could actually sleep through the night! But third trimester brought it back worse than before.',
        name: 'Megan A.',
        week: 33,
      },
      {
        quote: 'Kegel exercises really helped with the little leaks when sneezing. My doctor recommended them and they made a difference.',
        name: 'Hannah B.',
        week: 28,
      },
    ],
    faqs: [
      {
        question: 'Is frequent urination normal throughout entire pregnancy?',
        answer: 'Yes, frequent urination is one of the most common symptoms throughout pregnancy, though it varies by trimester. It typically starts in the first trimester due to hormones and increased blood volume, improves in the second trimester as the uterus rises above the pelvis, then returns in the third trimester when baby drops down and puts pressure on your bladder.',
      },
      {
        question: 'Should I limit my water intake to reduce bathroom trips?',
        answer: 'No, staying well-hydrated is crucial during pregnancy. Don\'t limit water intake - you need adequate fluids for amniotic fluid, increased blood volume, and preventing UTIs and constipation. Instead, try front-loading fluids earlier in the day and limiting intake 2-3 hours before bedtime to reduce nighttime bathroom trips.',
      },
      {
        question: 'How can I tell the difference between normal urination and a UTI?',
        answer: 'Normal frequent urination involves no pain and clear urine. A UTI typically causes burning or pain during urination, urgency with little urine produced, cloudy or strong-smelling urine, pelvic discomfort, or lower back pain. If you experience these symptoms, contact your healthcare provider immediately as UTIs require antibiotic treatment during pregnancy.',
      },
      {
        question: 'What are Kegel exercises and how do I do them?',
        answer: 'Kegel exercises strengthen your pelvic floor muscles, helping prevent and reduce urinary incontinence. To do them: identify the muscles by stopping urination mid-stream (only do this once to identify muscles). Then, contract these muscles for 5 seconds, relax for 5 seconds, and repeat 10-15 times, three times daily. You can do Kegels anywhere, anytime - no one can tell!',
      },
    ],
  },
  {
    slug: 'leg-cramps',
    title: 'Leg Cramps',
    shortDescription: 'Painful muscle spasms in calves and feet, especially at night, affecting about 50% of pregnant women in the second and third trimesters.',
    detailedDescription: [
      'Leg cramps, also called charley horses, are sudden, painful muscle spasms that typically occur in the calves but can also affect your feet and thighs. They\'re most common at night and can wake you from sleep with intense pain.',
      'These cramps usually begin in the second trimester and often worsen in the third trimester. While the exact cause isn\'t fully understood, they\'re likely related to changes in blood circulation, mineral imbalances, and the extra weight your legs are carrying.',
      'Though painful and disruptive, leg cramps are generally harmless. However, learning prevention strategies and quick relief techniques can significantly improve your comfort and sleep quality during pregnancy.',
    ],
    whatItIs: [
      'Sudden, sharp pain in calf, foot, or thigh muscles',
      'Hard, tight muscle that you can feel under the skin',
      'Cramping that wakes you from sleep at night',
      'Muscle spasm lasting from seconds to several minutes',
      'Residual soreness in the muscle after cramp releases',
      'Cramps often occurring when stretching or changing positions',
    ],
    whyItHappens: [
      'Extra weight putting strain on leg muscles',
      'Growing uterus putting pressure on blood vessels and nerves',
      'Changes in blood circulation to legs',
      'Fatigue from carrying additional pregnancy weight',
      'Calcium and magnesium imbalances or deficiencies',
      'Dehydration affecting muscle function',
      'Compression of nerves in legs due to pregnancy posture',
      'Reduced physical activity and circulation',
    ],
    commonWeeks: 'Weeks 14-40 (begins second trimester, peaks third trimester)',
    trimestersAffected: ['Second trimester (begins)', 'Third trimester (most common and severe)'],
    reliefTips: [
      'Stretch calf muscles immediately: straighten leg and flex foot toward shin',
      'Stand up and put weight on cramping leg',
      'Massage the cramping muscle firmly',
      'Apply heat with heating pad or warm compress after cramp subsides',
      'Walk around to restore blood flow',
      'Apply ice if muscle is sore after cramp',
      'Elevate legs when resting to improve circulation',
      'Avoid pointing toes when stretching or yawning in bed',
      'Wear supportive shoes during the day',
      'Stay active with regular gentle exercise',
    ],
    safeRemedies: [
      'Stretch calf muscles before bed: stand arm\'s length from wall, lean forward with heels flat',
      'Stay well-hydrated throughout the day',
      'Increase calcium-rich foods (dairy, leafy greens, fortified foods)',
      'Eat magnesium-rich foods (nuts, seeds, bananas, whole grains)',
      'Take warm bath before bed to relax muscles',
      'Prenatal yoga focusing on leg stretches',
      'Compression stockings during day to improve circulation',
      'Calcium and magnesium supplements if deficient (consult doctor)',
      'Avoid standing or sitting in one position too long',
      'Gentle leg massage before bed',
    ],
    whenToCallDoctor: [
      'Persistent calf pain that doesn\'t go away with stretching',
      'Leg pain with swelling, redness, or warmth (possible blood clot)',
      'Pain in only one leg that\'s worse than the other',
      'Severe, frequent cramps interfering with sleep and daily life',
      'Leg pain accompanied by shortness of breath or chest pain',
      'Visible redness or warm area over painful muscle',
      'Cramps not improving despite trying prevention strategies',
      'Numbness or tingling persisting after cramp releases',
    ],
    warningDangerSigns: [
      'Deep vein thrombosis (blood clot) - serious medical emergency',
      'Nerve compression requiring medical evaluation',
      'Severe mineral deficiencies needing intervention',
      'Signs of poor circulation requiring treatment',
    ],
    relatedSymptoms: ['back-pain-sciatica', 'swelling-edema', 'fatigue-exhaustion', 'round-ligament-pain'],
    weeklyLinks: [20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40],
    userExperiences: [
      {
        quote: 'The leg cramps at night were excruciating! Flexing my foot toward my shin and having my husband massage my calf helped release them.',
        name: 'Brittany M.',
        week: 32,
      },
      {
        quote: 'Stretching my calves before bed and taking magnesium supplements (with doctor approval) really reduced how often I got cramps.',
        name: 'Kelly F.',
        week: 28,
      },
      {
        quote: 'Staying hydrated was key for me. Once I made sure to drink enough water throughout the day, the cramps became much less frequent.',
        name: 'Danielle L.',
        week: 35,
      },
    ],
    faqs: [
      {
        question: 'Why do leg cramps happen more at night during pregnancy?',
        answer: 'Leg cramps are more common at night because: (1) you\'re lying still for extended periods, reducing circulation, (2) the weight of blankets can point your toes downward, triggering cramps, (3) muscle fatigue from carrying extra pregnancy weight all day peaks at night, and (4) calcium and magnesium levels may naturally dip at night. Stretching before bed can help prevent nighttime cramps.',
      },
      {
        question: 'Are leg cramps a sign of a serious problem?',
        answer: 'Most pregnancy leg cramps are harmless, though painful. However, call your doctor if you have persistent pain in one leg with swelling, redness, or warmth, as this could indicate a blood clot (deep vein thrombosis), which is more common in pregnancy and requires immediate medical attention. Occasional cramps in both legs that respond to stretching are typically not concerning.',
      },
      {
        question: 'What should I do when a leg cramp strikes?',
        answer: 'For immediate relief: (1) Straighten your leg and gently flex your foot toward your shin, (2) Stand up and put weight on the cramping leg, (3) Massage the muscle firmly, (4) Walk around to restore circulation, (5) Apply heat once the acute spasm subsides. Never point your toes during a cramp as this can worsen it. The cramp should release within 30 seconds to a few minutes.',
      },
      {
        question: 'Can calcium and magnesium supplements prevent leg cramps?',
        answer: 'Some studies suggest that calcium and magnesium supplementation may help reduce pregnancy leg cramps, though results are mixed. Many prenatal vitamins contain these minerals. If you\'re experiencing frequent cramps, talk to your doctor about checking your levels and whether additional supplementation is appropriate. Always consult your healthcare provider before adding supplements beyond your prenatal vitamin.',
      },
    ],
  },
  {
    slug: 'braxton-hicks',
    title: 'Braxton Hicks Contractions',
    shortDescription: 'Practice contractions causing irregular tightening of the uterus, typically beginning in the second or third trimester.',
    detailedDescription: [
      'Braxton Hicks contractions, often called "practice contractions," are irregular tightening sensations in your uterus that help prepare your body for labor. Unlike true labor contractions, they don\'t increase in intensity or frequency and don\'t cause cervical dilation.',
      'These contractions were named after Dr. John Braxton Hicks who first described them in 1872. They can begin as early as the second trimester but are most commonly felt in the third trimester, especially in the final weeks of pregnancy.',
      'Learning to distinguish between Braxton Hicks and true labor contractions is important, especially as you approach your due date. While Braxton Hicks are normal and harmless, knowing when to call your doctor is essential.',
    ],
    whatItIs: [
      'Tightening or hardening of uterus lasting 30 seconds to 2 minutes',
      'Irregular contractions that don\'t follow a pattern',
      'Painless or mildly uncomfortable sensations (usually not painful)',
      'Contractions that stop with rest, hydration, or position change',
      'Belly becoming hard and tight, then softening',
      'Sensations often triggered by activity, dehydration, or full bladder',
    ],
    whyItHappens: [
      'Uterus "practicing" and toning for actual labor',
      'Increased activity or physical exertion',
      'Dehydration causing uterine irritability',
      'Full bladder putting pressure on uterus',
      'Baby\'s movements and position changes',
      'After sexual activity or orgasm',
      'Someone touching your belly',
      'Normal part of pregnancy preparation in final weeks',
    ],
    commonWeeks: 'Weeks 20-40 (can begin earlier, most noticeable weeks 28-40)',
    trimestersAffected: ['Late second trimester (may begin)', 'Third trimester (most common)'],
    reliefTips: [
      'Rest and lie down on your left side',
      'Drink water - dehydration often triggers Braxton Hicks',
      'Change positions or activities',
      'Take a warm bath to relax uterine muscles',
      'Practice relaxation breathing techniques',
      'Empty your bladder frequently',
      'Reduce physical activity if they become frequent',
      'Gentle walking may help them subside',
      'Try different positions to relieve pressure',
      'Stay calm - remember they\'re normal and preparing your body',
    ],
    safeRemedies: [
      'Hydration - drink 2-3 glasses of water',
      'Warm (not hot) bath or shower',
      'Deep breathing exercises and relaxation',
      'Prenatal yoga and gentle stretching',
      'Resting in side-lying position',
      'Avoid activities that trigger them if becoming uncomfortable',
      'Empty bladder regularly throughout the day',
      'Light snack if it\'s been a while since eating',
      'Gentle belly massage',
      'Practice labor breathing techniques for when real contractions come',
    ],
    whenToCallDoctor: [
      'Contractions becoming regular and increasing in intensity',
      'More than 4 contractions per hour before 37 weeks',
      'Contractions accompanied by vaginal bleeding or fluid leakage',
      'Lower back pain with contractions that comes and goes',
      'Pelvic pressure or cramping with contractions',
      'Contractions don\'t stop with rest, hydration, and position change',
      'Significant change in baby\'s movement with contractions',
      'Any concerns about whether contractions are real labor',
    ],
    warningDangerSigns: [
      'Preterm labor before 37 weeks requiring immediate attention',
      'Rupture of membranes (water breaking)',
      'Signs of placental abruption',
      'True labor contractions needing evaluation',
    ],
    relatedSymptoms: ['back-pain-sciatica', 'round-ligament-pain', 'frequent-urination', 'pelvic-pressure'],
    weeklyLinks: [28, 30, 32, 34, 35, 36, 37, 38, 39, 40],
    userExperiences: [
      {
        quote: 'My belly would get rock hard for about a minute, then release. Drinking water and resting on my side always made them stop. They definitely felt different from real labor!',
        name: 'Patricia N.',
        week: 36,
      },
      {
        quote: 'I called my doctor the first time thinking it was labor. She explained Braxton Hicks are irregular and not painful. Real labor contractions were much more intense and had a pattern.',
        name: 'Melissa G.',
        week: 38,
      },
      {
        quote: 'I had tons of Braxton Hicks in my third trimester, especially when I was busy and forgot to hydrate. My body was definitely practicing!',
        name: 'Christina R.',
        week: 35,
      },
    ],
    faqs: [
      {
        question: 'How can I tell the difference between Braxton Hicks and real labor?',
        answer: 'Braxton Hicks are irregular, don\'t increase in intensity, stop with rest or position change, are usually painless or mildly uncomfortable, and don\'t have a regular pattern. True labor contractions are regular (5 minutes apart or less), increase in intensity and frequency, don\'t stop with rest, become progressively painful, and often include lower back pain. When in doubt, especially near your due date, call your healthcare provider.',
      },
      {
        question: 'When do Braxton Hicks typically start?',
        answer: 'Braxton Hicks can begin as early as 20 weeks, though many women don\'t notice them until the third trimester around 28-30 weeks. First-time mothers often notice them later than women who\'ve had previous pregnancies. Some women never consciously feel them at all. They typically increase in frequency as you approach your due date.',
      },
      {
        question: 'Are frequent Braxton Hicks contractions normal?',
        answer: 'Some women experience frequent Braxton Hicks, especially in the third trimester, and this is generally normal. However, if you\'re having more than 4-6 per hour before 37 weeks, or if they\'re becoming regular and painful, contact your healthcare provider to rule out preterm labor. After 37 weeks, frequent Braxton Hicks often mean your body is preparing for labor.',
      },
      {
        question: 'Does having lots of Braxton Hicks mean labor is coming soon?',
        answer: 'Not necessarily. While Braxton Hicks may increase in frequency as you approach your due date, having many of them doesn\'t reliably predict when you\'ll go into labor. Some women have frequent Braxton Hicks for weeks before labor begins, while others have few and go into labor suddenly. They\'re your body\'s way of preparing, but timing of actual labor varies greatly.',
      },
    ],
  },
  {
    slug: 'round-ligament-pain',
    title: 'Round Ligament Pain',
    shortDescription: 'Sharp, stabbing pain in lower abdomen or groin caused by stretching ligaments supporting the uterus, common in second trimester.',
    detailedDescription: [
      'Round ligament pain is a sharp, sudden pain in your lower abdomen or groin area that occurs when the round ligaments (which support your uterus) stretch and thin as your baby grows. It\'s one of the most common pregnancy aches and can be quite startling.',
      'This pain typically begins in the second trimester and may continue into the third trimester. It usually occurs on one or both sides of your lower belly or groin and is triggered by sudden movements, position changes, coughing, sneezing, or laughing.',
      'While round ligament pain can be sharp and uncomfortable, it\'s completely normal and harmless. Understanding what triggers it and how to prevent and manage the pain can help you feel more confident and comfortable.',
    ],
    whatItIs: [
      'Sharp, stabbing pain in lower belly or groin area',
      'Brief pain lasting a few seconds to minutes',
      'Usually felt on one side but can occur on both sides',
      'Pain triggered by sudden movements, standing up, or rolling over',
      'May occur when coughing, sneezing, laughing, or exercising',
      'Dull aching after the sharp pain subsides',
    ],
    whyItHappens: [
      'Round ligaments stretching as uterus grows and moves up in abdomen',
      'Ligaments becoming thinner and more prone to spasm',
      'Sudden movements causing ligaments to tighten quickly',
      'Weight of growing uterus pulling on ligaments',
      'Increased blood flow to ligaments making them more sensitive',
      'Rapid position changes stretching ligaments suddenly',
      'Hormones relaxing ligaments and making them more pliable',
    ],
    commonWeeks: 'Weeks 14-24 (most common), can continue through week 40',
    trimestersAffected: ['Second trimester (most common)', 'Third trimester (may continue)'],
    reliefTips: [
      'Move slowly and deliberately, avoiding sudden movements',
      'Bend and flex hips before coughing, sneezing, or laughing',
      'Roll onto your side before getting up from lying position',
      'Apply warmth to painful area with heating pad or warm compress',
      'Rest and take breaks when pain occurs',
      'Support belly with hands when changing positions',
      'Use pregnancy support belt during activities',
      'Practice good posture to reduce strain on ligaments',
      'Avoid activities that consistently trigger the pain',
      'Gentle stretching to keep ligaments flexible',
    ],
    safeRemedies: [
      'Prenatal yoga with focus on gentle stretching',
      'Swimming or water exercises to relieve pressure',
      'Warm baths to relax muscles and ligaments',
      'Cat-cow stretches to gently stretch lower abdomen',
      'Hip flexor stretches to reduce tension',
      'Maternity support belt to lift weight off ligaments',
      'Acetaminophen (Tylenol) for pain if needed - consult doctor',
      'Rest in comfortable side-lying position with pillow support',
      'Prenatal massage focusing on lower back and hips',
      'Slow, controlled movements throughout the day',
    ],
    whenToCallDoctor: [
      'Severe or persistent pain lasting more than a few minutes',
      'Pain accompanied by fever, chills, or bleeding',
      'Pain with regular contractions',
      'Difficulty walking or moving due to pain',
      'Pain accompanied by nausea, vomiting, or dizziness',
      'Burning sensation when urinating with the pain',
      'Pain that significantly worsens or changes character',
      'Pain on only one side that\'s constant (possible ovarian issue)',
    ],
    warningDangerSigns: [
      'Ovarian cyst torsion requiring emergency care',
      'Appendicitis symptoms requiring immediate attention',
      'Ectopic pregnancy (though unlikely in second/third trimester)',
      'Placental abruption with severe abdominal pain',
    ],
    relatedSymptoms: ['back-pain-sciatica', 'braxton-hicks', 'leg-cramps', 'pelvic-pressure'],
    weeklyLinks: [14, 16, 18, 20, 22, 24, 26, 28, 30],
    userExperiences: [
      {
        quote: 'The first time I felt round ligament pain, I thought something was seriously wrong! It was so sharp. But learning to move slowly and support my belly when turning really helped.',
        name: 'Allison K.',
        week: 20,
      },
      {
        quote: 'Sneezing was the worst trigger for me. I learned to bend my knees and brace my belly before sneezing and it made a huge difference.',
        name: 'Tiffany S.',
        week: 22,
      },
      {
        quote: 'The pregnancy support belt was a lifesaver. It took the weight off the ligaments and I had way less pain throughout the day.',
        name: 'Natalie J.',
        week: 24,
      },
    ],
    faqs: [
      {
        question: 'Is round ligament pain dangerous?',
        answer: 'No, round ligament pain is not dangerous and is a completely normal part of pregnancy. It\'s simply your body\'s ligaments stretching to accommodate your growing uterus and baby. While the sharp pain can be alarming, it\'s harmless. However, if pain is severe, persistent, or accompanied by other symptoms like fever, bleeding, or contractions, contact your healthcare provider.',
      },
      {
        question: 'How can I tell if it\'s round ligament pain or something serious?',
        answer: 'Round ligament pain is brief (seconds to a few minutes), sharp, occurs on one or both sides of lower abdomen or groin, is triggered by movement, and resolves with rest. Serious conditions typically involve persistent pain, fever, bleeding, vomiting, painful urination, or regular contractions. When in doubt, contact your healthcare provider to rule out other conditions.',
      },
      {
        question: 'When does round ligament pain typically occur?',
        answer: 'Round ligament pain most commonly begins in the second trimester (around weeks 14-20) when your uterus is growing rapidly and moving up out of the pelvis. It can continue into the third trimester. Some women experience it earlier, while others never notice it at all. It often improves or resolves in late pregnancy as growth slows.',
      },
      {
        question: 'What\'s the best way to prevent round ligament pain?',
        answer: 'Prevention strategies include: moving slowly and avoiding sudden movements, bending your hips before coughing or sneezing, supporting your belly when changing positions, wearing a pregnancy support belt during activities, maintaining good posture, doing gentle stretching exercises regularly, and staying active with low-impact activities like walking or swimming. These measures help keep ligaments flexible and reduce sudden strain.',
      },
    ],
  },
]

export function getSymptomTrackerData(slug: string): SymptomTrackerData | undefined {
  return symptomTrackerData.find((symptom) => symptom.slug === slug)
}

export const symptomCategories = {
  digestive: ['morning-sickness-nausea', 'heartburn-indigestion', 'constipation'],
  pain: ['back-pain-sciatica', 'leg-cramps', 'round-ligament-pain', 'breast-tenderness'],
  physical: ['fatigue-exhaustion', 'swelling-edema', 'frequent-urination', 'braxton-hicks'],
  emotional: ['mood-swings-anxiety'],
}
