// Pregnancy week-by-week data

export interface WeekData {
  week: number
  trimester: 1 | 2 | 3
  babySize: string
  babyLength: string
  babyWeight: string
  babyDevelopment: string[]
  momSymptoms: string[]
  nutritionTips: string[]
  toDo: string[]
  funFact: string
}

export const weeklyData: WeekData[] = [
  // First Trimester (Weeks 1-13)
  {
    week: 1,
    trimester: 1,
    babySize: 'Poppy seed',
    babyLength: 'Less than 0.1 inches',
    babyWeight: 'Less than 1 gram',
    babyDevelopment: [
      'Conception typically occurs at the end of week 2',
      'The fertilized egg begins its journey to the uterus',
      'Cells start dividing rapidly',
    ],
    momSymptoms: [
      'You may not know you\'re pregnant yet',
      'Your last menstrual period marks the start of pregnancy calculations',
    ],
    nutritionTips: [
      'Start taking prenatal vitamins with folic acid (400-800 mcg daily)',
      'Eat a balanced diet rich in fruits and vegetables',
      'Stay hydrated with plenty of water',
      'Limit caffeine to 200mg per day or less',
    ],
    toDo: [
      'Begin tracking your menstrual cycle',
      'Start taking prenatal vitamins',
      'Review your current medications with a doctor',
      'Maintain a healthy lifestyle',
    ],
    funFact: 'Pregnancy is calculated from the first day of your last menstrual period, even though conception typically happens two weeks later.',
  },
  {
    week: 2,
    trimester: 1,
    babySize: 'Poppy seed',
    babyLength: 'Less than 0.1 inches',
    babyWeight: 'Less than 1 gram',
    babyDevelopment: [
      'Ovulation typically occurs during this week',
      'The egg is released and may be fertilized',
      'If fertilized, the egg becomes a zygote',
      'Rapid cell division begins',
    ],
    momSymptoms: [
      'No pregnancy symptoms yet',
      'You may notice ovulation symptoms like increased cervical mucus',
    ],
    nutritionTips: [
      'Continue taking prenatal vitamins',
      'Eat foods rich in folate like leafy greens and legumes',
      'Include lean proteins in your diet',
      'Avoid alcohol and smoking',
    ],
    toDo: [
      'Track ovulation if trying to conceive',
      'Continue healthy lifestyle habits',
      'Reduce stress levels',
      'Get adequate sleep',
    ],
    funFact: 'Your baby\'s gender is determined at conception by whether the sperm carries an X or Y chromosome.',
  },
  {
    week: 3,
    trimester: 1,
    babySize: 'Sesame seed',
    babyLength: '0.04 inches',
    babyWeight: 'Less than 1 gram',
    babyDevelopment: [
      'The fertilized egg implants in the uterine lining',
      'The cells divide into two groups: embryo and placenta',
      'The amniotic sac begins to form',
      'Pregnancy hormone (hCG) production starts',
    ],
    momSymptoms: [
      'Possible light spotting from implantation',
      'Mild cramping',
      'Early pregnancy may not be detectable yet',
    ],
    nutritionTips: [
      'Continue prenatal vitamins with folic acid',
      'Eat iron-rich foods like lean meats and spinach',
      'Include calcium sources in your diet',
      'Stay hydrated',
    ],
    toDo: [
      'Watch for early pregnancy signs',
      'Continue taking prenatal vitamins',
      'Avoid harmful substances',
      'Maintain a healthy diet',
    ],
    funFact: 'Implantation typically occurs 6-12 days after fertilization, which is when pregnancy truly begins.',
  },
  {
    week: 4,
    trimester: 1,
    babySize: 'Poppy seed',
    babyLength: '0.04 inches',
    babyWeight: 'Less than 1 gram',
    babyDevelopment: [
      'The embryo consists of two layers that will develop into organs',
      'The amniotic sac and fluid form around the embryo',
      'The placenta begins to develop',
      'Neural tube (future brain and spine) starts forming',
    ],
    momSymptoms: [
      'Missed period',
      'Light spotting',
      'Mild cramping',
      'Breast tenderness',
      'Fatigue',
    ],
    nutritionTips: [
      'Folic acid is crucial for neural tube development',
      'Eat small, frequent meals if nausea begins',
      'Include whole grains for energy',
      'Avoid raw or undercooked foods',
    ],
    toDo: [
      'Take a home pregnancy test',
      'Schedule your first prenatal appointment',
      'Continue prenatal vitamins',
      'Start avoiding alcohol, smoking, and drugs',
    ],
    funFact: 'By the end of week 4, you can get a positive pregnancy test as hCG levels become detectable.',
  },
  {
    week: 5,
    trimester: 1,
    babySize: 'Sesame seed',
    babyLength: '0.13 inches',
    babyWeight: 'Less than 1 gram',
    babyDevelopment: [
      'The heart begins to beat',
      'The neural tube continues developing',
      'Tiny buds that will become arms and legs appear',
      'The umbilical cord forms',
    ],
    momSymptoms: [
      'Morning sickness may begin',
      'Increased urination',
      'Fatigue',
      'Breast tenderness',
      'Food aversions or cravings',
    ],
    nutritionTips: [
      'Eat ginger or peppermint for nausea relief',
      'Keep crackers by your bedside for morning sickness',
      'Stay hydrated with water and electrolyte drinks',
      'Eat protein-rich snacks',
    ],
    toDo: [
      'Confirm pregnancy with your doctor',
      'Begin tracking symptoms',
      'Research prenatal care providers',
      'Start avoiding cat litter and raw meat',
    ],
    funFact: 'Your baby\'s heart begins beating around day 22-23, even though it\'s only about the size of a poppy seed!',
  },
  {
    week: 6,
    trimester: 1,
    babySize: 'Lentil',
    babyLength: '0.25 inches',
    babyWeight: 'Less than 1 gram',
    babyDevelopment: [
      'Facial features begin forming',
      'The heart beats 100-160 times per minute',
      'Arm and leg buds grow',
      'Lungs, liver, and kidneys begin to develop',
    ],
    momSymptoms: [
      'Morning sickness intensifies',
      'Frequent urination',
      'Mood swings',
      'Bloating',
      'Heightened sense of smell',
    ],
    nutritionTips: [
      'Eat vitamin B6-rich foods to help with nausea',
      'Small, frequent meals throughout the day',
      'Avoid strong-smelling foods',
      'Stay hydrated',
    ],
    toDo: [
      'Schedule first prenatal appointment if not done',
      'Discuss prenatal testing options',
      'Start documenting your pregnancy journey',
      'Rest when needed',
    ],
    funFact: 'By week 6, your baby\'s heart is beating twice as fast as yours!',
  },
  {
    week: 7,
    trimester: 1,
    babySize: 'Blueberry',
    babyLength: '0.51 inches',
    babyWeight: '0.04 ounces',
    babyDevelopment: [
      'Brain and facial features are developing rapidly',
      'Hands and feet are emerging',
      'Digestive system is forming',
      'The tail is disappearing',
    ],
    momSymptoms: [
      'Increased morning sickness',
      'Frequent urination continues',
      'Excess saliva',
      'Constipation',
      'Emotional changes',
    ],
    nutritionTips: [
      'Increase fiber intake to help with constipation',
      'Drink plenty of water',
      'Eat foods rich in vitamin C',
      'Avoid greasy or spicy foods',
    ],
    toDo: [
      'Attend first prenatal appointment',
      'Discuss genetic screening options',
      'Ask about morning sickness remedies',
      'Consider pregnancy-safe exercise',
    ],
    funFact: 'Your baby is developing about a million cells every second at this stage!',
  },
  {
    week: 8,
    trimester: 1,
    babySize: 'Kidney bean',
    babyLength: '0.63 inches',
    babyWeight: '0.04 ounces',
    babyDevelopment: [
      'Webbed fingers and toes are forming',
      'The tail has disappeared',
      'Eyes are more visible',
      'Breathing tubes connect throat to lungs',
      'Nerve cells are branching out',
    ],
    momSymptoms: [
      'Heightened sense of smell',
      'Food aversions',
      'Breast enlargement',
      'Occasional cramping',
      'Increased vaginal discharge',
    ],
    nutritionTips: [
      'Continue prenatal vitamins',
      'Eat foods rich in omega-3 fatty acids',
      'Include dairy for calcium',
      'Snack on nuts and seeds',
    ],
    toDo: [
      'Stay hydrated',
      'Get plenty of rest',
      'Start thinking about maternity clothes',
      'Continue avoiding harmful substances',
    ],
    funFact: 'Your baby is now officially called a fetus instead of an embryo!',
  },
  {
    week: 9,
    trimester: 1,
    babySize: 'Grape',
    babyLength: '0.9 inches',
    babyWeight: '0.07 ounces',
    babyDevelopment: [
      'All essential organs have begun forming',
      'Fingers and toes are no longer webbed',
      'Earlobes are forming',
      'Muscles are developing',
      'Baby can start moving',
    ],
    momSymptoms: [
      'Nausea may peak this week',
      'Fatigue',
      'Breast tenderness',
      'Frequent urination',
      'Mood swings',
    ],
    nutritionTips: [
      'Eat small meals frequently',
      'Try ginger tea for nausea',
      'Include lean proteins',
      'Avoid empty calories',
    ],
    toDo: [
      'Continue prenatal appointments',
      'Rest when feeling fatigued',
      'Stay active with gentle exercise',
      'Join a pregnancy support group',
    ],
    funFact: 'Your baby\'s heart is now fully formed with four chambers!',
  },
  {
    week: 10,
    trimester: 1,
    babySize: 'Kumquat',
    babyLength: '1.2 inches',
    babyWeight: '0.14 ounces',
    babyDevelopment: [
      'Vital organs are functioning',
      'Bones and cartilage are forming',
      'Baby can bend limbs',
      'Tiny nails are developing',
      'Peach fuzz is starting to grow',
    ],
    momSymptoms: [
      'Visible veins due to increased blood flow',
      'Thicker hair',
      'Round ligament pain',
      'Heartburn may begin',
    ],
    nutritionTips: [
      'Eat calcium-rich foods for bone development',
      'Include vitamin D sources',
      'Stay hydrated',
      'Eat small meals to prevent heartburn',
    ],
    toDo: [
      'Consider first trimester screening tests',
      'Document pregnancy with photos',
      'Research birthing classes',
      'Start planning nursery',
    ],
    funFact: 'If you could peek inside, you\'d see your baby is now swallowing and kicking!',
  },
  {
    week: 11,
    trimester: 1,
    babySize: 'Fig',
    babyLength: '1.6 inches',
    babyWeight: '0.25 ounces',
    babyDevelopment: [
      'Hair follicles are forming',
      'Fingernails appear',
      'Baby is beginning to open and close fists',
      'Tooth buds are forming',
      'Genitals are developing',
    ],
    momSymptoms: [
      'Nausea may start to ease',
      'Increased energy in some women',
      'Skin changes may appear',
      'Increased appetite',
    ],
    nutritionTips: [
      'Eat plenty of vegetables and fruits',
      'Include whole grains',
      'Get adequate protein',
      'Continue prenatal vitamins',
    ],
    toDo: [
      'Consider genetic testing options',
      'Start maternity wardrobe shopping',
      'Continue regular exercise',
      'Plan for second trimester',
    ],
    funFact: 'Your baby\'s head makes up about half of its body length right now!',
  },
  {
    week: 12,
    trimester: 1,
    babySize: 'Lime',
    babyLength: '2.1 inches',
    babyWeight: '0.49 ounces',
    babyDevelopment: [
      'Reflexes are developing',
      'Intestines move into the abdomen',
      'Kidneys are producing urine',
      'Nerve cells are multiplying rapidly',
      'Baby can open and close mouth',
    ],
    momSymptoms: [
      'Reduced nausea for many women',
      'Increased energy',
      'Visible baby bump may appear',
      'Darkening of nipples',
    ],
    nutritionTips: [
      'Increase caloric intake slightly (about 300 extra calories)',
      'Focus on nutrient-dense foods',
      'Stay hydrated',
      'Include iron-rich foods',
    ],
    toDo: [
      'Schedule nuchal translucency scan if desired',
      'Start announcing pregnancy to friends and family',
      'Research maternity leave policies',
      'Continue healthy habits',
    ],
    funFact: 'Your baby\'s vocal cords are forming this week, though you won\'t hear any sounds for many months!',
  },
  {
    week: 13,
    trimester: 1,
    babySize: 'Peapod',
    babyLength: '2.9 inches',
    babyWeight: '0.81 ounces',
    babyDevelopment: [
      'Fingerprints are forming',
      'Eyes are moving closer together',
      'Baby can suck thumb',
      'Ovaries or testes are fully developed internally',
      'Vocal cords form',
    ],
    momSymptoms: [
      'Energy increases',
      'Morning sickness usually subsides',
      'Baby bump becomes more visible',
      'Round ligament pain',
    ],
    nutritionTips: [
      'Continue balanced nutrition',
      'Eat plenty of fruits and vegetables',
      'Include healthy fats',
      'Stay hydrated',
    ],
    toDo: [
      'Celebrate completing the first trimester!',
      'Schedule second trimester prenatal visits',
      'Consider maternity clothes shopping',
      'Start researching baby gear',
    ],
    funFact: 'Congratulations on reaching the end of your first trimester! The risk of miscarriage drops significantly after this point.',
  },

  // Second Trimester (Weeks 14-27)
  {
    week: 14,
    trimester: 2,
    babySize: 'Lemon',
    babyLength: '3.4 inches',
    babyWeight: '1.5 ounces',
    babyDevelopment: [
      'Facial expressions are possible',
      'Baby can squint, frown, and grimace',
      'Liver produces bile',
      'Spleen produces red blood cells',
      'Baby can urinate',
    ],
    momSymptoms: [
      'Increased energy',
      'Less nausea',
      'Growing belly',
      'Possible nasal congestion',
      'Increased appetite',
    ],
    nutritionTips: [
      'Eat iron-rich foods to prevent anemia',
      'Include vitamin C to help iron absorption',
      'Eat frequent, balanced meals',
      'Stay hydrated',
    ],
    toDo: [
      'Welcome to the second trimester!',
      'Schedule anatomy scan (usually at 18-20 weeks)',
      'Start researching childbirth classes',
      'Consider sharing pregnancy news publicly',
    ],
    funFact: 'Your baby can now make complex facial expressions, even though there\'s no one to see them yet!',
  },
  {
    week: 15,
    trimester: 2,
    babySize: 'Apple',
    babyLength: '3.98 inches',
    babyWeight: '2.5 ounces',
    babyDevelopment: [
      'Legs are growing longer than arms',
      'Bones are hardening',
      'Baby can sense light',
      'Taste buds are forming',
      'Hair pattern on scalp is developing',
    ],
    momSymptoms: [
      'Second trimester energy boost',
      'Possible nosebleeds',
      'Swollen gums',
      'Baby bump is showing',
      'Skin may be glowing',
    ],
    nutritionTips: [
      'Continue prenatal vitamins',
      'Eat calcium-rich foods',
      'Include protein at every meal',
      'Snack on healthy options',
    ],
    toDo: [
      'Continue prenatal appointments',
      'Start thinking about baby names',
      'Consider amniocentesis if recommended',
      'Exercise regularly',
    ],
    funFact: 'Your baby can now perceive light, even though their eyelids are still sealed shut!',
  },
  {
    week: 16,
    trimester: 2,
    babySize: 'Avocado',
    babyLength: '4.6 inches',
    babyWeight: '3.5 ounces',
    babyDevelopment: [
      'Head and body are more proportional',
      'Eyes are moving to proper position',
      'Ears are in final position',
      'Muscles are getting stronger',
      'Nervous system is functioning',
    ],
    momSymptoms: [
      'You may feel first flutters (quickening)',
      'Backaches may begin',
      'Increased vaginal discharge',
      'Dry, itchy eyes',
    ],
    nutritionTips: [
      'Eat foods rich in vitamin A for baby\'s eye development',
      'Include DHA for brain development',
      'Stay hydrated',
      'Eat magnesium-rich foods',
    ],
    toDo: [
      'Watch for first baby movements',
      'Schedule anatomy scan if not done',
      'Start prenatal yoga or swimming',
      'Research pediatricians',
    ],
    funFact: 'You might feel your baby move for the first time this week - it feels like butterflies or bubbles!',
  },
  {
    week: 17,
    trimester: 2,
    babySize: 'Turnip',
    babyLength: '5.1 inches',
    babyWeight: '5.9 ounces',
    babyDevelopment: [
      'Baby can move joints',
      'Skeleton is changing from cartilage to bone',
      'Sweat glands are developing',
      'Hearing is developing',
      'Baby practices breathing movements',
    ],
    momSymptoms: [
      'Increased appetite',
      'Baby movements may be more noticeable',
      'Possible heartburn',
      'Strange dreams',
    ],
    nutritionTips: [
      'Eat plenty of calcium for bone development',
      'Include foods rich in phosphorus',
      'Stay hydrated',
      'Eat small, frequent meals',
    ],
    toDo: [
      'Continue tracking baby movements',
      'Research birthing options',
      'Start thinking about nursery design',
      'Consider maternity photos',
    ],
    funFact: 'Your baby can now hear sounds from outside your body, including your voice!',
  },
  {
    week: 18,
    trimester: 2,
    babySize: 'Bell pepper',
    babyLength: '5.6 inches',
    babyWeight: '6.7 ounces',
    babyDevelopment: [
      'Baby yawns',
      'Fingerprints are in place',
      'If female, uterus and fallopian tubes are formed',
      'If male, genitals are visible',
      'Myelin (nerve coating) is forming',
    ],
    momSymptoms: [
      'Increased energy',
      'Dizziness',
      'Possible leg cramps',
      'Growing belly',
      'Backaches',
    ],
    nutritionTips: [
      'Eat iron-rich foods to prevent anemia',
      'Include folate-rich foods',
      'Stay hydrated',
      'Eat potassium-rich foods for leg cramps',
    ],
    toDo: [
      'Prepare for anatomy scan',
      'Decide if you want to know baby\'s gender',
      'Start shopping for nursery items',
      'Continue regular exercise',
    ],
    funFact: 'Your baby is developing their unique fingerprints right now!',
  },
  {
    week: 19,
    trimester: 2,
    babySize: 'Mango',
    babyLength: '6.0 inches',
    babyWeight: '8.5 ounces',
    babyDevelopment: [
      'Vernix caseosa (protective coating) covers baby\'s skin',
      'Permanent teeth buds form behind baby teeth',
      'Brain is developing specialized areas',
      'Sensory development is in high gear',
      'Arms and legs are proportional',
    ],
    momSymptoms: [
      'Round ligament pain',
      'Dizziness',
      'Abdominal pain',
      'Backaches',
      'Baby movements are stronger',
    ],
    nutritionTips: [
      'Eat foods rich in vitamin D',
      'Include omega-3 fatty acids',
      'Stay hydrated',
      'Eat small, frequent meals',
    ],
    toDo: [
      'Attend anatomy scan',
      'Start planning baby shower',
      'Research baby gear and registries',
      'Consider prenatal massage',
    ],
    funFact: 'If you\'re having a girl, she already has about 6 million eggs in her ovaries!',
  },
  {
    week: 20,
    trimester: 2,
    babySize: 'Banana',
    babyLength: '6.5 inches',
    babyWeight: '10.2 ounces',
    babyDevelopment: [
      'Baby is swallowing more',
      'Hair is growing',
      'Lanugo (fine hair) covers body',
      'Baby can hear and may respond to sounds',
      'Sleep and wake cycles are developing',
    ],
    momSymptoms: [
      'Halfway through pregnancy!',
      'Visible baby movements',
      'Increased vaginal discharge',
      'Possible varicose veins',
      'Shortness of breath',
    ],
    nutritionTips: [
      'Eat iron-rich foods',
      'Include vitamin C for iron absorption',
      'Stay hydrated',
      'Eat foods rich in calcium',
    ],
    toDo: [
      'Celebrate being halfway through!',
      'Review anatomy scan results',
      'Start preparing nursery',
      'Consider creating a birth plan',
    ],
    funFact: 'Congratulations! You\'re halfway through your pregnancy journey!',
  },
  {
    week: 21,
    trimester: 2,
    babySize: 'Carrot',
    babyLength: '10.5 inches',
    babyWeight: '12.7 ounces',
    babyDevelopment: [
      'Baby can hear your voice clearly',
      'Eyebrows and eyelids are fully formed',
      'Fingers and toes are fully formed',
      'Bone marrow is making blood cells',
      'Baby drinks amniotic fluid',
    ],
    momSymptoms: [
      'Increased appetite',
      'Possible varicose veins',
      'Stretch marks may appear',
      'Braxton Hicks contractions may start',
    ],
    nutritionTips: [
      'Eat plenty of fiber to prevent constipation',
      'Include lean proteins',
      'Stay hydrated',
      'Eat foods rich in vitamin E for skin',
    ],
    toDo: [
      'Talk and read to your baby',
      'Continue exercising safely',
      'Apply moisturizer for stretch marks',
      'Research childbirth classes',
    ],
    funFact: 'Your baby can now taste what you eat through the amniotic fluid!',
  },
  {
    week: 22,
    trimester: 2,
    babySize: 'Papaya',
    babyLength: '10.9 inches',
    babyWeight: '15.2 ounces',
    babyDevelopment: [
      'Eyelids and eyebrows are fully formed',
      'Lips are becoming more distinct',
      'Pancreas is developing',
      'Reproductive system continues developing',
      'Baby looks like a miniature newborn',
    ],
    momSymptoms: [
      'Increased libido for some women',
      'Possible leg cramps',
      'Constipation',
      'Increased vaginal discharge',
      'Skin changes',
    ],
    nutritionTips: [
      'Eat magnesium-rich foods for leg cramps',
      'Include fiber for digestion',
      'Stay hydrated',
      'Eat foods rich in vitamin A',
    ],
    toDo: [
      'Continue prenatal appointments',
      'Start childbirth classes',
      'Plan baby shower',
      'Consider cord blood banking',
    ],
    funFact: 'Your baby is now practicing facial expressions, preparing for their first smile!',
  },
  {
    week: 23,
    trimester: 2,
    babySize: 'Grapefruit',
    babyLength: '11.4 inches',
    babyWeight: '1.1 pounds',
    babyDevelopment: [
      'Baby can hear sounds from outside',
      'Lungs are developing blood vessels',
      'Skin is still translucent',
      'Bone marrow produces blood cells',
      'Baby practices breathing movements',
    ],
    momSymptoms: [
      'Swelling in feet and ankles',
      'Possible skin darkening (linea nigra)',
      'Braxton Hicks contractions',
      'Increased forgetfulness',
    ],
    nutritionTips: [
      'Eat foods rich in omega-3 for brain development',
      'Include folate-rich foods',
      'Reduce sodium to minimize swelling',
      'Stay hydrated',
    ],
    toDo: [
      'Elevate feet when resting',
      'Continue regular exercise',
      'Register for baby gear',
      'Research maternity leave',
    ],
    funFact: 'Your baby weighs about as much as a large mango and is getting chubby!',
  },
  {
    week: 24,
    trimester: 2,
    babySize: 'Cantaloupe',
    babyLength: '11.8 inches',
    babyWeight: '1.3 pounds',
    babyDevelopment: [
      'Baby is viable (could survive with medical help if born)',
      'Lungs are developing surfactant',
      'Taste buds are maturing',
      'Footprints and fingerprints are formed',
      'Brain is growing rapidly',
    ],
    momSymptoms: [
      'Glucose screening test',
      'Growing belly',
      'Possible carpal tunnel syndrome',
      'Increased appetite',
    ],
    nutritionTips: [
      'Monitor sugar intake for glucose test',
      'Eat complex carbohydrates',
      'Include lean proteins',
      'Stay hydrated',
    ],
    toDo: [
      'Complete glucose screening test',
      'Continue childbirth classes',
      'Start creating baby registry',
      'Research pediatricians',
    ],
    funFact: 'Your baby is considered viable this week - a major milestone!',
  },
  {
    week: 25,
    trimester: 2,
    babySize: 'Cauliflower',
    babyLength: '13.6 inches',
    babyWeight: '1.5 pounds',
    babyDevelopment: [
      'Baby may respond to touch through your belly',
      'Nostrils are opening',
      'Blood vessels in lungs are developing',
      'Vocal cords are functioning',
      'Spine is getting stronger',
    ],
    momSymptoms: [
      'Possible hemorrhoids',
      'Trouble sleeping',
      'Restless leg syndrome',
      'Increased appetite',
    ],
    nutritionTips: [
      'Eat fiber-rich foods',
      'Include magnesium for restless legs',
      'Stay hydrated',
      'Eat small meals before bed',
    ],
    toDo: [
      'Use pregnancy pillow for comfort',
      'Continue regular exercise',
      'Start planning nursery details',
      'Consider maternity photoshoot',
    ],
    funFact: 'Your baby\'s hair color and texture are being determined this week!',
  },
  {
    week: 26,
    trimester: 2,
    babySize: 'Lettuce',
    babyLength: '14 inches',
    babyWeight: '1.7 pounds',
    babyDevelopment: [
      'Eyes are beginning to open',
      'Baby can respond to light',
      'Lungs are developing branches',
      'Baby inhales and exhales amniotic fluid',
      'Brain wave activity increases',
    ],
    momSymptoms: [
      'Braxton Hicks more frequent',
      'Possible pelvic pain',
      'Shortness of breath',
      'Growing belly',
    ],
    nutritionTips: [
      'Eat iron-rich foods',
      'Include vitamin C',
      'Stay hydrated',
      'Eat small, frequent meals',
    ],
    toDo: [
      'Practice relaxation techniques',
      'Continue prenatal appointments',
      'Finalize baby registry',
      'Start infant CPR class',
    ],
    funFact: 'Your baby can now see light filtering through your belly!',
  },
  {
    week: 27,
    trimester: 2,
    babySize: 'Cauliflower',
    babyLength: '14.4 inches',
    babyWeight: '2 pounds',
    babyDevelopment: [
      'Baby can recognize your voice',
      'Lungs continue maturing',
      'Baby has regular sleep and wake cycles',
      'Brain is very active',
      'Hands are active',
    ],
    momSymptoms: [
      'Preparing for third trimester',
      'Possible sciatic nerve pain',
      'Increased Braxton Hicks',
      'Possible swelling',
    ],
    nutritionTips: [
      'Continue balanced nutrition',
      'Eat foods rich in vitamin K',
      'Include healthy fats',
      'Stay hydrated',
    ],
    toDo: [
      'Complete second trimester!',
      'Schedule third trimester appointments',
      'Start preparing hospital bag',
      'Review birth plan',
    ],
    funFact: 'Your baby now has a regular sleep-wake cycle and may even dream!',
  },

  // Third Trimester (Weeks 28-40)
  {
    week: 28,
    trimester: 3,
    babySize: 'Eggplant',
    babyLength: '14.8 inches',
    babyWeight: '2.2 pounds',
    babyDevelopment: [
      'Welcome to third trimester!',
      'Eyes can open and close',
      'Baby can blink',
      'Lungs can breathe air (with medical help)',
      'Brain is developing billions of neurons',
    ],
    momSymptoms: [
      'Shortness of breath',
      'Trouble sleeping',
      'Possible sciatic pain',
      'Frequent urination returns',
      'Braxton Hicks contractions',
    ],
    nutritionTips: [
      'Eat iron-rich foods for red blood cell production',
      'Include calcium for baby\'s bones',
      'Stay hydrated',
      'Eat protein at every meal',
    ],
    toDo: [
      'Schedule Tdap vaccine',
      'Start counting baby kicks',
      'Tour hospital or birth center',
      'Begin preparing hospital bag',
    ],
    funFact: 'Your baby can now distinguish between light and dark outside the womb!',
  },
  {
    week: 29,
    trimester: 3,
    babySize: 'Butternut squash',
    babyLength: '15.2 inches',
    babyWeight: '2.5 pounds',
    babyDevelopment: [
      'Baby is getting stronger kicks',
      'Bones are fully developed but still soft',
      'Baby can control body temperature',
      'White fat is accumulating',
      'Muscles and lungs continue maturing',
    ],
    momSymptoms: [
      'Heartburn',
      'Hemorrhoids',
      'Varicose veins',
      'Fatigue returns',
      'Pelvic pressure',
    ],
    nutritionTips: [
      'Eat small meals to avoid heartburn',
      'Include fiber for constipation',
      'Stay hydrated',
      'Avoid spicy and acidic foods',
    ],
    toDo: [
      'Count baby kicks daily',
      'Continue childbirth classes',
      'Finalize nursery setup',
      'Install car seat',
    ],
    funFact: 'Your baby is gaining about half a pound per week now!',
  },
  {
    week: 30,
    trimester: 3,
    babySize: 'Cabbage',
    babyLength: '15.7 inches',
    babyWeight: '3 pounds',
    babyDevelopment: [
      'Lanugo (fine hair) is disappearing',
      'Baby is getting plumper',
      'Bone marrow produces red blood cells',
      'Toenails are visible',
      'Head hair is growing',
    ],
    momSymptoms: [
      'Swelling in hands and feet',
      'Backaches',
      'Leaking colostrum',
      'Mood swings',
      'Nesting instinct may begin',
    ],
    nutritionTips: [
      'Reduce salt intake to minimize swelling',
      'Eat calcium-rich foods',
      'Include vitamin C',
      'Stay hydrated',
    ],
    toDo: [
      'Elevate feet to reduce swelling',
      'Continue tracking kicks',
      'Wash baby clothes',
      'Research breastfeeding',
    ],
    funFact: 'Your baby\'s brain is developing grooves and wrinkles to hold more brain cells!',
  },
  {
    week: 31,
    trimester: 3,
    babySize: 'Coconut',
    babyLength: '16.2 inches',
    babyWeight: '3.3 pounds',
    babyDevelopment: [
      'All five senses are functioning',
      'Baby can see, hear, smell, taste, and touch',
      'Lungs are nearly mature',
      'Baby moves to head-down position',
      'Fingernails reach fingertips',
    ],
    momSymptoms: [
      'Braxton Hicks more intense',
      'Possible pelvic pain',
      'Increased vaginal discharge',
      'Shortness of breath',
    ],
    nutritionTips: [
      'Continue prenatal vitamins',
      'Eat omega-3 rich foods',
      'Include iron-rich foods',
      'Stay hydrated',
    ],
    toDo: [
      'Discuss labor signs with doctor',
      'Finalize birth plan',
      'Prepare older siblings if any',
      'Stock up on postpartum supplies',
    ],
    funFact: 'Your baby is using all five senses now and learning about their environment!',
  },
  {
    week: 32,
    trimester: 3,
    babySize: 'Jicama',
    babyLength: '16.7 inches',
    babyWeight: '3.8 pounds',
    babyDevelopment: [
      'Baby practices breathing',
      'Digestive system is nearly complete',
      'Hair and nails continue growing',
      'Soft downy hair shedding',
      'Baby gains 1/2 pound per week',
    ],
    momSymptoms: [
      'Frequent urination',
      'Breast leakage increases',
      'Possible carpal tunnel',
      'Vivid dreams',
    ],
    nutritionTips: [
      'Eat frequent small meals',
      'Include healthy fats',
      'Stay hydrated',
      'Avoid lying down after eating',
    ],
    toDo: [
      'Start weekly prenatal appointments',
      'Review hospital bag checklist',
      'Prepare freezer meals',
      'Finalize pediatrician choice',
    ],
    funFact: 'Your baby is practicing all the skills they\'ll need for life outside the womb!',
  },
  {
    week: 33,
    trimester: 3,
    babySize: 'Pineapple',
    babyLength: '17.2 inches',
    babyWeight: '4.2 pounds',
    babyDevelopment: [
      'Skull bones are soft and not fused',
      'Immune system is developing',
      'Baby can detect light',
      'Pupils can dilate and contract',
      'Bones are hardening except skull',
    ],
    momSymptoms: [
      'Increased Braxton Hicks',
      'Forgetfulness (pregnancy brain)',
      'Clumsiness',
      'Trouble sleeping',
    ],
    nutritionTips: [
      'Eat calcium for baby\'s bones',
      'Include vitamin D',
      'Stay hydrated',
      'Eat iron-rich foods',
    ],
    toDo: [
      'Pack hospital bag',
      'Install infant car seat',
      'Take childbirth classes if not done',
      'Arrange childcare for older kids',
    ],
    funFact: 'Your baby\'s skull bones aren\'t fused to allow for easier passage through the birth canal!',
  },
  {
    week: 34,
    trimester: 3,
    babySize: 'Cantaloupe',
    babyLength: '17.7 inches',
    babyWeight: '4.7 pounds',
    babyDevelopment: [
      'Vernix (protective coating) thickens',
      'Fingernails reach end of fingers',
      'Central nervous system maturing',
      'Lungs are nearly mature',
      'Fat layers continue forming',
    ],
    momSymptoms: [
      'Vision changes',
      'Fatigue',
      'Pelvic pressure',
      'Possible constipation',
    ],
    nutritionTips: [
      'Eat foods rich in vitamin K',
      'Include probiotics',
      'Stay hydrated',
      'Eat frequent small meals',
    ],
    toDo: [
      'Discuss Group B strep test',
      'Review labor and delivery plan',
      'Prepare home for baby',
      'Pre-register at hospital',
    ],
    funFact: 'Your baby is about the length of a ruler and weighs as much as a pineapple!',
  },
  {
    week: 35,
    trimester: 3,
    babySize: 'Honeydew melon',
    babyLength: '18.2 inches',
    babyWeight: '5.3 pounds',
    babyDevelopment: [
      'Baby is running out of room',
      'Kidneys are fully developed',
      'Liver can process waste',
      'Lungs are almost fully mature',
      'Reflexes are coordinated',
    ],
    momSymptoms: [
      'Frequent urination',
      'Pelvic pressure',
      'Possible swelling',
      'Shortness of breath',
    ],
    nutritionTips: [
      'Continue balanced nutrition',
      'Eat easily digestible foods',
      'Stay hydrated',
      'Include vitamin C',
    ],
    toDo: [
      'Know signs of preterm labor',
      'Have hospital bag ready',
      'Arrange postpartum help',
      'Practice relaxation techniques',
    ],
    funFact: 'If born now, your baby has excellent chances of healthy survival!',
  },
  {
    week: 36,
    trimester: 3,
    babySize: 'Romaine lettuce',
    babyLength: '18.7 inches',
    babyWeight: '5.8 pounds',
    babyDevelopment: [
      'Baby is gaining an ounce per day',
      'Skin is becoming smooth',
      'Gums are rigid',
      'Circulation and immune systems complete',
      'Baby is considered early term',
    ],
    momSymptoms: [
      'Increased Braxton Hicks',
      'Pelvic pressure intensifies',
      'Possible lightning (baby dropping)',
      'More frequent bathroom trips',
    ],
    nutritionTips: [
      'Eat foods rich in vitamin K for blood clotting',
      'Include iron',
      'Stay hydrated',
      'Eat small frequent meals',
    ],
    toDo: [
      'Have weekly prenatal checkups',
      'Know signs of labor',
      'Finalize birth plan',
      'Rest as much as possible',
    ],
    funFact: 'Your baby is considered "early term" and could arrive any time now!',
  },
  {
    week: 37,
    trimester: 3,
    babySize: 'Swiss chard',
    babyLength: '19.1 inches',
    babyWeight: '6.3 pounds',
    babyDevelopment: [
      'Baby is full term!',
      'Baby practices breathing and sucking',
      'Baby can grasp firmly',
      'All organs can function independently',
      'Lanugo is mostly gone',
    ],
    momSymptoms: [
      'Excitement and nervousness',
      'Nesting instinct strong',
      'Possible mucus plug loss',
      'Increased discharge',
    ],
    nutritionTips: [
      'Continue healthy eating',
      'Stay hydrated',
      'Eat energy-boosting foods',
      'Include fiber',
    ],
    toDo: [
      'Celebrate full term!',
      'Have hospital bag by door',
      'Know route to hospital',
      'Rest when possible',
    ],
    funFact: 'Congratulations! Your baby is full term and ready to meet you!',
  },
  {
    week: 38,
    trimester: 3,
    babySize: 'Leek',
    babyLength: '19.6 inches',
    babyWeight: '6.8 pounds',
    babyDevelopment: [
      'Baby continues gaining weight',
      'Organs are fully developed',
      'Baby might have a full head of hair',
      'Meconium (first poop) building up',
      'Baby is ready for life outside',
    ],
    momSymptoms: [
      'Cervix may be dilating',
      'Possible bloody show',
      'Contractions may increase',
      'Water may break',
    ],
    nutritionTips: [
      'Eat light, nutritious meals',
      'Stay hydrated',
      'Avoid heavy meals',
      'Stock up on easy foods',
    ],
    toDo: [
      'Monitor contractions',
      'Know when to call doctor',
      'Have emergency contacts ready',
      'Try to relax and rest',
    ],
    funFact: 'Your baby could arrive any day now - stay alert for labor signs!',
  },
  {
    week: 39,
    trimester: 3,
    babySize: 'Mini watermelon',
    babyLength: '19.9 inches',
    babyWeight: '7.3 pounds',
    babyDevelopment: [
      'Baby is continuing to gain weight',
      'Lungs are producing more surfactant',
      'Baby\'s brain is still developing',
      'Antibodies from mom support immune system',
      'Baby is ready to be born',
    ],
    momSymptoms: [
      'Lightning crotch pains',
      'Increased contractions',
      'Possible water breaking',
      'Anticipation and anxiety',
    ],
    nutritionTips: [
      'Eat light meals',
      'Stay hydrated',
      'Avoid large meals',
      'Keep energy snacks handy',
    ],
    toDo: [
      'Rest as much as possible',
      'Know labor signs',
      'Keep phone charged',
      'Try to stay calm',
    ],
    funFact: 'Labor could start at any moment - be ready and trust your body!',
  },
  {
    week: 40,
    trimester: 3,
    babySize: 'Small pumpkin',
    babyLength: '20.2 inches',
    babyWeight: '7.6 pounds',
    babyDevelopment: [
      'Baby is ready to meet you!',
      'Organs are fully functioning',
      'Baby has strong reflexes',
      'Coordination is developed',
      'Baby is at full development',
    ],
    momSymptoms: [
      'Ready to meet baby',
      'Possible increased contractions',
      'Anxious or impatient',
      'Labor could start any time',
    ],
    nutritionTips: [
      'Stay hydrated',
      'Eat light, healthy meals',
      'Keep energy foods ready',
      'Avoid overeating',
    ],
    toDo: [
      'Know when to go to hospital',
      'Keep calm and patient',
      'Walk to encourage labor',
      'Rest when possible',
    ],
    funFact: 'Congratulations on reaching your due date! Your baby will arrive when they\'re ready!',
  },
]

// Helper function to get data for a specific week
export function getWeekData(week: number): WeekData | undefined {
  return weeklyData.find((w) => w.week === week)
}

// Helper function to get all weeks for a trimester
export function getWeeksByTrimester(trimester: 1 | 2 | 3): WeekData[] {
  return weeklyData.filter((w) => w.trimester === trimester)
}
